### ISSUE TITLE
Plotting API defaults should be over-ridden with user defined kwargs

### ISSUE THREAD

**Issue by jsignell** [intake/intake#171]
<img width="1018" alt="screen shot 2018-09-28 at 3 43 32 pm" src="https://user-images.githubusercontent.com/4806877/46230071-6a5d9100-c335-11e8-874b-923610c768c2.png">

**Comment by martindurant** [comment]
Agree, good report. 
Does it also happen if you do `.bivariate(x='model', y='emission')`?

Are you intending to fix this?

**Comment by jsignell** [comment]
>Does it also happen if you do .bivariate(x='model', y='emission')

Yes. I haven't yet decided just trying to keep track of issues as they crop up.

**Comment by martindurant** [comment]
Please tag someone in hv, if you don't think you will get to it, as the traceback implicates them more than Intake.

**Comment by jsignell** [comment]
@philippjfr

**Comment by philippjfr** [comment]
Yes let's move this issue to hvplot.

**Comment by martindurant** [comment]
Is there an issue tracking this in hvplot? If so, I would close this, and link.

**Comment by jsignell** [comment]
Moved to https://github.com/pyviz/hvplot/issues/181
