### ISSUE TITLE
Driver args and parameters example

### ISSUE THREAD

**Issue by benjaminsingleton** [intake/intake#195]
Apologies if this is a stupid question, but I'm having difficulty finding information / examples in the documentation about how to use args and parameters together in a custom driver. I need to pass to the driver the username and password environment variables, which I know is [possible](https://intake.readthedocs.io/en/latest/catalog.html#parameter-definition), but I couldn't find an example of custom driver where this is implemented.

Any pointers to examples would be greatly appreciated! Looking forward to using `intake `at my organization.

**Comment by martindurant** [comment]
I agree that an explicit example of this would be a nice addition to the [examples](https://intake.readthedocs.io/en/latest/examples.html) page. I talked about this in my recent presentation at PyData NY, but the video is not yet available, so I'll try to answer here. Any advice you can give on cleaning this up into an example or some part of the documentation would be appreciated. It is far from clear, but one of the [tests](https://github.com/ContinuumIO/intake/blob/master/intake/catalog/tests/test_local.py#L333) does demonstrate that this functionality works.

There are two separate concerns to be addressed in your question.

- A given driver knows nothing about intake "parameters", they are expected to simply take a number of arguments in the implementation class's `__init__` method. 
- Any argument in a data-source specification can have its value substituted with a named user parameter, and those parameters, in turn, can draw their default values from the environment.

So you might have a driver defined like

```
class MyDriver(DataSource):
    def __init__(self, username, metadata=None):
        ...
```

and a spec like

```
sources:
  source_with_username:
    description: For demonstration
    args:
      username: "{{user}}"
    parameters:
      user:
        description: The username
        type: str
        default: "env(USER)"
```

which, if the user doesn't specify an explicit give their own input, will pass the value of the environment variable "USER" as the value of `username` when calling the class.

**Comment by benjaminsingleton** [comment]
This is very helpful, thank you! Once I get a working simple example, I'll
look to improve some of the documentation on this use case.

**Comment by benjaminsingleton** [comment]
@martindurant I was able to pass in the username and password as arguments to the driver and successfully return data, so thanks!

As I mentioned, I intend to create an example from the data, but I wanted to ask for some additional guidance so I can build in the functionality described below, which will be typical of a lot of my use cases for intake and I would assume for some others as well. If you prefer that I move this kind of questioning to StackOverflow, to another issue,  or someplace else, please let me know and I'd be happy to oblige.

Say I have a database table with 100 million rows called `orders`. I will almost never want to load in the entire orders table. I usually want to load in orders between a start date and an end date or by some other filtered value (like `order_type` or `amount`). Is there any way to pass all of the `parameters` into the `arguments` section of the catalog as a dictionary? I will use these key-value pairs to change the SQL statement that would otherwise return the entire `orders` table in the `_load(self)` function in the driver.

Quick default parameter syntax question: in the example above, if I wanted to default to return orders in the last five years, I would set the `end_dt` to `default: "today"`, but how should I represent the `start_dt` default, which should be `datetime.today() - datetime.timedelta(days=5*365)`. Is something like that currently supported in the catalog?

Because I often don't know exactly what to expect in the data, I regularly just want to see a preview of it with actual values. If I were querying the database directly, I would write `LIMIT 100`. Is there a preferred method of doing this? I can imagine writing a `.preview()` function in the driver or I could create a `preview` parameter in the catalog that accepts boolean values. What do you recommend?

Lastly, to the data analyst/scientist, would the implementation look something like this?

```
import intake
cat = intake.open_catalog('catalog.yaml')
df = cat.command_codes.get(start_dt=..., end_dt=..., order_type=..., amount=...).read()
```

Apologies for the length of this post, and I appreciate your time!

**Comment by martindurant** [comment]
This is a fine place for this kind of question and, again, if you have advice on how the documentation and examples can be made better, it would be much appreciated.

It is anticipated that a data source may refer to a whole data-set, which is too big for memory, and can then only be processed either by iterating with `read_chunked` or `to_dask`. However, you could easily have several data sources based on the same dataset, or use parameters to select from a larger data-set to end up with manageable pieces, or even use the [alias](https://intake.readthedocs.io/en/latest/api_base.html#intake.source.base.AliasSource) mechanism to pass data sources to another driver for further filtering. Which option is best is up to the catalog author, and doubtless depends on the specifics of the problem. It sounds like in your situation, you would prefer to push filtering to the server, so parameters or several "views" onto the same data-set sound best.

> Is there any way to pass all of the parameters into the arguments section of the catalog as a dictionary?

This is not how things are currently implemented, parameters are only used at the time of data source instantiation, in the method `LocalCatalogEntry._create_open_args`, which fills in argument templated with the parameter values (user-supplied, or defaults). However, the `expand_templates` function that is called allows for optionally passing back those names that do not get used, and I don't see why these should not be passed to the source as a dictionary as you describe.

> should be `datetime.today() - datetime.timedelta(days=5*365)`. Is something like that currently supported

No, the only functions currently supported for expansion of the defaults are for environment variables and external shell. Others could be possible, but it does not seem right to try to put executable code directly into the catalog spec like this. However, a custom driver is free to have whatever internal defaults it likes, or interpret strings to mean specific things, like any python code. Suggestions on a comprehensive grammar of parameters that would be able to express your requirements welcome here.

> I regularly just want to see a preview of it with actual values. If I were querying the database directly,

This is actually what intake_sql does already, although it may be buried in the Dask code, and may involve reading the whole of the first partition. Other drivers like ElasticSearch are more explicit about reading N rows, to figure out dtypes. However, a `head()` or `preview()` method does sounds like something that users would want. It would require implementation on a driver-by-driver basis, would not be useful for some unpartionionable data types, and not make any sense for some data that is not obviously sequential (like N-D arrays). You could make a separate issue to request the feature to get discussion.

> df = cat.orders.get(start_dt=..., end_dt=..., order_type=..., amount=...)

Yes, that's exactly how you specify parameter values as a user. The `get` verb is actually optional and assumed, you have the same behaviour with `cat.orders(start_dt=...)`. Any parameter not given will take its default value, if there is one.

**Comment by benjaminsingleton** [comment]
Appreciate the feedback and guidance. Once I implement all of this successfully, I will contribute back to the documentation to help clarify some of the parts that I had some difficulty following.

**Comment by martindurant** [comment]
@benjaminsingleton , this seems to have slipped through the cracks. Are you still thinking to work on this, is there any way I can help? Happy to talk with you in person.

**Comment by youngsaj** [comment]
I was trying to figure out this type of scenario as well.
A specialized driver.
A set of data files returned from wildcard.
I get metadata from all the files, for determining UI setup later on when specific files are picked.
The interesting aspect of read though could be dynamic reads based on UI selection.
fdata = mycat.CATITEM.read_partition([0, [100,200],[10,100]])

read_partition documentation noted that i can be something more complex.
Here I went with [0, [100, 200], [10, 100]] where it's index of list of files, then within that file the range of data (the range of data will be dynamic).
Whether this is an intention for i in read_partition I'm not sure, but that actually did work.

Is that the intention of i for read_partition?

Or is there a better mechanism that this (#195) might cover.

**Comment by martindurant** [comment]
Yes, that is a totally appropriate use for the parameter `i` and we do do that for the array and xarray implementations already (e.g., https://github.com/intake/intake/blob/master/intake/source/zarr.py#L62 ). It is only the most basing form or partitioning (lists, dataframes) that will always have `i` as a simple integer between 0 and `npartitions`. Normally, I would expect the partitions to be discreet and able to be concatenated to the whole - e.g., so that you can make a dask array out of array pieces - but that is in the choice of the driver author.

**Comment by youngsaj** [comment]
Thanks for the example, the thing I'm noticing now is that my _get_schema does some busy work at getting a good amount of metadata from a number of partitions, that aren't necessarily going to be concatenated to the whole.  i.e. a directory with *.tiff that holds numerous files.  Maybe my use of schema for this chunky bit of metadata(static per file) isn't the best way to handle it?  It does work, but might bog down what I want to be dynamically speedy when focused on a specific file.

**Comment by martindurant** [comment]
That sounds like a design question for you :|

Obviously, touching every file will be slow where there are many files, but it may be necessary if you want to provide an overall view of the dataset. Perhaps you could provide an escape hatch to assume the metadata is always the same or have an alternative way to infer it for a given dataset (e.g., pass in the required value and have it in the source prescription).

**Comment by youngsaj** [comment]
Simple enough, using .get() and some further logic works great!
Once I get this up public I'll point you to it, but that may take a while yet.
