### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by ElSaico** [intake/intake#197]
There are three modes I can think of:

* Dask bags
* `read_json`-style DataFrame
* `json_normalize`-style DataFrame (my immediate user case and what inspired this request in the first place)

Quite likely harder than it looks, though, given the possible flexibility.

**Comment by martindurant** [comment]
Certainly sounds reasonable.
Is the [dask function](http://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.read_json) already close to what you would want?

**Comment by ian-r-rose** [comment]
Does `TextFilesSource` support loading into dataframes (in the same way that `dd.read_json` or `pd.read_json` do)? I see that it's default `container` type is `'python'`.

**Comment by martindurant** [comment]
No, but it exposes a `dask.bag` which you can call `.to_dataframe` on - which is similar, but not the same, as calling ``dd.read_json`` directly.

**Comment by martindurant** [comment]
Closing here meant "I am not planning on working on this", but if there is interest from someone else, that would be great. After all, since the dask function exists, it should be fairly easy.
