### ISSUE TITLE
Is Python 2 support currently intended?

### ISSUE THREAD

**Issue by danielballan** [intake/intake#228]
I couldn't find a general issue tracking the status of (or roadmap for) Python 2.7 support in intake. I notice some 2+3-isms in the source (usage of `six`, etc.) but I also notice that CI tests are [only run against 3.6](https://github.com/ContinuumIO/intake/blob/master/.travis.yml#L15). Is full support for 2.7 still intended? If so, shall I add a 2.7 build to the CI to verify it is not accidentally broken?

As a separate question, I would personally advocate for building consensus to drop Python 2.7 as soon as practical.

**Comment by seibert** [comment]
Given how new intake is, and the abandonment of Python 2 by the SciPy ecosystem happening in 2019, I don't think it is unreasonable to drop Python 2 by the end of the year.

That said, since the current code base should work for Python 2, I think it makes sense to add it to the CI configuration to make sure it does until dropping Python 2 is agreed upon.

**Comment by martindurant** [comment]
I completely agree with your concerns, and encourage other people to speak up on this issue.

I believe that at the moment, tests will fail for py2, and the pypi/conda selectors are for py3. Originally, Intake was developed with py2 in mind, and most of the code will be fine, but this has slipped as some of the plugins required py3-only dependencies, and external packages like numpy and dask are actively pursuing py3-only right now (or, in some cases, are having conversations about the same). 

From our point of view, it would be reasonable to investigate how much work py2 support would be for the base, thinking that there may well be legacy data loading packages that Intake wants to make use of.

**Comment by seibert** [comment]
I agree that plugins may have to drop Python 2 on a different and quicker schedule.  If the Intake core can preserve/restore Python 2 compatibility for the short term, that would at least give plugin authors the option to decide what they want to do.

**Comment by danielballan** [comment]
One possibility would be to re-instate Python 2 support, cut a release, and then declare intake Python 3 only from there on out, as happened [in this case](https://github.com/dask/dask-kubernetes/pull/114#issuecomment-453314929).

**Comment by martindurant** [comment]
As things stand, I think it would take some work to get a py2 version out. I'll look into how bad it is.

**Comment by danielballan** [comment]
Was [this change](https://github.com/intake/intake/pull/287/files#diff-2eeaed663bd0d25b7e608891384b7298R40) intentional? We test on 3.6 and 3.7, and [intake 0.4.2 is marked as 3.5+](https://pypi.org/project/intake/0.4.2/) but intake 0.4.3 and 0.4.4 are [marked as 2.5+](https://pypi.org/project/intake/0.4.4/).

**Comment by martindurant** [comment]
I have no idea how that happened!
