### ISSUE TITLE
DAT as a caching mechanism

### ISSUE THREAD

**Issue by martindurant** [intake/intake#267]
See https://docs.datproject.org/ecosystem
DAT is a secure peer-to-peer directory sharing service popular for large scientific datasets, whereby the whole directory contents is a dereferencable blob, and the network transport is automatically handled.

This is an ideal cache use case for Intake, you just have the reference, and DAT puts the files in the right place.

cc @pzwang

**Comment by danielballan** [comment]
[IPFS](https://ipfs.io/) is also interesting in this space.

**Comment by martindurant** [comment]
Sure - if we can just call an external helper to fetch files by some ID, it would work nicely. The ID plus distribution system to fetch the bytes, and the Intake loading mechanism to make sense of what they contain. One possible problem, that a single DAT or other structure could contain many data-sets, so they should not be re-cached for each.

**Comment by pzwang** [comment]
I am inclined towards using Dat initially b/c sharing of scientific datasets were the original use case for which it was designed, and Sloan & Moore foundations have funded it to this end.

(Also it doesn't have complexifiers around cryptocurrency which IPFS carries along with FileCoin.)

My $.02..
