### ISSUE TITLE
(Compressed) Excel driver

### ISSUE THREAD

**Issue by gansanay** [intake/intake#274]
Hi,

My main data sources at the moment are remote zipped Excel files, so I was starting to build a data package and a driver package but I need your feedback: should it be an Excel Driver with a compression type option, is anyone already working on it? I would use pandas Excel reader as the reader.

If all lights are green I will start this intake-excel driver.

Regards,
Guillaume

**Comment by martindurant** [comment]
Can pandas-excel read from remote, or from an arbitrary file-like object?

Does zipped mean .zip, with multiple files in each archive, or .gz, with one file per archive?

An excel driver in general sounds like a great idea (one partition per input file, perhaps with filename parsing). The questions above will help define how best to achieve it.

**Comment by gansanay** [comment]
Thank you for your quick answer!

pd.read_excel() can read from a string or from several URL types. Your second question is actually very relevant to structure the driver.

**Comment by martindurant** [comment]
Did you mean to close the issue?

> pd.read_excel() can read from a string or from several URL types.

more importantly, from our point of view, it seems to accept arbitrary files-like instances, so we can treat is like any of the other read_* pandas functions

**Comment by gansanay** [comment]
I closed the issue, maybe wrongly understanding that drivers belonged to
separate packages. If you think an excel driver belongs to the main package
then sorry for closing!

Le mer. 20 févr. 2019 à 18:39, Martin Durant <notifications@github.com> a
écrit :

**Comment by martindurant** [comment]
I agree that it should be a separate package as for the other drivers, but this issue can remain live until that exists, and a reference to it would be nice.

**Comment by martindurant** [comment]
@gansanay , how are you finding building your driver?

**Comment by gansanay** [comment]
I am close to a first version. I struggled a bit but unlocked some problems when I used code from intake-sql. Still sometimes I don't know why intake doesn't find my intake-excel plugin.

Is it ok for you if I point you to an unfinished draft of the driver to get your feedback?

**Comment by martindurant** [comment]
Yes, certainly, do.
When testing, if you make a catalogue with explicit driver, that should be the easiest way to test
```yaml
sources:
  test1:
    driver: intake_excel.base.SetOfExcelFiles
    ...
```

Probably you are being caught by the fact that Intake only auto-imports intake-* packages if they are not already imported, so order of import statements can matter.

**Comment by gansanay** [comment]
I just uploaded the current version at https://github.com/franprix/intake-excel

At the moment there are many things missing: tests, versioneer configuration, error handling, a more advanced handling of sets of Excel files in zip files... and comments.

Working on it but when I conda build this source code and import intake it seems it doesn't find this driver.

**Comment by martindurant** [comment]
If I do `pip install -e . --no-deps` in the source dir, `import intake` indeed exposes `intake.open_excel`. 

After `conda build` and `conda install`, `import intake` again exposes `intake.open_excel`. 

In the long term you may want to build the package using conda-forge, which effectively does the same thing as pip.

**Comment by gansanay** [comment]
I actually had some errors which prevented plugin loading in previous versions. Now I have to work on more tests for the diverse situations (gzipped excel files, set of Excel files in zip) and on the driver API for these.

Feel free to have a look at the driver and tell me what is wrong or missing, maybe you can help me concerning the error during Travis tests https://travis-ci.org/franprix/intake-excel:

```
tests/test_intake_excel.py:3: in <module>
    import intake
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/intake/__init__.py:16: in <module>
    from .source.base import Schema, DataSource
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/intake/source/base.py:11: in <module>
    from .cache import make_caches
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/intake/source/cache.py:19: in <module>
    from dask.bytes.utils import infer_storage_options
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/dask/bytes/__init__.py:4: in <module>
    from .core import read_bytes, open_files
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/dask/bytes/core.py:9: in <module>
    from toolz import merge
E   ModuleNotFoundError: No module named 'toolz'
```

**Comment by martindurant** [comment]
`toolz` is in the requirements: https://github.com/intake/intake/blob/master/requirements.txt#L15 , so should have been installed.
Most Intake development probably happens on conda, but its good to have people working with the pip route too.

**Comment by martindurant** [comment]
Any progress on this, @gansanay ?

**Comment by martindurant** [comment]
@gansanay  ?

**Comment by martindurant** [comment]
Would be happy to see progress here, but will close for now.

**Comment by hunterowens** [comment]
has anybody picked this back up? I'd be happy to take a thwack at it?

**Comment by martindurant** [comment]
The pandas excel reader now supports reading from general fsspec URLs, including decompression on the fly (and/or caching).

Also, and independently, https://github.com/edjdavid/intake-excel appeared recently. I haven't tried it myself, but I expect it to work OK. If you have some effort spare, @hunterowens , I suggest you check in on that repo.
