### ISSUE TITLE
Explore RemoteCatalog with entries that open RemoteCatalogs on other servers

### ISSUE THREAD

**Issue by danielballan** [intake/intake#278]
Prompted by [this comment](https://github.com/intake/intake/pull/271#issuecomment-466064845)

**Comment by danielballan** [comment]
For what it's worth, while I can't really make full sense of this yet, it does seem like a reasonable suggestion that might come up in the future.

**Comment by martindurant** [comment]
Oh, it's done - you can persist a remote catalog containing remote-only sources and rehydrate it later; also, you can refer to remote catalogs inside normal catalogs. You can also refer to explicit remote sources within an ordinary YAML cat, but I don't expect anyone to actually do this.

**Comment by martindurant** [comment]
I don't intend to explicitly document this stuff until someone asks for it.
