### ISSUE TITLE
Failing to discover catalogs installed as conda packages

### ISSUE THREAD

**Issue by yergi** [intake/intake#292]
When installing catalogs as conda packages, the intake module fails to find them and load them into `intake.cat` as suggested by the [Data Scientist example](https://github.com/martindurant/intake-release-blog/blob/master/data_scientist.ipynb).

At first I thought this was an issue with the package I had built, but on installing two of the sample datasets from the `intake` channel I'm running into the same issue. I've verified that all the YAML files had successfully installed in `$PREFIX/share/intake/` so I'm not sure why intake is not discovering them.

**Comment by martindurant** [comment]
How exactly did you install things on your system? If I do
```
> conda create -n blah ipython intake data-us-states -c conda-forge -c intake
> conda activate blah
> ipython

In [ ]: import intake
In [ ]: list(intake.cat)
Out [ ]: ['states']
```

**Comment by yergi** [comment]
I already had the my environment created with intake installed, as it was the environment I used to create my package. After publishing my package to our internal conda channel, I tried downloading it and ran into this issue.

I then installed both the `data-us-states` and `us_crime` catalogs using `conda install data-us-states -c intake`

I restarted my Python kernel just to be sure and after running `import intake` and `list(intake.cat)` I get an empty list back.

However when I created a fresh environment installing everything at once it worked fine???

**Comment by martindurant** [comment]
That is indeed puzzling - did you get the same versions of the packages in each of the environments?

**Comment by yergi** [comment]
I did some more digging last night and I believe that the issue isn't with intake itself, but rather with how PyCharm's Python Console behaves when connecting to a remote interpreter.

All of our work is actually run on a Linux server, that I connect to via SSH on PyCharm. When running the conda environment in PyCharm's Python Console in this way, the `list(intake.cat)` command returns an empty list. However, if I launch a terminal on the server and run the `conda activate` and `ipython` commands, then the `list(intake.cat)` is populated.

So I'm guessing PyCharm has issues working perfectly with remote Conda environments.

**Comment by martindurant** [comment]
That is pretty weird, I thought pycharm uses the same jupyter-kernel technology, but maybe it messes with the paths to enable debug breakpoints and the like.

**Comment by yergi** [comment]
I think it does when the conda environment is local, as then you can use the "Conda Environment" option. However I think the SSH Interpreter option doesn't realize it is a conda environment and that's what is causing this issue.
