### ISSUE TITLE
Quickstart "unsafe" warning

### ISSUE THREAD

**Issue by rsignell-usgs** [intake/intake#295]
I just tried running the Intake QuickStart, and it throws a warning that, while isn't really anything to worry about, includes the words `default Loader is unsafe` which new users might find concerning:
 ```python
import intake
ds = intake.open_csv('states_*.csv')
print(ds)
```
produces the warning:
```
/opt/conda/lib/python3.6/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/opt/conda/lib/python3.6/site-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
```

**Comment by martindurant** [comment]
I believe pyyaml released a new version, may look into it. We probably *want* unsafe loading, which allows things like python tuples to be interpreted.

**Comment by martindurant** [comment]
Confirmed: the pip and conda-forge versions of pyyaml are 5.1 (released last week), but the anaconda main channel one is still 3.13, which is why I didn't see this.
