### ISSUE TITLE
nesting of catalogs in a deep directory structure

### ISSUE THREAD

**Issue by naomi-henderson** [intake/intake#300]
Hi folks, especially @martindurant to whom I spoke briefly today.  I am working with a large collection of data (CMIP6) containing mostly netcdf and zarr objects - consisting of thousands of files in a directory tree.  Obviously I cannot write flat YAML catalogs in this case.  What I am thinking is putting a 'config.yaml' file in EVERY directory and making the sources section point to config.yaml files in each of its subdirectories and so on ...  The nesting would be about 6-7 levels deep.

Here is my [example](https://github.com/naomi-henderson/cmip6-catalog).

This works great, except for two (hopefully) small issues (for more details, see above link)

  1. \<tab\> completion will work to get from the parent to child catalog (sub-directory), but then will not get to the grandchild catalog (sub-sub-directory)
  
  2. The path in each YAML file is relative to the `<dir>` in the initial `intake.open_catalog('<dir>/config.yaml')`. This means that if I `intake.open_catalog(config.yaml)` in a subdirectory, the paths are going to need to be relative to this subdirectory, but I have had to hard-wire them to an arbitrary initial parent directory.

If I am re-inventing the wheel and you could point me to an existing solution, that would be very much appreciated.  Or maybe there is a parent/child setting or equivalent to make this work?

**Comment by martindurant** [comment]
xref : https://github.com/NCAR/intake-esm/pull/46

**Comment by naomi-henderson** [comment]
sorry, how does that help?  intake-esm allows you to peruse a structured directory, such as CMIP6, to create a dataframe to persist as a csv file so that one can query the dataframe in various ways and subselect data.  The whole dataframe needs to be recreated every time files are added to the directory.  That is not what I need, which is a nested catalog.

**Comment by martindurant** [comment]
On the subject of tab-completions, what's going on here is a little subtle, bear with me.

A catalog entry is the set of parameters defined in a catalog (e.g., YAML file, or some query), but the concrete data source instance is only created later. This allows for the passing of parameters and overrides:

    source = cat.entry()  # defaults
    source = cat.entry(thing='new')  # passed parameter makes different source

Instantiating the source may take some work, e.g., loading a YAML file in the typical catalogue case.

When you do cat.entry.read() (or other method), Intake assumes you are OK with the defaults and want to operate on the source directly. This "shortcut" leads to ambiguity in what the thing after dot means,

    cat.level1.level2  # this is an entry, equivalent to cat.level1().level2
    cat.level1.level2()  # this is a source

only the latter one of these supports list() and tab-completion.

So we could
- overload list and dir on an entry to get the default source's set of possible completions; the former only makes sense if the entry is for a catalog
- make a special case for an entry of catalog type, so that the source is always instantiated immediately

**Comment by martindurant** [comment]
> sorry, how does that help

I am referencing as the scope seems to be related.

**Comment by martindurant** [comment]
I didn't quite understand point 2, above: does `{{ CATALOG_DIR }}/` do the trick? Perhaps an example of what you mean would be good (caveat: I have't yet looked at your linked code).

**Comment by naomi-henderson** [comment]
yes! {{ CATALOG_DIR }}/ solves the second point. thank you

**Comment by martindurant** [comment]
The ULRs [here](https://github.com/naomi-henderson/cmip6-catalog/blob/master/catalog/IPSL_CM6A_LR/historical/config.yaml#L4) appear to be wrong, as they include "/historical/", which is already in the catalogue directory.

You may be interested in 
```
>>> cat2 = cat.search('temperature', depth=8)
>>> list(cat2)
['CNRM_CM6_1.historical.r1i1p1f2.tas',
 'CNRM_CM6_1.historical.r2i1p1f2.tas',
 'CNRM_ESM2_1.historical.r1i1p1f2.tas',
 'GISS_E2_1_G.historical.r1i1p1f1.tas']
```
which walks the whole tree to the given number of levels, and finds all sources containing the given search word(s). You see that the key names they get in the output cat are made of the path elements, the "names" of the intermediate cats. For a broad and deeply nested tree, such an operation could take a long time.

**Comment by martindurant** [comment]
The following code would be enough to pluck the tab-completions from the sub-cats:
```diff
--- a/intake/catalog/entry.py
+++ b/intake/catalog/entry.py
@@ -127,6 +127,12 @@ class CatalogEntry(DictSerialiseMixin):
         # TODO: only consider attr not starting with "_"?
         return getattr(self._get_default_source(), attr)

+    def __dir__(self):
+        selflist = {'describe', 'describe_open', 'get',
+                    'has_been_persisted', 'plots'}
+        selflist.update(set(dir(self._get_default_source())))
+        return list(sorted(selflist))
+
     def __getitem__(self, item):
         """Pass getitem to data source, assuming default parameters
```

Any thoughts? cc @jsignell @seibert

**Comment by naomi-henderson** [comment]
Thanks @martindurant , I have fixed that yaml file with the extra 'historical' in the paths.  

Yes, the cat.search is useful, thanks again. I will add it to my little notebook in that example in case someone else is interested

**Comment by naomi-henderson** [comment]
So, hopefully to motivate the above code that @martindurant proposes, here is why I want the structure suggested in https://github.com/naomi-henderson/cmip6-catalog

Once this works (including the tab completion), then we also pass on the job of generating a minimalist 'config.yaml' to `intake` for every directory.  If a config.yaml already exists either because:

- we are at the bottom of the tree and want to source the data
- we want to add description or metadata to a directory 

then `intake` uses it, otherwise it just generates the sources which consist of the subdirectories.

This way we have turned any hierarchy of data into an object totally seen from intake

Thoughts? @rabernat?

**Comment by rabernat** [comment]
This seems like a very promising way forward. It would be good to get feedback from the NCAR folks like @andersy005 and @matt-long to ensure that it is also compatible with their needs.

**Comment by andersy005** [comment]
@naomi-henderson 
> What I am thinking is putting a 'config.yaml' file in EVERY directory and making the sources section point to config.yaml files in each of its subdirectories and so on .

This is a great idea! I have two questions though:

1) Does this approach assume that the user have write permissions in the directory and its sub-directories? In our case here at NCAR, for most community datasets, we have ready permission only! As a result, we wouldn't be able to take full advantage of this approach. 

2) For CMIP, it is possible to have thousands/hundreds of directories and subdirectories. How easy would it be to generate `config.yaml` in each directory and its subdirectories?

**Comment by naomi-henderson** [comment]
@andersy005 , so see https://github.com/intake/intake/issues/300#issuecomment-475599550
That is why I would like `intake` to generate the equivalent `config.yaml` files on the fly so they are  not needed in each and every directory and subdirectory.  The `config.yaml` files would be an optional way to put extra metadata and links in where desired, but could be totally left out. 

We still have to think more about what is to be done at the level of the netcdf files (my example is for there to be a `config.yaml` which has the zarr sources that have links to the pangeo-data) - but it would be possible to handle that on the fly, also.  I am just trying to get us to take little steps in the right direction ...

**Comment by andersy005** [comment]
> That is why I would like intake to generate the equivalent config.yaml files on the fly so they are not needed in each and every directory and subdirectory. 

This would definitely be a nice feature to have. Please keep me posted on your progress on this

**Comment by martindurant** [comment]
I can well imagine an extra kwarg to YAMLFileCatalog, which, when set, regards subdirectories of some URL location as subcats, which themselves can contain more subcats from nested directories *and* entries from any catalogue file matching some name template.

However:
- this would need fsspec to work across file-systems, in order to get file listings and is_dir (Dask's versions of the filesystems do not implement this). Note that s3fs and gcsfs have PRs to become compatible and based on fsspec, but these are not complete or merged and will likely wait until Dask and others go py3-only
- it wouldn't work for githubcontent: the directory containing the [root cat](https://raw.githubusercontent.com/naomi-henderson/cmip6-catalog/master/catalog/config.yaml) is https://raw.githubusercontent.com/naomi-henderson/cmip6-catalog/master/catalog/ and does *not* list its contents. You would have to crawl https://github.com/naomi-henderson/cmip6-catalog and infer the appropriate "raw" URLs. This is not a problem on s3/gcs/azure; the data are actually in GCS in this case.
- Given these things, it still may make sense to have a catalogue *service* which can be queried and returns the entries from the deep tree structure. In the simplest case this is a YAML file containing all 
entries, but some database system allowing complex queries would be much more flexible, even though it would require a new driver. [intake-bluesky](https://github.com/NSLS-II/intake-bluesky/) is a good template here, where the dataset details are stored in mongodb.

--

I should have been more specific above with search:
```
In [19]: cat2 = cat.search('temperature', depth=8)

In [20]: list(cat2)
Out[20]:
['CNRM_CM6_1.historical.r1i1p1f2.tas',
 'CNRM_CM6_1.historical.r2i1p1f2.tas',
 'CNRM_ESM2_1.historical.r1i1p1f2.tas',
 'GISS_E2_1_G.historical.r1i1p1f1.tas',
 'IPSL_CM6A_LR.historical.r1i1p1f1.tas',
 'IPSL_CM6A_LR.historical.r2i1p1f1.tas',
 'IPSL_CM6A_LR.historical.r3i1p1f1.tas',
 'IPSL_CM6A_LR.historical.r4i1p1f1.tas',
 'IPSL_CM6A_LR.historical.r5i1p1f1.tas',
 'IPSL_CM6A_LR.historical.r6i1p1f1.tas',
 'IPSL_CM6A_LR.historical.r7i1p1f1.tas']

In [21]: cat2['CN<TAB>
                     CNRM_CM6_1.h…2.tas
                     CNRM_CM6_1.h…2.tas
                     CNRM_ESM2_1.h…2.tas

In [21]: cat2['CNRM_CM6_1.historical.r1i1p1f2.tas']
Out[21]: <Catalog Entry: tas>
```
As you can see, the dot-notation does indeed get you there, but you can use the getitem syntax to get tab-completion of the full name of the data. Of course, the search process went through all directories, which may not be what you wanted.

**Comment by naomi-henderson** [comment]
@martindurant  Ah yes, I realized that, but that assumes I know what variable I want to find.  What if I just want to do data discovery, and know that tas is available, but also interested that pr and huss are in the same ensemble?

**Comment by martindurant** [comment]
Right, that sounds exactly like a more complex, structured query which the `.search()` method is unlikely to implement: you would probably want indexing in a real data service such as the example in intake-bluesky. Intake could have an opinion on a good way to do this, perhaps have such an index-and-query system implemented in the intake server, or perhaps stored in a sqlite DB file or... a few options here and we don't have a plan as such yet.

The ability to list directories as subcats, given a file-system that deals sensibly with directories, could be implemented fairly easily, but would force us into using fsspec or the file-system backends (s3fs, gcsfs) directly.

**Comment by martindurant** [comment]
ref https://github.com/intake/intake/issues/309

**Comment by martindurant** [comment]
@naomi-henderson , would you like to try again with Intake master ?

**Comment by naomi-henderson** [comment]
@martindurant , I finally got a change to test this. Fantastic, it works.  I can now <tab> complete all the way down the tree. Thanks!   I think this issue can now be closed, no?

**Comment by martindurant** [comment]
Glad to hear it.

**Comment by naomi-henderson** [comment]
Sorry, one more suggestion - and probably not good form, but would be convenient if the subdirs were listed first, or somehow marked as subdirectories! There are so many methods and the subdirs get lost in the suggested alphabetized completions.  I know, I know, totally absurd but would be nice 8-). Feel free to say no

**Comment by martindurant** [comment]
I believe that `dir()` will automatically alphabetise (this is explicit in my implementation), but maybe not, I can check. I could also implement `_ipython_key_completions_`, which allows you to define whatever order you like, but I think that only applies to `[...]` getitem syntax.

**Comment by naomi-henderson** [comment]
I noticed that your return from `__dir__` was sorted, so thought perhaps you could prepend the '_get_default_source()' list to the rest ...

**Comment by naomi-henderson** [comment]
so instead, you could have:
```
    def __dir__(self):
        selflist = {'describe', 'describe_open', 'get',
                    'has_been_persisted', 'plots'}
        selflist.update(dir(self))
        return list(self._get_default_source())+list(sorted(selflist))
```
yes, ugly, but it works

**Comment by martindurant** [comment]
Sure I can put that in. I am surprised that it works, I thought python sorted anyway (perhaps only when displaying the output)

**Comment by martindurant** [comment]
Your exception handler seems to also catch not-found and presumably other errors. I suggest it should catch only 405 Method-not-allowed, which as an exception looks like
```
requests.exceptions.HTTPError("501 Server Error: Unsupported method ...
```

**Comment by martindurant** [comment]
Really? I am seeing a sorted list anyway, and the [doc](https://docs.python.org/3/reference/datamodel.html#object.__dir__) says this is expected. Perhaps it depends on python version?
