### ISSUE TITLE
FileNotFoundError on Windows

### ISSUE THREAD

**Issue by Code4SAFrankie** [intake/intake#304]
import intake
import pandas as pd

df = intake.open_csv('{species}.csv').read()

Gives me the following from Jupyter Lab (the csv files was moved to the same directory as the notebook, but did not work from a subdirectory either):

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-0b3ffdd682c3> in <module>
      2 import pandas as pd
      3 
----> 4 df = intake.open_csv('{species}.csv').read()
      5 
      6 def fill_day(v):

e:\wpy-3710\python-3.7.1.amd64\lib\site-packages\intake\source\csv.py in read(self)
     62 
     63     def read(self):
---> 64         self._get_schema()
     65         return self._dataframe.compute()
     66 

e:\wpy-3710\python-3.7.1.amd64\lib\site-packages\intake\source\csv.py in _get_schema(self)
     47             self._dataframe = dask.dataframe.read_csv(
     48                 urlpath, storage_options=self._storage_options,
---> 49                 **self._csv_kwargs)
     50 
     51         dtypes = self._dataframe._meta.dtypes.to_dict()

e:\wpy-3710\python-3.7.1.amd64\lib\site-packages\dask\dataframe\io\csv.py in read(urlpath, blocksize, collection, lineterminator, compression, sample, enforce, assume_missing, storage_options, include_path_column, **kwargs)
    483                            storage_options=storage_options,
    484                            include_path_column=include_path_column,
--> 485                            **kwargs)
    486     read.__doc__ = READ_DOC_TEMPLATE.format(reader=reader_name,
    487                                             file_type=file_type)

e:\wpy-3710\python-3.7.1.amd64\lib\site-packages\dask\dataframe\io\csv.py in read_pandas(reader, urlpath, blocksize, collection, lineterminator, compression, sample, enforce, assume_missing, storage_options, include_path_column, **kwargs)
    339                        compression=compression,
    340                        include_path=include_path_column,
--> 341                        **(storage_options or {}))
    342 
    343     if include_path_column:

e:\wpy-3710\python-3.7.1.amd64\lib\site-packages\dask\bytes\core.py in read_bytes(urlpath, delimiter, not_zero, blocksize, sample, compression, include_path, **kwargs)
     96         for path in paths:
     97             try:
---> 98                 size = logical_size(fs, path, compression)
     99             except ValueError:
    100                 raise ValueError("Cannot do chunked reads on files compressed "

e:\wpy-3710\python-3.7.1.amd64\lib\site-packages\dask\bytes\core.py in logical_size(fs, path, compression)
    520 
    521     if compression is None:
--> 522         return fs.size(path)
    523     elif compression in seekable_files:
    524         with OpenFile(fs, path, compression=compression) as f:

e:\wpy-3710\python-3.7.1.amd64\lib\site-packages\dask\bytes\local.py in size(self, path)
     65     def size(self, path):
     66         """Size in bytes of the file at path"""
---> 67         return os.stat(self._normalize_path(path)).st_size
     68 
     69     def _get_pyarrow_filesystem(self):

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'e:\\work\\python\\pydata_dc_2018\\{species}.csv'

This is on:

Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32

**Comment by martindurant** [comment]
What are the names of the files you are wanting to load? Would you mind trying with the full path instead of just the local, relative one?

@jsignell , can you think of a reason that the path matching would fail - perhaps because these are Windows paths?

**Comment by Code4SAFrankie** [comment]
It's the files from @jsignell 's talk, so things like Acadian_Flycatcher.csv

It gives the same error with the full path. I rechecked and the path is definitely e:\work\python\pydata_dc_2018\ to get to Acadian_Flycatcher.csv

**Comment by martindurant** [comment]
Would you mind trying the same path but with "/" instead of the "\" (or, actually, "\\")?

**Comment by jsignell** [comment]
I can't reproduce on my windows10 VM. One think I would recommend is that you use `df = intake.open_csv('./{species}.csv').read()` since that way species should resolve to just the file name rather than the full path. Could you report your intake and dask version?

**Comment by martindurant** [comment]
@Code4SAFrankie , we suspect you have an older version of Intake, can you please update?

**Comment by Code4SAFrankie** [comment]
Thanks updating intake fixed it.
