### ISSUE TITLE
Best practices for naming catalogs

### ISSUE THREAD

**Issue by jsignell** [intake/intake#305]
I've been wondering what the best practices should be for naming catalogs. I've been leaning towards: 

 - a single catalog in a dir - catalog.yml 
 - more than one catalog in a dir - name them based on their contents

I like naming catalogs catalog.yml because it makes it clear what the role for the file is (it functions like an environment.yml). If that is recommended though - then we might want to make some attempt to get the name of the catalog from the dirname.

**Comment by martindurant** [comment]
> get the name of the catalog from the dirname

Perhaps the "name" a catalog wishes to have should be given in the metadata section? 

We mentioned this elsewhere, but catalogues may currently rename themselves depending on the file name or number of files for multifile; totally agree that some general logic and recommendations here would be useful.

**Comment by jsignell** [comment]
Does a catalog have its own metadata section? I don't know if I've ever seen that used.

**Comment by martindurant** [comment]
They optionally do, but we don't make much use of them. Currently, it can specify drivers to pre-load that might be needed by the cat, and a metadata version which for now is always 1.

**Comment by martindurant** [comment]
https://intake.readthedocs.io/en/latest/catalog.html#metadata

**Comment by jsignell** [comment]
Ok I propose that if name is in cat.metadata, then that should be used instead of filename. That would have really nice parallels with environment.yml. 

For instance: `catalog.yml` would start with
```yaml
name: landsat
sources: ...
```

**Comment by martindurant** [comment]
^ here you have `name` as a separate entry, not part of the metadata. That can be fine too.

**Comment by jsignell** [comment]
whoops. I do prefer it as a separate entry.

**Comment by martindurant** [comment]
I'm OK with allowing that; so the priority order would be
- name given in the spec
- name given by the caller, e.g., the entry name of the super cat
- name of the file/directory or something else derived from the path

**Comment by jsignell** [comment]
I think the priority order should be:
 
 1. name given by open function `intake.open_catalog(fn, name='top_priority')`
 2. name given in the spec
 3. name given by the caller, e.g., the entry name of the super cat
 4. name of the file/directory or something else derived from the path

But I could see 2 and 3 being flipped as well.

**Comment by martindurant** [comment]
Fair enough to add 1) to the top there.
