### ISSUE TITLE
Improve reprs for catalogs and catalog entries

### ISSUE THREAD

**Issue by ian-r-rose** [intake/intake#311]
Currently the reprs for catalogs and catalog entries are pretty spartan, which makes discovery and exploration more challenging. For instance, a typical entry repr looks something like
```
<Catalog Entry: some-url...>
```

Is there any interest in outputting more information here, at least in an IPython/Jupyter environment?

Catalogs could include:
* name
* length (at least for local catalogs)
* version

Entries could include
* markdown formatted description
* name
* intake driver
* target container

I see there is some effort towards a GUI for catalog exploration. I would view this as a lighter-weight, complementary feature.

**Comment by martindurant** [comment]
Good idea, in favour - although `describe()` exists for this purpose. Also, the source could be more more descriptive in a similar fashion. In fact, it occurs to me that the source should keep a record of the entry that made it, or at least the entry name (currently it remembers the catalog only, as attribute `.cat`).

**Comment by ian-r-rose** [comment]
Would you want to buff up `describe()` to have HTML/Markdown output, or leave that as plain text?

**Comment by martindurant** [comment]
Hm, I suppose it could return a dict-like object with a `_ipython_display_` method giving formatted output. There are also hooks for YAML output, so quite a few things going on here. I am happy to be swayed.
