### ISSUE TITLE
Using Dask dataframes in core

### ISSUE THREAD

**Issue by jbednar** [intake/intake#315]
How can I change whether Intake calls `df.persist()` for a Dask dataframe?  I work with some data that fits into memory, and other data that does not, so sometimes I want to use Dask out of core (no call to `.persist()`) and sometimes I want to use it in core (call `.persist()` before using it).  I can see how to use `.to_dask()` to get a Dask dataframe out of Intake, but I can't see any way to control whether Intake itself uses Dask's persisting.  E.g. for the following code:

```
import holoviews as hv, intake
from holoviews.operation.datashader import rasterize
hv.extension('matplotlib', logo=False)

catalog = intake.open_catalog('dashboard.yml')
source  = getattr(catalog, "nyc_taxi_50k")
rasterize(source.plot.dropoff())
```

Here I'm assuming that a Dask dataframe is in use internally, though I don't know how to ensure that or change that if I wanted to.  Assuming Dask is in use, how can I ensure that .persist is called on the dataframe before Intake builds the plot?  When I'm using interactive plots on a dataset that fits in memory, .persist is generally a major speed improvement,  so I want to be able to ensure it's called here (but not on datasets too large for my machine's memory).

**Comment by martindurant** [comment]
What holoviews does with the intake input is, I suppose, up to holoviews, and I don't actually know what options are available to you. 

If you wanted to be explicit, you could indeed do one of the following:
```
hvplot(source.read())   # pandas in-memory
hvplot(source.to_dask())  # dask ooc
hvplot(source.to_dask().persist())  # dask persisted
```

I agree that it *ought* to be possible to do this directly in `source.plot`.

**Comment by jbednar** [comment]
@jsignell and I just discussed all the levels involved here (Intake, Dask, hvPlot, HoloViews), and it took us a while to work out that hvplot.intake is the right level, not Intake itself and not HoloViews.  Intake is collecting the plot options from the catalog file, but it's just passing them on to hvplot's Intake support, and it's hvplot that's actually instantiating the dataframe, which is then given to HoloViews.

hvplot will create a Pandas dataframe unless the user provides`use_dask=True`, either explicitly or stored as an attribute in the Intake catalog.  And then the dataframe is, as suspected, not persisted.  @jsignell's made a PR for hvplot to properly respect a `persist` option on Intake objects, which it actually already does on xarray objects: https://github.com/pyviz/hvplot/pull/195

Once that PR is applied, we can put `persist=true` in the `plot` options on an Intake catalog and then Dask will be used by default and the object will be persisted by default, which is what we want. Thanks for the feedback!
