### ISSUE TITLE
nested catalogs and '.' characters in identifiers

### ISSUE THREAD

**Issue by rabernat** [intake/intake#316]
In Pangeo, we are now using highly nested catalogs. We have hit an issue (https://github.com/pangeo-data/pangeo-datastore/pull/16#issuecomment-479124582), that exposes my ignorance about how `__getitem__` works with nested catalogs.

Consider the following:
```python
import intake
url = 'https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/387e55f27c9a7c93975bdf6dfef58dcfb1077a2b/intake-catalogs/cmip6.yaml'
cat = intake.Catalog(url)
list(cat)
```

There are two entries (`['Omon', 'A3hr']`), which are themselves catalogs. 

`cat.walk()` gives
```
{'Omon.BCC-CSM2-MR.historical.r1i1p1f1.sos': <Catalog Entry: BCC-CSM2-MR.historical.r1i1p1f1.sos>,
 'Omon.BCC-CSM2-MR.historical.r1i1p1f1.tos': <Catalog Entry: BCC-CSM2-MR.historical.r1i1p1f1.tos>,
...
 'Omon': <Catalog Entry: Omon>,
 'A3hr.BCC-CSM2-MR.historical.r1i1p1f1.pr': <Catalog Entry: BCC-CSM2-MR.historical.r1i1p1f1.pr>,
 'A3hr.CNRM-CM6-1.historical.r1i1p1f2.huss': <Catalog Entry: CNRM-CM6-1.historical.r1i1p1f2.huss>,
...
 'A3hr': <Catalog Entry: A3hr>}
```

However, `cat['Omon.BCC-CSM2-MR.historical.r1i1p1f1.sos']  is None`.

Three things stand out:
- If there are no `.` characters in the dataset name, it works
- I would expect the keys returned by `walk` would be valid dataset identifiers 
- I would expect an error if I do not use a valid identifier, rather than returning `None`. For example, `cat['foo']` raises a `KeyError` but `cat['foo.bar']` returns `None`.

**Comment by rabernat** [comment]
@naomi-henderson points out that it might be the dashes, not the dots, that are screwing things up.

**Comment by rabernat** [comment]
p.s. intake version 0.4.3

**Comment by martindurant** [comment]
(note that I am at conference, so responses will be slower)

Simplest first: 

> cat['foo'] raises a KeyError but cat['foo.bar'] returns None

This should be fixed, not immediately sure why it would happen

OK, so what's going on here. When you select a dataset, Intake tries two things:
- Is there a data entry with exactly this name in the catalog?
- By splitting the name on ".", can we recursively get the pieces, assuming they all give catalogs, and end up with a data entry.

The problem with `'Omon.BCC-CSM2-MR.historical.r1i1p1f1.sos'` is that some of it is catalog hierarchy and some of it real name. What should probably happen is, that as we descend each level, we check is the remaining part of the given string is a known entry; or, rather, if *any leading part* of the string is a known entry:

- Is 'Omon.BCC-CSM2-MR.historical.r1i1p1f1.sos' an entry? No
- Is 'Omon' a catalog-type entry? 
  - If yes, open and recurse, keeping 'BCC-CSM2-MR.historical.r1i1p1f1.sos' for the next level
  - If no, Is 'Omon.BCC-CSM2-MR' a catalog-type entry...
