### ISSUE TITLE
Remote catalogs cannot be cast to list

### ISSUE THREAD

**Issue by jacobtomlinson** [intake/intake#324]
When using the `intake.catalog.local.YAMLFileCatalog` driver I'm having trouble listing what is in a nested dataset.

I've created two catalogs on GitHub Gists as an example for this issue. One with a [CSV dataset](https://gist.githubusercontent.com/jacobtomlinson/8146f044ced4e899b10c85e1c2ea9b1e/raw/9b5a4f6dbd6150158c336121534fef55f7263eb7/pupils.yaml) and [one which refers to it](https://gist.githubusercontent.com/jacobtomlinson/50027d61e718b5f9997f28acd054456e/raw/f2fc73d6194d22a88559a1f712786f07583575be/eu_pupils.yaml).

## Expected functionality

When opening the high level catalog I expect to be able to list the sources inside it, and then also list the sources inside the nested catalog.

```python
cat = intake.open_catalog('https://gist.githubusercontent.com/jacobtomlinson/50027d61e718b5f9997f28acd054456e/raw/f2fc73d6194d22a88559a1f712786f07583575be/eu_pupils.yaml')
list(cat)
# ['eu_pupils']
list(cat.eu_pupils)
# ['pupils']
```

## Actual functionality

```python
cat = intake.open_catalog('https://gist.githubusercontent.com/jacobtomlinson/50027d61e718b5f9997f28acd054456e/raw/f2fc73d6194d22a88559a1f712786f07583575be/eu_pupils.yaml')
list(cat)
# ['eu_pupils']
list(cat.eu_pupils)
```

```python-traceback
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-21-19b7dea46d81> in <module>()
----> 1 list(cat.eu_pupils)

/opt/conda/lib/python3.6/site-packages/intake/catalog/entry.py in __getitem__(self, item)
    145             else:
    146                 item = item[0]
--> 147         return self._get_default_source()[item]
    148 
    149     def __repr__(self):

/opt/conda/lib/python3.6/site-packages/intake/catalog/base.py in __getitem__(self, key)
    296                 out = self[part]
    297             return out
--> 298         raise KeyError(key)
    299 
    300     def discover(self):

KeyError: 0
```

## Additional notes

I see that I can do `list(cat.eu_pupils.get())` which gives me the result I'm after. However this isn't how I would expect to interact with this.

**Comment by martindurant** [comment]
Yep, this is something we know about. I suppose I'll implement `__iter__` for the case that the catalog entry also references a catalog. Note that you can already get the child labels with tab-completion. 
Will be in #323

**Comment by martindurant** [comment]
(btw, you could also have used the slightly simpler syntax of `list(cat.eu_pupils())`)

**Comment by martindurant** [comment]
This should now be fixed and released.
