### ISSUE TITLE
Performance issues with displaying catalog entries

### ISSUE THREAD

**Issue by ian-r-rose** [intake/intake#326]
I'm a bit puzzled as to what is going on here, but the repr for catalog entries is extremely slow.
If I have a catalog (in an IPython context), the following takes almost a second on my machine per entry:
```python
for entry_id, entry in catalog.items():
    display(entry)
```
The following is much faster:
```python
for entry_id, entry in catalog.items():
    display(entry.describe_open())
```

~~Some rooting around with cprofile suggests that the issue may be in `intake.catalog.utils._expand`, where there is the possibility for quadratic expansion of variables in templates. I'm not familiar enough with the codebase to know what might cause the paths to be so different for these two display variants, however~~.

Edit: seems like the problem may be with some unwanted interactions with IPython. It does a fair amount of attribute testing when deciding how to display a given object. The intake catalog entries overload `__getattr__`, and create new sources on the fly. This may turn what is meant to be a cheap attribute test into a much more expensive one with lots of jinja2 templating:

https://github.com/intake/intake/blob/b50ab5ca58e3c99eed159dc124db3862bf4ab03e/intake/catalog/entry.py#L128-L132

**Comment by martindurant** [comment]
I'm not sure what exactly `display` will call - would print or repr not be useful here? Your point I think is that the ipython standard visualisation ought to be the same as `.describe_open()`, which would be easy to implement; however, that would use the default values of any parameters.

-EDIT-

OK, it's because display is trying to call `_ipython_display_` on the entry, which does not exist, so Intake is instantiating the source to see if it has the attribute, before moving on. We could provide the hook. I have wondered previously whether it was right to seek underscored attributes in the default source...

**Comment by ian-r-rose** [comment]
@martindurant Thanks for the quick reply, just updated the comment above with some more info.

I don't think that `describe_open()` should *necessarily* do the same thing as the repr (though it may), I just was using that for illustrative purposes,

**Comment by martindurant** [comment]
The string form used in `intake.gui.source_view.Description.contents` may be an appropriate thing to use; in fact, since that is a Panel class, it could actually be **the** notebook representation of an entry, maybe ( cc @jsignell )

**Comment by ian-r-rose** [comment]
I also think that a `text/markdown` or `text/html` display would be appropriate (especially since the documentation states that descriptions are expected to be in markdown).

To this issue, I suppose either filtering out underscored items or providing a superseding set of display hooks could fix the situation. It seems kind of brittle, however.

**Comment by jsignell** [comment]
We definitely want a performant repr. The description from the GUI might be fine. I am not sure we want to have a panel object be the default representation of an entry since there are various installs required to get it set up properly. I think a nice text representation makes sense though.

**Comment by martindurant** [comment]
That makes sense, @jsignell - then we should move that method from the Description class to the entry, and have some of str/repr/_ipython_display_ call it (the latter producing a markdown version, if it isn't already). The Description panel can then just call it. @ian-r-rose , would you like to do this?

**Comment by ian-r-rose** [comment]
Sure, I can take a crack at this.

xref #311
