### ISSUE TITLE
Driver creation to support intake-server as well as standard intake

### ISSUE THREAD

**Issue by youngsaj** [intake/intake#332]
This may be more of a question, than any issue.
I created a intake driver for custom data.  I used fsspec, and it works fine for local, and even https data (using intake with a jupyter notebook).
However, when I try .discover() with an intake-server I get TypeError: can not serialize 'set' object (in the server console just after it successfully got the file paths in python list).

I'm wondering: Is this due to using fsspec in my driver, vs Dask? I'm also just using python for the container, does that have bearing on it?
The driver is loading and a print shows it's finding files for the urlpath (python list) just before the Exception.
There's several layers to remote data that I may not be understanding.  I was planning to just use the default direct_access and have the server proxy the data.
I see a listing for RemoteDataSource shows to_dask 
I have tornado 6.0.2, intake 0.4.2
A latest build of fsspec from main.

**Comment by martindurant** [comment]
It would be easier for me to help if I saw the code - is it public?

When the server sends details of a catalog entry, it serialises all the information using msgpack which, it appears, does not support sets (this surprises me). You could design your driver class to take a list or tuple in its place.

**Comment by youngsaj** [comment]
It's still prototype early stages and hasn't been pushed up yet.  That which you described may give me enough to go on.
I'm working on another class that needs to use intake.  Is there a way you prefer to get non public code (once I'm sure I can share).

**Comment by martindurant** [comment]
Obviously, in the open source world, the more open the better, and others may be able to help besides me :)

But you can email me and I can try to help when I have time ( mdurant at anaconda com )

**Comment by youngsaj** [comment]
It's definitely using sets in a specialized class that handles xml as a python object.  I suspect it's as simple as just getting the xml might work, sometimes easier said than done....

**Comment by youngsaj** [comment]
I found by using msgpack what it’ll accept.
I simply had to convert object to xml, and decode() once it comes back.

I'll close this out.
