### ISSUE TITLE
Catalogs as catalog entries and _load() performance

### ISSUE THREAD

**Issue by ian-r-rose** [intake/intake#333]
Over at [`intake-dcat`](https://github.com/CityOfLosAngeles/intake-dcat/tree/master/intake_dcat) I've got things set up so that DCAT catalogs are a data source themselves, as described in the intake docs. I was a bit surprised to see that every access of the catalog source calls the `_load()` function on it. In this case, that involves a network request for a few-megabyte file, so inspecting the catalog contents becomes pretty laggy.

1. Is this behavior intended? I might expect the catalog source to not need to re-initialize/reload itself unless explicitly forced to.
2. Is there a recommended way around this? I expect these catalogs to be slowly moving, so I can cache the entries after the first load, and then shortcut `_load()` thereafter. But perhaps there is a way that is considered more idiomatic for `intake`?

**Comment by martindurant** [comment]
The intent is that `cat.reload()` is called on access to one of the user-facing methods, and this calls `_load()` if more than `cat.ttl` seconds have elapsed. If you set `ttl` higher (in `Catalog.__init__`), reloads should be correspondingly less frequent.

**Comment by ian-r-rose** [comment]
Hmm, I am still seeing the same behavior, even if `ttl` is set to be very high. Let me try to come up with a minimal example.

**Comment by ian-r-rose** [comment]
Okay, in my example it is working as you describe. Which suggests to me that there is something invalidating the `ttl` somewhere in the more complex setup of `intake-dcat`.

```python
from intake.catalog import Catalog
from time import sleep
import yaml

class MyCatalog(Catalog):
    name = 'mycat'
    def _load(self):
        print('loading', end='...')
        sleep(2)
        print('loaded')

        self._entries = {}


inner = MyCatalog(ttl = 0, name='inner')
outer = Catalog.from_dict({'inner': inner})
outer.inner.items()
```

**Comment by martindurant** [comment]
`cat = intake_dcat.catalog.DCATCatalog("https://data.lacity.org/data.json", ttl=100)` seems to not reload every time for me.

**Comment by ian-r-rose** [comment]
Yep, figured out my mistake. Thanks for the help!

**Comment by ian-r-rose** [comment]
Whoops, never mind. The issue I am seeing is with nested catalogs, where they seem

**Comment by ian-r-rose** [comment]
I spoke too soon. Creating the catalog directly is behaving as expected. But when it is nested and deserialized from disk, I am still seeing problems...

I think it may have to do with the indirection between a catalog entry and the source, i.e. https://github.com/intake/intake/blob/a8512e53ac6bc899d80cffcf6a828eede2b74953/intake/catalog/entry.py#L89-L91

Here is a working example of the issue
```python
from intake.catalog import Catalog
from time import sleep
import yaml

class MyCatalog(Catalog):
    name = 'mycat'
    def _load(self):
        print('loading', end='...')
        sleep(2)
        print('loaded')

        self._entries = {}


inner = MyCatalog(ttl = 200, name='inner')
print(inner.yaml())
f = open('tmp.yml', 'w')
f.write(inner.yaml())
outer = intake.open_catalog('tmp.yml')
inner = outer.inner
```

With this setup, `inner.items()` always reloads the dataset. If, however, the catalog is reified from the entry using `inner = inner.get()`, then it behaves as expected.

I suppose this is expected behavior if you know what is going on behind the scenes. But to the user (and to myself), the blurring of the distinction between the catalog entry and the data source makes this behavior surprising.

**Comment by martindurant** [comment]
Note that the syntax could have been simpler, to instantiate the source: `inner = inner()`. What do you make of this solution to cache the "most recently" instantiated source for a given entry, in case it might be used again
```diff
index 6ff9e09..d14ab26 100644
--- a/intake/catalog/entry.py
+++ b/intake/catalog/entry.py
@@ -6,6 +6,7 @@
 #-----------------------------------------------------------------------------

 from copy import deepcopy
+import functools
 import time
 from ..utils import DictSerialiseMixin, pretty_describe

@@ -58,6 +59,7 @@ class CatalogEntry(DictSerialiseMixin):
         """
         raise NotImplementedError

+    @functools.lru_cache(1)
     def __call__(self, persist=None, **kwargs):
         """Instantiate DataSource with given user arguments
```

**Comment by ian-r-rose** [comment]
I think that would address my confusion. Are there times when we would want to explicitly clear the cache?

**Comment by martindurant** [comment]
Yes, source instances can hold onto resources after `discover()` has been called, but I don't think I'm prepared to worry about it at this point.
