### ISSUE TITLE
Remote Intake-server error with intake.gui

### ISSUE THREAD

**Issue by youngsaj** [intake/intake#340]
I’m having a problem using intake-server with intake.gui.   intake 0.5
(Using a custom driver).
I had started intake-server like
>intake-server remote_catalog.yml

I’m able to use:

myrcat = intake.open_catalog('intake://localhost:5000')
Then work with that readily using myrcat (read_partition worked fine).  
 

However, when I try to use the intake.gui (completely separate even from intake.open_catalog)

In the remote URL I put

Intake://localhost:5000

 

The remote server console print outputs what I would expect (same driver for both intake-server, and local use).
 
On the intake.gui side the browser output:
 

Python failed with the following traceback: 
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\panel\pane\base.py _update_pane L123
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\panel\pane\base.py _update_object L105
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\panel\pane\markup.py _update L58
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\panel\pane\image.py _get_properties L178
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\panel\pane\image.py _img L169
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\panel\pane\image.py _img L61
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\requests\api.py request L60
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\requests\sessions.py request L533
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\requests\sessions.py send L640
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\requests\sessions.py get_adapter L731
                InvalidSchema: No connection adapters were found for 'C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\intake\gui\icons\baseline-error-24px.svg'
VM1072:65 Python failed with the following traceback: 
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\panel\viewable.py _change_event L648
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\param\parameterized.py inner L1146
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\param\parameterized.py set_param L2488
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\param\parameterized.py set_param L1292
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\param\parameterized.py _batch_call_watchers L1407
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\intake\gui\catalog\select.py callback L87
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\intake\gui\catalog\select.py expand_nested L111
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\intake\gui\catalog\select.py get_children L97
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\intake\gui\catalog\select.py <listcomp> L97
C:\Apps\Anaconda3\envs\pyviz_dev\lib\site-packages\intake\catalog\entry.py __getattr__ L117
                AttributeError: 'RemoteSequenceSource' object has no attribute '_container'

**Comment by martindurant** [comment]
cc @jsignell - the GUI should be calling describe or the new text-repr, instead of accessing the attributes directly
