### ISSUE TITLE
Possibility for ibis container

### ISSUE THREAD

**Issue by ian-r-rose** [intake/intake#347]
Has there been any discussion of adding an [`ibis`](https://github.com/ibis-project/ibis) container for intake sources? This might be a nice option for deferred loading of large datasets with SQL-like backends.

**Comment by martindurant** [comment]
Certainly a fine idea, but no, it hasn't specifically come up in conversations with me before (although I did momentarily misread that as https://github.com/informatics-lab/intake-iris ). I'm not sure quite how you would express the dataframe-like syntax in a way that could be conveniently packed into a yaml spec.

**Comment by ian-r-rose** [comment]
I guess I was envisioning that you would get an ibis connection object, rather than an already-constructed expression, so the yaml specification would look much like the existing SQL drivers.

**Comment by martindurant** [comment]
Yes, that would be fine, and in-keeping with what other drivers do. Probably `.read()` would give you the pandas equivalent, and another method gives you the ibis object. However, the ability to prescribe the full expression is also interesting - this is currently done in intake-spark only.

Do you know if ibis outputs are chunkable for dask?

**Comment by ian-r-rose** [comment]
I don't think they are chunkable as-is, though once they are evaluated they are regular dataframes.

**Comment by martindurant** [comment]
Are you volunteering to make such a driver, @ian-r-rose ?

**Comment by ian-r-rose** [comment]
Possibly, but not on any immediate timescale :)

I'm also unsure about whether it should be considered a new driver or a new container type.

**Comment by martindurant** [comment]
It seems to me that this would be fine as a dataframe-type driver.

**Comment by ian-r-rose** [comment]
But if it immediately executes the expression, then you lose the benefit of the more lazy expression building, and might as well use `intake-sql`.

**Comment by martindurant** [comment]
>  if it immediately executes the expression

providing an alternate method to expose the expression object is fine, just like `.to_dask` produces lazy dask dataframes, but the type of data really is dataframe-like, and I would expect `.read()` to produce pandas.

**Comment by costrouc** [comment]
I am looking to implement this feature or some datasource that has ibis compatibility. We currently have intake catalogs with some dataframes taking up around 50GB of memory due to complex joins. Would like to be able to apply filters to limit the number of rows fetches (for example last 2 months of data instead of 5 years). Right now I am think that I will just implement this in an adhok way but would like to contribute it back once we have an idea of what this would look like

**Comment by martindurant** [comment]
Sure, looking forward to seeing it, @costrouc . Generally, the way to provide arguments to an Intake driver may have certain conventions, but really they are set by the necessities of the format/package doing the reading and the expectations of existing users.

**Comment by martindurant** [comment]
https://github.com/intake/intake-sql/pull/6

**Comment by martindurant** [comment]
Closing this, in preference to the PRs.
