### ISSUE TITLE
Change in v0.5.0 requires args to be msgpack-serializable.

### ISSUE THREAD

**Issue by danielballan** [intake/intake#353]
Commits 2d69d1a and 1b8913b, released in v0.5.0, had the possibly-unintentional effect of adding keys to `source.describe()`, and that now includes an Entry's `args`. When the server calls `source.describe()` here

https://github.com/intake/intake/blob/95177644620378de34618cb6b4c39d8ec3f1bf95/intake/cli/server/server.py#L208

and attempts to serialize it, it will fail if any of those args are not msgpack-serializable. In intake-bluesky, we pass into `args` various callables that close over a MongoDB client, which are of course not serializable. Should we avoid passing callables to `args`? Or can intake go back to being more narrow about what `describe()` returns and/or what the server attempts to serialize?

xref https://github.com/bluesky/intake-bluesky/issues/32

**Comment by martindurant** [comment]
Hm, that is a problem for you, I see. I'll have to think about it a little. Indeed, it must be possible to pass all the args at some point, so that opening a remote source directly (bypassing the server) can be possible, but maybe it can be deferred. Passing the arg values early does allow, though, for the user to override some at source instantiation time (POST) even when opening remote as opposed to direct.

**Comment by martindurant** [comment]
The obvious, but perhaps suboptimal, option would be to allow "cloudpickle" as an allowed serialiser. Of course, that comes with a possible security problem...

**Comment by martindurant** [comment]
Is it possible to refer to functions by a string `package.mod.func` rather than using concrete function objects? Allowing remote triggering of imports seems ok (we would do this to get a driver class anyway), preferable to unpickling arbitrary objects.

**Comment by danielballan** [comment]
My functions are closures over a `pymongo.MongoClient` instance, so they can't be recreated by importing. I think I could do something clever with strings nonetheless, like passing in a key in some global registry of `pymongo.MongoClient` instances.

**Comment by martindurant** [comment]
So I don't suppose they could be pickled either... I wonder if we should do something different in these cases where direct access is never possible.

**Comment by danielballan** [comment]
I was mulling something along those lines. I wouldn't want to ask intake to carve out an overly-specialized case, but maybe adding an option at server startup time would make sense. For my use case that would be sufficient. For potential other use cases where a server might serve a mix of directly-accessible and not-directly-accessible Entries, maybe there should be an way for specific Entries to opt in or out of that setting. Of course, if the Entries are _not_ being accessed locally with no server, that option would not be meaningful.

**Comment by danielballan** [comment]
Fixed by #354.
