### ISSUE TITLE
Add the ability to specify cache dir from within catalog

### ISSUE THREAD

**Issue by jsignell** [intake/intake#358]
I recently was working on a project where I want to have a directory structure like:

```
.
├── anaconda-project.yml
├── catalog.yml
├── data
│   └── data.parq
└── notebook.ipynb
```

I'd like the data dir to be populated when the sources defined in the intake catalog are cached. I don't think there is currently a way to specify the cache directory other than globally. Ideally there would be a:

 1. global cache dir
 2. local cache dir
 3. catalog cache dir
 4. user parameter for cache dir

with each overriding the last.

Relates to #355

**Comment by jsignell** [comment]
Note that for my particular example I realized I can specify the cache_dir as an env var in the anaconda_project. This gets me pretty close:

```.
├── anaconda-project.yml
├── catalog.yml
├── data
│   └── f890ce4d538240e87ede9d31a6541443
│       └── data.csv
└── notebook.ipynb
```

**Comment by martindurant** [comment]
Will this do for the time being, then? Caching is a general topic up for discussion right now.

btw: why not just reference the file directly rather than use the cache mechanism, if you're bundling it anyway?

**Comment by jsignell** [comment]
Yeah the env var is fine for the time being. We aren't bundling it. This is the file structure that the user will end up with. They will start with no data dir at all.

**Comment by martindurant** [comment]
OK, closing - but let's talk yet about the broader cache story.

**Comment by michaelaye** [comment]
+1 for caching, where is the discussion happening? I'd like to be able to tell the `read{)` command to cache things locally, so that I can continue to work while offline in a plane...

**Comment by martindurant** [comment]
@michaelaye : It is now possible to do this at the file system layer in fsspec: https://filesystem-spec.readthedocs.io/en/latest/features.html#caching-files-locally . In practice, this would mean having intake sources something like
```yaml
sources:
  mysource:
    driver: ..
    description:
    arguments:
      url: "filecache://bucket/path/glob*files" 
      storage_options:
        target_protocol: s3
        target_options: {anon: true}
```
I am thinking to entirely deprecate the cache functionality in Intake for this simpler implementation for my own personal sanity, and to make it available for people outside of Intake too.
