### ISSUE TITLE
Remote zipped CSV file on Dropbox

### ISSUE THREAD

**Issue by michaelaye** [intake/intake#366]
I'm trying to create an intake package, but am total intake beginner, so maybe I'm missing something.

For zipped files on Dropbox, to be able to read them directly into pandas I need to provide the compression indicator like so:

```python
pd.read_csv("https://www.dropbox.com/s/i4njyuua38g3imn/P4_catalog_v1.1_L1C_cut_0.5_fan.csv.zip?dl=1", compression='zip')
```
because of the `?dl=1` addition one needs to get the download directly; but then pandas auto-detection of the compression fails.
So, this works fine.

But when I put that into the `intake` source, using `csv_kwargs` I get a NotImplementedError and a warning:

```python
source = intake.open_csv("https://www.dropbo x.com/s/i4njyuua38g3imn/P4_catalog_v1.1_L1C_cut_0.5_fan.csv.zip?dl=1",
                         csv_kwargs={'compression':'zip'})
```
```bash
/srv/conda/envs/notebook/lib/python3.7/site-packages/dask/dataframe/io/csv.py:318: UserWarning: Warning zip compression does not support breaking apart files
Please ensure that each individual file can fit in memory and
use the keyword ``blocksize=None to remove this message``
Setting ``blocksize=None``
  "Setting ``blocksize=None``" % compression)

NotImplementedError: Compression format zip not installed
```
(This while running it in Binder.)

**Comment by michaelaye** [comment]
If the problem is created by using dask, can I avoid using dask for this remote file access?

**Comment by michaelaye** [comment]
Hm, this seems to work now, not sure what happened, sorry for the noise.

**Comment by martindurant** [comment]
Oh! I had just come to look into it, thanks for letting me know.

**Comment by michaelaye** [comment]
Well, sorry, there was one part that doesn't work, which is that zip isn't supported by dask, while pandas actually supports it. So I had to change to gzip to make things work. I guess there's no way to switch off the dask bridge to have directly pandas reading the file?

**Comment by martindurant** [comment]
We are considering this in another conversation. Of course, zip should be added to dask...
Intake does support zip as part of the caching mechanism, if downloading and extracting the file locally, so you have a local copy, is something that would be useful.
