### ISSUE TITLE
Extra kwargs passed to drivers

### ISSUE THREAD

**Issue by ian-r-rose** [intake/intake#399]
The filesystem work in #381 is causing some problems with `intake_geopandas`. So far as I can tell, it tries to add a `'storage_options'` kwarg to the open args, which is not recognized by the plugin. Requiring this kwarg seems a bit strict to me (though we could go ahead and ignore it downstream).

```text.python.traceback
/opt/conda/lib/python3.7/site-packages/intake/catalog/entry.py in __getattr__(self, attr)
    119             return self.__dict__[attr]
    120         else:
--> 121             return getattr(self._get_default_source(), attr)
    122 
    123     def __dir__(self):

/opt/conda/lib/python3.7/site-packages/intake/catalog/entry.py in _get_default_source(self)
     91         """Instantiate DataSource with default agruments"""
     92         if self._default_source is None:
---> 93             self._default_source = self()
     94         return self._default_source
     95 

/opt/conda/lib/python3.7/site-packages/intake/catalog/entry.py in __call__(self, persist, **kwargs)
     76             raise ValueError('Persist value (%s) not understood' % persist)
     77         persist = persist or self._pmode
---> 78         s = self.get(**kwargs)
     79         if s.has_been_persisted and persist is not 'never':
     80             s2 = s.get_persisted()

/opt/conda/lib/python3.7/site-packages/intake/catalog/local.py in get(self, **user_parameters)
    279         """Instantiate the DataSource for the given parameters"""
    280         plugin, open_args = self._create_open_args(user_parameters)
--> 281         data_source = plugin(**open_args)
    282         data_source.catalog_object = self._catalog
    283         data_source.name = self.name

TypeError: __init__() got an unexpected keyword argument 'storage_options'
```

**Comment by martindurant** [comment]
How about the following change:
```diff
--- a/intake/catalog/local.py
+++ b/intake/catalog/local.py
@@ -246,7 +246,8 @@ class LocalCatalogEntry(CatalogEntry):
                   'CATALOG_DIR': self._catalog_dir,
                   }
         params.update(self._open_args)
-        if 'storage_options' not in params and self._filesystem is not None:
+        if ('storage_options' not in params and self._filesystem is not None
+                and self._filesystem.storage_options):
             params['storage_options'] = self._filesystem.storage_options

```
so we only pass storage_options if there's anything to pass, i.e., never for local files. Of course, it *might* be nice to suppose remote files too.

**Comment by ian-r-rose** [comment]
I think the problem isn't that the file system is remote, but that the driver doesn't take general `kwargs`, and thus chokes on `'storage_options'`.

Though some of the file system inference worries me a bit with fiona/GDAL, especially stuff like this: https://github.com/intake/intake/blob/5da406ce149fc7487529403c805d93b752727839/intake/catalog/local.py#L527-L530
Since GDAL has a different virtual filesystem setup. I initially thought that this might be the problem, but I think in fact it's the above. I've updated the issue title.

**Comment by martindurant** [comment]
So, the purpose of this stuff is, that when a catalog is loaded via anything remote, chances are that the filesystem needed configuration, and then any dataset referred to by that catalog and relative paths (i.e., including `"{{CATALOG_DIR}}"`) would need to inherit the same filesystem. Perhaps there is a way to skip this if there are no relative file paths at all.

**Comment by ian-r-rose** [comment]
In this case I am reading data from s3, so yes, it's an absolute URL. Nevertheless -- should all drivers need to implement handling of `'storage_options'`?  I would think that the `args` should be more or less entirely owned by a specific driver.

**Comment by martindurant** [comment]
I feel that any driver that has args that could be relative URLs should accept storage_options, because a relative URL makes no sense without reference to the filesystem. How else could it be achieved?

**Comment by ian-r-rose** [comment]
Perhaps any driver accepting relative URL should take `storage_options` (though I might make the language [here](https://intake.readthedocs.io/en/latest/catalog.html?highlight=storage_options#remote-access) a bit stronger, since it would be more than a convention).

Doing too much inference on path construction in `intake` (rather than the driver) *does* make me pretty nervous, since different data sources can have very different URI semantics, the GDAL vfs being one of them,

**Comment by martindurant** [comment]
(note that the `get_dir` thing above is only called in the context of a YAML catalog file, so it is a case where a since source handles its own inputs)

**Comment by ian-r-rose** [comment]
> 
> 
> (note that the `get_dir` thing above is only called in the context of a YAML catalog file, so it is a case where a since source handles its own inputs)

Yes, you're right, and I don't think it's wrong in this case. I just wanted to express my concern about path-related logic, since I know from much painful experience how easy it is to miss hidden assumptions :)

**Comment by ian-r-rose** [comment]
Put another way, `intake_geopandas` defers to geopandas (via `**geopandas_kwargs`), which defers to fiona, which constructs a path for GDAL. I'm not sure what it would do with `storage_options`, other than catch it to avoid an error, then ignore it.
