### ISSUE TITLE
How can Intake GUI accept catalog URL as start-up argument

### ISSUE THREAD

**Issue by jeffdlb** [intake/intake#430]
More a question than an issue: Unless I'm missing something, it appears that intake.gui always starts with an empty "builtin" catalog, and to actually view a specific catalog you need to click '+' and add it manually. The documentation does say "New instances of the GUI are also available by instantiating intake.GUI, where you can specify a list of catalogs to initially include," but it is not clear (at least to me) from the documentation how to actually do that given a previously-defined catalog URL.

**Comment by martindurant** [comment]
Like this:
```
from intake.gui.gui import GUI
cat1 = intake.open_catalog(...)
cat2 = intake.open_catalog(...)
g = GUI([cat1, cat2])
```

**Comment by jeffdlb** [comment]
Thank you! That works, as long as I also use 
import panel as pn
pn.extension()

However, it still seems a bit of a dead-end: I can display the Catalog and the Sources, but intake.gui.sources remains empty [] even after clicking on a source.

**Comment by martindurant** [comment]
You need the attributes of the newly-created GUI object, like `g.cats`, `g.sources`, `g.item`

**Comment by jeffdlb** [comment]
Thanks -- I should have realized that myself!
