### ISSUE TITLE
persist ttl argument should check that it's an int.

### ISSUE THREAD

**Issue by jsignell** [intake/intake#438]
I just tried to use persist for the first time and passed a file name to the `ttl` argument (don't ask me why but I kind of thought `ttl` might be a terrible abbreviation of title). Passing a string to ttl did not through an error, but when I try to call `is_persisted` on the source, I am getting a comparison failure. 

As part of this, might be nice to add to the persist docstring.

**Comment by martindurant** [comment]
Yes please!

**Comment by martindurant** [comment]
(stands for "time to live")

**Comment by jsignell** [comment]
So should we just implement typing throughout intake? :)

**Comment by martindurant** [comment]
Rather you than me!
