### ISSUE TITLE
Implement __len__ on Catalog class?

### ISSUE THREAD

**Issue by rabernat** [intake/intake#456]
Catalog types almost meet the requirements for a [Collection](https://docs.python.org/3.8/library/collections.abc.html). They implement `__iter__` and `__contains__`. But not `__len__`. If we implement `__len__`, then a `Catalog`  will be a valid `Collection`. 

My specific application is for our nascent pangeo-datastore flask app, which traverses intake catalogs. I'd like to be able to do `{{ cat|length }}` from a jinja template. This requires being able to do `len(cat)` in python.

Should be easy to implement.

**Comment by martindurant** [comment]
Certainly worthwhile.
Can be implemented by iterating if necessary; note that it may be costly where paging from an external resource.

**Comment by rabernat** [comment]
Would it just look like this?

```python
class Catalog(Datasource):
    ...
    def __len__(self):
        return len(self._get_entries())
```

Is there a better way?

**Comment by martindurant** [comment]
It's a decent default implementation, although you only need the keys and not the details. I assume @danielballan would override this?

**Comment by danielballan** [comment]
Yes, that is what we do now. I support adding this default implementation.
