### ISSUE TITLE
Incompatible with pandas 1.0.0

### ISSUE THREAD

**Issue by danielballan** [intake/intake#460]
Pandas chose to [remove support for msgpack](https://pandas.pydata.org/pandas-docs/version/1.0.0/user_guide/io.html?highlight=to_msgpack#msgpack) in order to guide users toward Arrow instead. This breaks this codepath in intake

https://github.com/intake/intake/blob/33a096721765fc7fe79e958d3aa5f050a4c60937/intake/container/serializer.py#L56-L57

which now raises an `AttributeError` because `Data.Frame.to_msgpack` no longer exists.

I'm not immediately sure what the right fix is here, but maybe we should take up the suggestion in the TODO comment in this same function and transition to relying on `distributed`.

https://github.com/intake/intake/blob/33a096721765fc7fe79e958d3aa5f050a4c60937/intake/container/serializer.py#L48-L49

**Comment by danielballan** [comment]
More details about the change:

The msgpack reader and writer were deprecated in [v0.25.0](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.25.0.html) (released in July) and removed in v1.0.0 (released 7 days ago).

There is some relevant discussion in https://github.com/pandas-dev/pandas/issues/27722 where Jeff points people to https://github.com/pydata/pandas-msgpack but notes that it is broken and has no active maintainers (last commit was April 2017).

**Comment by danielballan** [comment]
I assume dask has a way to adjust for this, as they also make heavy use of msgpack for data serialization.

**Comment by martindurant** [comment]
@tomaugspurger , do you know what's the right thing to do here?

**Comment by TomAugspurger** [comment]
I guess stepping back a bit: why is msgpack serialization valuable? Can pickle be used instead?

> msgpack for data serialization.

I think msgpack is primarily (only?) used for serializing administrative data. Data like arrays, dataframes, etc. are serialized separatly.

**Comment by martindurant** [comment]
Well, using pickle everywhere would not be too bad, and reduce complexity too. Relying on dask might have been good, since it gets a lot more attention and deprecations are spotted and fixed earlier - except that this is distributed, which Intake does not currently rely on. 
Let's just use pickle for everything?

**Comment by TomAugspurger** [comment]
Was this being used to serialize data between the client and server? Is it safe to assume that the python & library versions match? If so, then pickle does seem simpler.

**Comment by martindurant** [comment]
Yes client and server. Should have a version check. For pickling of dataframes and arrays it can be fairly loose, right?

**Comment by TomAugspurger** [comment]
For pandas, the client being newer than the server would be OK (though sometimes slow). We maintain pickle compatibility for a while. The server being newer than the client may or may not work.

Not sure about numpy.

**Comment by danielballan** [comment]
> I guess stepping back a bit: why is msgpack serialization valuable? Can pickle be used instead?

It's a fair question. I think the dask scheduler--worker communication is a more "trusted" scenario where pickle is appropriate. Moving data between a scheduler and a worker is a short step from `multiprocessing` in terms of trust. I think users would be accepting a larger risk by un-pickling whatever an intake-server sends. I liked that aspect of relying on msgpack.

**Comment by danielballan** [comment]
P.S. Thanks for helping us sort this out, @TomAugspurger. :-)

**Comment by TomAugspurger** [comment]
The security angle is interesting.

How performance-sensitive is this codepath? It's possible that `DataFrame.to_json(orient='table')` and `pd.read_json(data, orient='table')` can be used, but that involves going through a text representation, and doesn't handle all cases (non-unique indices in particular, I think).

Arrow Flight may be a good option, but I don't know if Arrow is an acceptable dependency at this point.

**Comment by martindurant** [comment]
Requiring arrow for the specific case of dataframe transport from the server is OK, and so perhaps the best option, given a suitable exception upon import failure. Serialising via JSON would hurt performance too much I think.

**Comment by TomAugspurger** [comment]
@danielballan Does arrow as an optional dep for client / server stuff sound reasonable to you? I'd be happy to prototype something over the next few days to see how things work. I've been meaning to experiment with flight.

**Comment by martindurant** [comment]
I don't know about "flight", but
```python
context = pa.default_serialization_context()
out = context.serialize(df).to_buffer()
```

**Comment by danielballan** [comment]
Yes, it seems best to use the technology that pandas core devs support for serializing DataFrames. Alternatives seem likely to be slow or fail to round-trip special data types correctly or both. As long as we can make this work with Arrow as I'm optional dep, :+1: from me.
