### ISSUE TITLE
Path as pattern not working with CSVs on S3

### ISSUE THREAD

**Issue by jlstevens** [intake/intake#463]
Loading a CSVSource with the following catalog (note, `urlpath` is just an example):

```yml
sources:
  s3_csv:
    driver: csv
    description: "CSV data on S3; requires s3fs"
    args:
      urlpath: s3://bucket/directory/{date}/example.csv
```

With this code:

```python
import intake
cat = intake.open_catalog('catalog.yml')
s3data = cat.s3_csv()
s3data.discover()
```

Results in the following exception:

<details><pre>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-f98dba06d1a9> in <module>
      2 cat = intake.open_catalog('catalog.yml')
      3 s3data = cat.s3_csv()
----> 4 s3data.discover() #integration_dashboard

~/miniconda3/envs/analytics/lib/python3.7/site-packages/intake/source/base.py in discover(self)
    189     def discover(self):
    190         """Open resource and populate the source attributes."""
--> 191         self._load_metadata()
    192 
    193         return dict(datashape=self.datashape,

~/miniconda3/envs/analytics/lib/python3.7/site-packages/intake/source/base.py in _load_metadata(self)
    138         """load metadata only if needed"""
    139         if self._schema is None:
--> 140             self._schema = self._get_schema()
    141             self.datashape = self._schema.datashape
    142             self.dtype = self._schema.dtype

~/miniconda3/envs/analytics/lib/python3.7/site-packages/intake/source/csv.py in _get_schema(self)
    128 
    129         if self._dataframe is None:
--> 130             self._open_dataset(urlpath)
    131 
    132         dtypes = self._dataframe._meta.dtypes.to_dict()

~/miniconda3/envs/analytics/lib/python3.7/site-packages/intake/source/csv.py in _open_dataset(self, urlpath)
    119 
    120         # add the new columns to the dataframe
--> 121         self._set_pattern_columns(path_column)
    122 
    123         if drop_path_column:

~/miniconda3/envs/analytics/lib/python3.7/site-packages/intake/source/csv.py in _set_pattern_columns(self, path_column)
     76             col.cat.codes.map(dict(enumerate(values))).astype(
     77                 "category" if not _HAS_CDT else CategoricalDtype(set(values))
---> 78             ) for field, values in reverse_formats(self.pattern, paths).items()
     79         }
     80         self._dataframe = self._dataframe.assign(**column_by_field)

~/miniconda3/envs/analytics/lib/python3.7/site-packages/intake/source/utils.py in reverse_formats(format_string, resolved_strings)
    127     args = {field_name: [] for field_name in field_names}
    128     for resolved_string in resolved_strings:
--> 129         for field, value in reverse_format(format_string, resolved_string).items():
    130             args[field].append(value)
    131 

~/miniconda3/envs/analytics/lib/python3.7/site-packages/intake/source/utils.py in reverse_format(format_string, resolved_string)
    194 
    195     # get a list of the parts that matter
--> 196     bits = _get_parts_of_format_string(resolved_string, literal_texts, format_specs)
    197 
    198     for i, (field_name, format_spec) in enumerate(zip(field_names, format_specs)):

~/miniconda3/envs/analytics/lib/python3.7/site-packages/intake/source/utils.py in _get_parts_of_format_string(resolved_string, literal_texts, format_specs)
     42             if literal_text not in _text:
     43                 raise ValueError(("Resolved string must match pattern. "
---> 44                                   "'{}' not found.".format(literal_text)))
     45             bit, _text = _text.split(literal_text, 1)
     46             if bit:

ValueError: Resolved string must match pattern. 's3://team-edition-test-viz/test-results/' not found.
</pre></details>

It looks like `literal_text` in `source/utils.py` includes the protocol prefix (i.e `'s3://'`) which is not in the `_text` variable. Hacking in the following string replacement results in the expected behavior with a `date` column added to the dataframe:

```python
    for i, literal_text in enumerate(literal_texts):
        literal_text = literal_text.replace('s3://', '')
        if literal_text != '':
           ...
```

Tagging @jsignell as I believe Julia implemented this feature in #157.

Issue reproduced with intake version 0.4.1.

**Comment by jsignell** [comment]
Sorry for the slow response @jlstevens. I definitely implemented the feature, but it's got rough edges. I'd say that you should not include the path prefix in the thing that you want to use as a pattern. So this will probably work for instance:

```yaml
sources:
  s3_csv:
    driver: csv
    description: "CSV data on S3; requires s3fs"
    args:
      urlpath: s3://bucket/directory/*/example.csv
      path_as_pattern: bucket/directory/{date}/example.csv
```

As far as I can remember it was hard to figure out what the prefix is to a urlpath.
