### ISSUE TITLE
Document 'intake.catalogs' entrypoint and usage

### ISSUE THREAD

**Issue by danielballan** [intake/intake#464]
Per @talebzeghmi's [comment](https://github.com/intake/intake/pull/424#issuecomment-547160043)

> Some documentation on how to register a Catalog with an entry point would be helpful. This would allow us to register non YAMLFileCatalog to the global Intake catalog.

The short answer is:

```py
# setup.py
setup(
    ...
    entry_points=
        {'intake.catalogs': [
            'some_catalog_name = some.module:catalog_instance',
        ]},
)
```

but to document it properly we should reframe the narrative around it to be clear it can handle catalogs other than YAML files and also be clear that any Python package (not only a conda-packaged one) may be used.

**Comment by martindurant** [comment]
...and indeed that it makes distributing via conda easier too, no need to refer to special directories!
