### ISSUE TITLE
Better repr for user parameters

### ISSUE THREAD

**Issue by jsignell** [intake/intake#465]
Currently user parameters render like: 

```python
[<intake.catalog.local.UserParameter at 0x7f7072960d90>,
 <intake.catalog.local.UserParameter at 0x7f70723c7e80>]
```

It'd be nice if they were a dict, but if that is too hard, at least the repr for the object should contain the name.

**Comment by danielballan** [comment]
Related to https://github.com/intake/intake/pull/255 (which I did not immediately remember when @jsignell brought this up in person).
