### ISSUE TITLE
Consider slimming dependencies further

### ISSUE THREAD

**Issue by danielballan** [intake/intake#466]
## Why?

As a pluggable reader it seems plausible that intake core could have very few required dependencies. It is easier to convince people to adopt a library when it has few dependencies. We have received some push-back from potential adopters on this point, even though the situation is [much better than it was a year or so ago](https://github.com/intake/intake/issues/97).

We could just pip extras and multiple conda packages (akin to [dask-core-feedstock](https://github.com/conda-forge/dask-core-feedstock)) to support minimal installations and more full-featured "common drivers included" installations.

## Possible target

The current required dependencies are:

```
appdirs
entrypoints
dask[bag] >=1.0
jinja2
numpy
pyyaml
requests
msgpack
fsspec >=0.3.6
```

Many of these are used by certain built-in drivers or by the intake client. The subset that seems essential to make intake usable might be:

```
appdirs  # for configuration path management
entrypoints  # for driver and catalog discovery
fsspec >=0.3.6  # for the cache
pyyaml  # for parsing config files
```

The built in readers could be made to shadow their imports (e.g. "To use the CSV reader you must install...") or be packaged separately in entrypoints-ified intake packages. The intake client functionality is very useful (and essential for _my_ use case, it happens) but I think not generally required for many use cases.

**Comment by martindurant** [comment]
Good points...

jinja is required by the argument templating system, whether or not using UserParameters

(plus, at some point we should probably reopen pyyaml v rueml)

**Comment by SnarkBoojum** [comment]
Entrypoints is in maintenance mode with its homepage stating: "New code should use the [importlib.metadata module](https://docs.python.org/3/library/importlib.metadata.html) in the Python standard library to find and load entry points."

So perhaps it's possible to get rid of it?

**Comment by martindurant** [comment]
Intake Take2 (#737 ) uses importlib.metadata, and will be merged soon.
