### ISSUE TITLE
Proposal for a more succinct way to bootstrap a DataSource

### ISSUE THREAD

**Issue by danielballan** [intake/intake#468]
**This original post does not quite align with our current thinking. See the second and third comments.**

<hr />

@jsignell and I propose adding a new experimental minimal alternative to `DataSource`, which plugins may opt in to adopting at their own pace. It would requires some additions to the server (which @danielballan obviously volunteers to make) but otherwise should peacefully coexist with the rest of the codebase.

```py
class Reader:
    container = '...'

    def __init__(self, ...):
        """
        This signature is not specified.

        It may be a file, a database URI, or whatever makes sense for the data type.
        """
        # As in xarray, no structure is imposed on this dict.
        # It can have whatever internal structure or schema
        # is used by the corresponding standard or domain.
        # Its contents are exposed to the user but not used by intake.
        self.metadata = {...}
        # This may set additional internal variables for use below;
        # that's implementation-specific.

    def read(self, dask=None):
        """
        May return np.Array, pd.DataFrame, xr.DataArray, xr.Dataset or dask analogues.

        Generally the simplest structure that can represent the underlying data should be preferred.

        If None, the user is leaving it up to the Reader implementation whether to return
        a lazy (dask) or non-lazy (in-memory) object. Some Readers may hard code this choice;
        other Readers may make the choice dynamically based on data size or other considerations.
        The user can always take control by passing in True or False explicitly.
        """

   def  close(self):
        "Clean up any cached resources. At this point the Reader becomes unusable."

    def __enter__(self):
        return self

    def __exit__(self, *exc_details):
        self.close()
```

That is, the complete public API is `container` (a class variable used by client-server stuff), `__init__`, `metadata` (which may be a set in `__init__` or a cached property computed on demand), `read`, and `close`.

This resembles the anti-pattern mentioned in ["Stop Writing Classes"](https://www.youtube.com/watch?v=o9pEzgHorH0&t=194s), where the speaker advises against writing classes that only have `__init__` and one other method. The distinction here is, you can put arbitrary `metadata` _alongside_ a numpy or dask array, you can access that metadata before pulling enough information to build a dask array (or xarray backed by dask arrays) --- that is, before you know the shapes. In some cases, it may be cheap to get the shapes in advance, but not in all cases. Thus, we want a class that encapsulates metadata and a method for requesting data lazily or non-lazily.

Notably missing here is `read_partition`, which is currently central to the way the client--server interaction works. However, we can adopt the clever approach used in intake-xarray, where object on the server sends its counterpart on the client a kind of "header" that tells it the shapes, dtypes, and other metadata as appropriate for the client to set up a compatible shell of a data structure for which it can request chunks using some payload agreed upon between the client-side and server-side object. We can establish _patterns_ for this payload, but the server does not have to understand it or require a standard; it just passes info between these two objects. A typical payload might look much like what intake-xarray does now: a column name and a block index. (Of course, a backward-compatible codepath for classes existing that implement `read_partition` can be retained.)

We would like to leave consideration of functionality `persist` and `export` to a future round. Some form of local caching to disk seems useful on a Reader, but it pulls in enough additional complexity (state!) that we propose to get some basic examples written and working using this minimal API before we take that next step.

**Comment by danielballan** [comment]
Musing on this a little more, I noticed that the lifecycle of the proposed `Reader` API:

```py
reader = Reader(...)
reader.read()
reader.close()
```

rhymes nicely with opening files in Python:

```py
file = open(...)
file.read()
file.close()
```

"Using an intake Reader is just like opening a file in Python, but when you read it you get an (optionally lazy) SciPy/PyData data structure," is pleasantly easy to explain.

**Comment by danielballan** [comment]
I have built a prototype to show that if plugin authors provide a `Reader` API, we can automatically construct the rest of the `DataSource` API for them. https://github.com/danielballan/reader_prototype

**Comment by danielballan** [comment]
Expanded thoughts on how there is a place for an ecosystem-wide standard in this space without dependency on or even reference to any particular library.

https://blog.danallan.com/posts/2020-03-07-reader-protocol/

Intake has a role in that story, and it is well positioned to leverage such a standard to build nice features, but I don't think any library can be _core_ to the story if we want to get widespread traction. Every library that we might want to implement some readers (thinking of imageio, napari, PIMS, even pandas) has its own needs and design preferences. I don't think it's possible or desirable to sand over those differences, but we might be able to agree on some fundamental interface that the respective plugin systems can deal with.

**Comment by martindurant** [comment]
Intake Take 2 solves this, I think!
