### ISSUE TITLE
Adopt a convention where the 'intake.drivers' entrypoint name is a mimetype

### ISSUE THREAD

**Issue by danielballan** [intake/intake#470]
If we adopt a convention of registering DataSources using the mimetype that they handle, as in

```py
entry_points = {
    'intake.drivers':
        ['image/tiff = intake_tiff.TiffSource']}
```

then we can enable usages like

```py
# some function reads signature signature and/or extension
# (This exists in the standard library and in several third-party libraries.)
mimetype = sniff_mime_type(file)
intake.registry[mimetype](file).read()
```

where at no point do I have to know if `file` is `PNG` or `TIFF` or Nexus or something else. We could even wrap this in a convenience function, such as

```py
intake.open(file).read()
```

Some very generic readers (postgres) probably do not have an associated mimetype, but this convention should apply to most file-based formats that intake drivers read. Are there any downsides to adopting this convention?

**Comment by danielballan** [comment]
cc @saulshanabrook who may be interested in this

**Comment by martindurant** [comment]
This is somewhat complicated by a driver being able to potentially handle several mime-types. You would have an entry for each?
Also, currently driver names get converted into `intake.open_*` functions for convenience, so that would no longer work, as mime strings are never valid as python identifiers.

**Comment by danielballan** [comment]
Both good points. Yes, I think we would have an entry for each. I think there is no cost to putting the same object in multiple entrypoint entries.

I think the advantages of aligning our entrypoint names with standard MIME types are such that we might consider retiring (or stop extending) the dynamically-defined `intake.open_*` functions. We might lose `intake.open_tiff('image.tiff')` would we could gain `intake.open('image.tiff')` via the mechanism sketched above. Drivers would still be accessible (keyed by MIME type) in the `intake.registry` dict when they need to be explicitly invoked.

**Comment by danielballan** [comment]
I have reconsidered this statement.

> I think the advantages of aligning our entrypoint names with standard MIME types are such that we might consider retiring (or stop extending) the dynamically-defined intake.open_* functions. 

That's a little too dismissive of the convenience of the `open_*` functions, and it's too cavalier about breaking or abandoning a prominent feature of the API. I can think of a couple ways we can get MIME type-based dispatch (which I think would be really cool!) without getting in the way of `open_*`.

Here is the best one I have thought of so far, but there may be others we should consider:

We currently expect the entrypoint name to be a valid Python identifier, as in

```py
'tiff mime:image/tiff = package.module:Class'
```

We could extend this mini-specification to accept a valid Python identifier optionally followed by a MIME type, for drivers where MIME is applicable, as in:

```py
 'tiff mime:image/tiff = package.module:Class'
```

The entrypoint `name` is allowed to be any string, so we have a lot of latitude to structure it however we like. The driver discovery process could build a new, registry keyed on MIME types by looking for the matching structure in the entrypoint name. Then, the proposed inspection/dispatch mechanism could use that registry, as in

```py
def open(file):
    "Infer the type of the file and return a DataSource instance build on it."
    import mimetypes  # a standard lib module
    mimetypes.init()  # gets index of known MIME types from the OS
    _, mimetype = mimetypes.guess_type(file)
    return mimetype_registry[mimetype](file)
```

**Comment by danielballan** [comment]
This also gives a path for a different answer to

> This is somewhat complicated by a driver being able to potentially handle several mime-types. You would have an entry for each?

Instead of multiple entries, we might prefer allowing multiple `mime:` declarations in one entrypoint, as in

```py
'imageio mime:image/png mime:image/jpg mime:image/gif = package.module:Class'
```

**Comment by martindurant** [comment]
OK, I can see that working; and is remains compatible with previous usage, which just looks like no explicit MIME types being specified. Do you know if anyone else uses entrypoints in this manner? It doesn't seem like its really means for formatted string passing. We might accept commas as well as/instead of spaces as the delimiter.

**Comment by danielballan** [comment]
I don't know of anyone who uses entrypoints this way. Maybe @saulshanabrook or @takluyver would be generous enough to weigh in on whether the entrypoint construction

```py
'imageio mime:image/png mime:image/jpg mime:image/gif = package.module:Class'
```

feels "good clever" or "bad clever" to them? A viable alternative would be registering the same object repeatedly under different names, as proposed earlier:

```py
'imageio = package.module:Class',
'mime:image/png  = package.module:Class',
'mime:image/jpg = package.module:Class',
'mime:image/gif = package.module:Class',
```

**Comment by takluyver** [comment]
Gut feeling on a quick glance: bad clever. It feels like entrypoint names should be identifiers, not strings you parse meaning out of.

If you want to register both simple names and mimetypes, I might even go for two separate groups of entry points, something like:

```ini
[intake.drivers]
imageio = package.module:Class

[intake.mime_drivers]
image/png = package.module:Class
```

On the other hand, if you expect there to be multiple drivers for the same mimetype, some things might be simpler if mimetypes are treated as additional metadata rather than like names. It's totally possible to access multiple mimetypes with the same name, but it might be more fiddly e.g. to give a names to the set of possible drivers for a given mimetype.

**Comment by saulshanabrook** [comment]
I agree with @takluyver, I think overloading the definition even more seems a bit confusing. 

Yeah could the mimetypes be defined on the driver itself instead of in the entrypoints?

**Comment by martindurant** [comment]
> Yeah could the mimetypes be defined on the driver itself instead of in the entrypoints?

Yes, but we don't want to necessarily import the driver :)

**Comment by saulshanabrook** [comment]
> Yes, but we don't want to necessarily import the driver :)

Ah I see... You want to wait to import it until you actually encounter that mimetype because importing might be expensive?

**Comment by martindurant** [comment]
Exactly; or a mime type might be available from multiple packages, of which only some have the right dependencies and the others are not importable.

**Comment by saulshanabrook** [comment]
> of which only some have the right dependencies and the others are not importable.

So is the idea that if a user runs `intake.open("myfile.png").read()` it would then try to lookup the `img/png` mimetype and then import that driver? And that's when the user would get some error if there are them on imports?

**Comment by martindurant** [comment]
Yes, that is the workflow. This is already how things go, except that now you need to know the name of the driver for your data-set, "imageio" in the example.

**Comment by saulshanabrook** [comment]
I am curious what the use cases are in the real world for delaying import... Like do you have a concrete example today of how that helps the user?

If you don't wanna discuss this here, that's fine too, I know it's a bit of a diversion, just trying to get up to speed on assumptions underlying this discussion.

**Comment by martindurant** [comment]
We have a [lot of drivers](https://intake.readthedocs.io/en/latest/plugin-directory.html), and without lazy import, importing Intake itself is prohibitively slow.

**Comment by takluyver** [comment]
Presumably you'd combine that with some sort of priority system, so a specialised high-performance png driver could take priority over a more generic image library (as a hypothetical example)? At least, that's  easily the best of the simple options that come to mind (compared to picking a compatible driver at random or throwing an error if there's more than one compatible driver).

**Comment by saulshanabrook** [comment]
@takluyver So then would the priority be in the entrypoint as well then?

**Comment by takluyver** [comment]
I'd guess you'd identify the compatible drivers through entrypoints, which should be a small subset of the full list, then import all of those to compare their priority. That way, the priority mechanism can also handle if importing one of them fails, giving it lowest priority.

**Comment by danielballan** [comment]
Yes, actually I was thinking along those lines. For example, we might have one `'image/tiff'` driver that returns plain dask arrays and another than returns richer xarray.DataArray-of-dask-arrays objects with labeled dimensions. Exactly as you said, we could import all the compatible drivers and then look at attributes on them to choose the "highest priority" one, perhaps preferring the one with the richest container.

As long as the specification is reasonable, intake or external libraries for that matter can experiment with various discovery/priority schemes.

I definitely like the [proposal](https://github.com/intake/intake/issues/470#issuecomment-595316651) for a separate `'intake.mime_drivers'` better than my proposals above.

**Comment by martindurant** [comment]
Alright, sounds like we should split out the mime types. Still, we should support the simple names and provide open_* functions, and for those drivers that declare entrypoint mimetypes, a new general intake open function that will attempt to guess the type from the URL, and select the right driver. Obviously in that case, the user is not expected to know the optional parameters of the driver... but once they have a DataSource created, they can investigate and refine later, if desired.

**Comment by danielballan** [comment]
Great, sounds like a plan.

I can foresee this interacting with the discussion about enabling plugins to implement a smaller interface from which we automatically construct a full DataSource subclass. (That is, do we want `'mime_readers'` instead of or in addition to `'mime_drivers'`?) Unless there is an urgent need for this to be implemented (not from my side) I suggest we sit on this design until the discussion in #468 is further along.

**Comment by martindurant** [comment]
OK, but it did occur to me just now, that for some storage backends (HTTP, s3, gcs), there may be an explicit MIME type associated with a location, so we are not limited to looking at the filename alone.

**Comment by takluyver** [comment]
Desktop Linux also has a convention for using non-standard mimetypes to represent URL protocols, like `x-scheme-handler/http` for `http://` - just in case you're looking for a way to represent URL types in the same way.

(This is used when associating a default application with a URL scheme)

**Comment by martindurant** [comment]
That's a whole different discussion :)
`fsspec` already dispatches on the "protocol" part of URLs, but I definitely had not considered using that same part of the URL as a format specifier.

**Comment by danielballan** [comment]
> We are not limited to looking at the filename alone.

Definitely. We also might want to incorporate file signature sniffing. In fact there is a [standard library module that does this](https://docs.python.org/3/library/imghdr.html) that does this for images but it's pretty limited and is [among those that may be removed in the future](https://www.python.org/dev/peps/pep-0594/#imghdr). External alternatives include puremagic, filetype, python-magic.

As soon the entrypoint declarations are added, we can experiment with this kind of thing externally without committing to changing intake itself.

**Comment by danielballan** [comment]
@takluyver Can you help me understand the story around `entry_points` in `pyproject.toml`? Judging from and https://flit.readthedocs.io/en/latest/pyproject_toml.html#entry-points-sectionshttps://python-poetry.org/docs/pyproject/#plugins it looks like this has to be addressed for the specific tool or tools that may be used to install the package. Do you know if there are any plans to promote `entry_points` to a first-class entity in `pyproject.toml` itself? Does that even make sense?

**Comment by takluyver** [comment]
It's addressed to the tool used to *build* the package. When you install
something with pip and there isn't a wheel ready for it to use, it invokes
a backend to build a wheel (see pep 517 for the gory details), and then
installs from that. Wheels contain entry points in a standard format (.txt
file) which pip knows about.

The choice of build tool is up to the package maintainers, but users
installing the package shouldn't need to know about it.

**Comment by martindurant** [comment]
datatype classes in Intake Take2 support search by MIME
