### ISSUE TITLE
Unify catalog read

### ISSUE THREAD

**Issue by jsignell** [intake/intake#471]
At the moment there is a `intake.Catalog` alias for `intake.open_catalog` and there is also `intake.load_catalog`. It'd be nice to at least consolidate around one approach in the docs. Additionally, it'd be nice to get rid of the top level `Catalog` since it is confusing that it is not a class.

**Comment by danielballan** [comment]
:+1:

`intake.Catalog` being alias for `intake.open_catalog` and not `intake.local.Catalog` has tripped me and some of my colleagues up. Removing it is likely to break some examples; one way to mitigate the upgrade pain is to use a module property to provide a helpful error:

```
# intake/__init__.py

# If supported, use a module property to tell the user we have removed intake.Catalog.
if sys.version_info >= (3, 7):
    def __getattr__(name):
        if name == 'Catalog':
            raise AttributeError("The alias intake.Catalog was removed. (Helpful suggestions...)")
```
