### ISSUE TITLE
Monthly dev meeting

### ISSUE THREAD

**Issue by jsignell** [intake/intake#472]
I mentioned this idea on gitter, but the idea arose at the dask dev meeting that it would be a generally useful thing to have a monthly dev meeting where we can discuss maintenance, road-map and so on. 

Perhaps 10:30am eastern on the first Thursday of the month (that would put it right before the dask monthly meeting, so maybe it'd be easier to remember?).

@danielballan @martindurant

**Comment by martindurant** [comment]
That time works OK for me.

**Comment by jhamman** [comment]
I assume @andersy005 will want to join. 10:30a ET is too early for me (Pacific timezone).

**Comment by jsignell** [comment]
@jhamman would you also want to join? I am not attached to the time.

**Comment by andersy005** [comment]
First Thursday works for me as well. @jhamman, thank you for bringing this to my attention.

**Comment by jhamman** [comment]
I don't think it is worth scheduling around me. If it were >=8a PT, I would join semi-regularly.

**Comment by jsignell** [comment]
In that vein, I added an @intake-dev team. We should add people to that team and ping it when we are making design choices

**Comment by martindurant** [comment]
Including collaborators as listed by github:
@hdsingh @talebzeghmi @mmccarty @rsignell-usgs @seibert 
@ian-r-rose @jacobtomlinson @jcrist @rabernat @tam203 @TomAugspurger

**Comment by danielballan** [comment]
Also of interest to @tacaswell @gwbischof

**Comment by martindurant** [comment]
It being Friday evening, we may not hear back many opinions soon, so I will presume Julia's suggested time until we maybe agree on something better.

**Comment by tacaswell** [comment]
I'm on board with joining this call semi-regularly (but likely mostly to listen).

**Comment by martindurant** [comment]
@jsignell , do you want to make a public meeting notice for this week?

**Comment by jsignell** [comment]
Not sure if you have something different in mind, but here is a link to a google calendar invite: https://calendar.google.com/event?action=TEMPLATE&tmeid=N2dqczlua3U1ZjVsZThqcWsycjlscmJuMzkganNpZ25lbGxAbQ&tmsrc=jsignell%40gmail.com

**Comment by danielballan** [comment]
I get "Could not find the requested event" from that link. Maybe the calendar isn't public.

**Comment by jsignell** [comment]
Maybe we should make it from the intake gmail account. I think @martindurant probably has access.

**Comment by jsignell** [comment]
Ok try this one: https://calendar.google.com/event?action=TEMPLATE&tmeid=NDE4bWc3NHZxODdtOG04YmI4N2h0ZXFiZ3RfMjAyMDAzMDVUMTUzMDAwWiBpbnRha2UuZGV2QG0&tmsrc=intake.dev%40gmail.com&scp=ALL

**Comment by danielballan** [comment]
Success.

**Comment by danielballan** [comment]
(Thanks!)

**Comment by mmccarty** [comment]
Thanks for organizing. Definitely interested in attending!

**Comment by martindurant** [comment]
For future reference, where can we put that invitation, or updated version of it, to get wider participation? Although this is a "dev meeting", I would not be against anyone attending that thinks they have something to contribute.

**Comment by jsignell** [comment]
I think we can do like dask and add the google calendar to a community page https://docs.dask.org/en/latest/support.html

**Comment by jsignell** [comment]
@martindurant how do the docs get built, is it only on release?

**Comment by kaedonkers** [comment]
Late to the party, but a couple of us from the UK Met Office will be at the next one 👍 
Thanks for organising @jsignell!

**Comment by martindurant** [comment]
ping all - this is coming up in five minutes (according to my calendar)

**Comment by pgierz** [comment]
Hello,

is the meeting also open to users and other "interested people"? I'm starting to set up some intake-based infrastructure in our research group and would love to hang out and listen, and maybe ask some questions.

Thanks!
Paul

**Comment by martindurant** [comment]
@pgierz , the meeting is open to anyone that wants to come. You are also welcome to ask on gitter and issues (I see #485 )

**Comment by martindurant** [comment]
Any suggestions for an alternate time? I am thinking that people in other time-zones (e.g., @talebzeghmi ) may have preferences.

**Comment by tacaswell** [comment]
Can we schedule more than 30 minutes?  The last few meetings have felt like we got through introductions and all getting on the same page about the topic we were going to talk about just in time for the meeting to end.

**Comment by martindurant** [comment]
I am happy to have longer, but the dask community meeting is immediately after, so if we keep the same time, we would have to start earlier.

**Comment by jsignell** [comment]
I'm fine with longer and earlier or longer and different date :)

**Comment by martindurant** [comment]
@jsignell , could you tentatively edit the invite to start half an hour earlier?

**Comment by jsignell** [comment]
Sure sounds good. I fixed the docs link while I was at it: https://github.com/intake/intake/pull/495

**Comment by jsignell** [comment]
@intake/dev community meeting at 9am central today (in 15 minutes) at https://anaconda.zoom.us/j/5408205637

**Comment by martindurant** [comment]
Because of various national holidays this week, the meeting will be *postponed* to Thursday, 9 July. Same time, same place.

**Comment by martindurant** [comment]
Unfortunately, out baby is having inoculations tomorrow morning, and I’ll be needed to provide transport. It is pretty unlikely I’ll make it back in time for the meeting. Should we a) have the meeting anyway (I can provide the zoom room) or b) postpone?

**Comment by martindurant** [comment]
The following will be open from 1000, eastern https://anaconda.zoom.us/j/96451024940 . I should make it before 1100, with luck.

**Comment by martindurant** [comment]
Monthly Intake meeting tomorrow morning. This room will be available from 10, eastern:
Join Zoom Meeting
https://anaconda.zoom.us/j/96464359692?pwd=NzcxaTl3Q2szZHp6YlJjaXM3aGZOdz09
Meeting ID: 964 6435 9692
Passcode: 782627

**Comment by martindurant** [comment]
monthly reminder!

**Comment by danielballan** [comment]
New link. I made this recurring through June, so it should continue to operate for future monthly meetings. https://bnl.zoomgov.com/j/1618146019?pwd=QlBvZTUzc3kzeE56TUZwRkF3Q21IQT09

**Comment by martindurant** [comment]
Dear thread,

at the last meeting, we discussed the places where this meeting was mentioned, and which would be authoritative. It would be best to define in exactly one place, to be easier to update.
- this issue
- calendar invite or zoom invite
- https://intake.readthedocs.io/en/latest/community.html (which mentions notes, which we have not been posting)
- in addition, it's nice to put a reminder on the gitter channel

Lets hammer this down now, with time before the start of the next month!

**Comment by martindurant** [comment]
Closing for https://github.com/intake/intake/issues/596
