### ISSUE TITLE
Add example for creation of plots

### ISSUE THREAD

**Issue by thisiswhereitype** [intake/intake#480]
In the examples [here](https://intake.readthedocs.io/en/latest/plotting.html#declaring-custom-plots) and [here](https://github.com/intake/intake-examples/blob/master/tutorial/data_engineer.ipynb) there is no source code showing how to add plots.

How to add them so I can see my plots in the output of `source.yaml()`?

Thanks

**Comment by martindurant** [comment]
There is no current method to get a set of parameters *out* of an existing plot for storage, so assuming your are iteratively making plots from the data, you would need to inspect the parameters you are passing and write them out yourself - unfortunately.

You *could* use tools like [`dfviz`](https://github.com/intake/dfviz) and [`xrviz`](https://github.com/intake/xrviz) to interactively find the right plot and generate YAML blocks. For example, with `dfviz`:
```
import dfviz
dfv = dfziv.run_example()
# dfv = dfviz.DFViz(my_dataframe) for your data
# interact
mw.control.kwargs  # arguments as a dict
```
The interface also has a YAML panel with the currently plotter arguments shown in the right format.

#398 will include these viz tools in Intake itself, together with documentation to make the above process clearer.

**Comment by martindurant** [comment]
You are quite right on the general point though, the docs could probably do with more details and more structure to be able to find that detail... All help would be appreciated!

**Comment by thisiswhereitype** [comment]
Thanks for the speedy and comprehensive response.
