### ISSUE TITLE
Make catalogs lazy by default

### ISSUE THREAD

**Issue by martindurant** [intake/intake#506]
Currently, the Catalog base does the following on instantiation:
```
        self._entries = self._make_entries_container()  # gives {} by default
        self.force_reload()
```
so that `_load()` is called at that time (and whenever the TTL runs out, which is on by default!). Now, we *can* construct special lazy versions of `_entries`, but it would be nice if the default were to only do any loading when entries are actually accessed in any way.

Related to #505 (where there is no loading of entries in zarrcat's init, only _load, which is the recommended thing to do).

**Comment by martindurant** [comment]
@tacaswell , sounds like your kind of thing...

**Comment by danielballan** [comment]
I have had that this thought on my "back burner" for awhile: what if the special lazy Entries class that we use was the default? I think the NSLS-II contingent can push on this.

**Comment by martindurant** [comment]
Yes definitely - albeit, a lazy entry class that loads from files for the typical case. Snipping the current implementation to defer that first load until first access would be easier, a smaller change, though.

**Comment by danielballan** [comment]
Definitely agreed. I have found that the call to `_load` in `__init__` makes it difficult to override certain things early enough so that they are available for `_load`. This would help with that too.

**Comment by martindurant** [comment]
So.. just let me know if you think you can get people to work on this (either the simple fix or the more complete one). I have been mored in async file-ops...

**Comment by danielballan** [comment]
We will work on the simple fix.
