### ISSUE TITLE
Performance in loading nested catalogs

### ISSUE THREAD

**Issue by ian-r-rose** [intake/intake#512]
I'm seeing some performance regressions in the most recent release of intake (0.6.0), possibly related to #490.

A while back in #333, we had discussed how to avoid fetching catalog data (e.g., with a network request) too many times in the context of a nested catalog. #335 provided a fix, but that no longer seems to work. At present, dotting into nested catalogs seems to recreate the inner catalogs anew every time. I have some contexts where setting up a new catalog is somewhat expensive (tens of seconds), which makes this constant recreation very painful.

A minimal example of this is (adapted from #333):
```python
from time import sleep

import intake
import yaml

# Create a catalog that is slow to initialize
class MyCatalog(intake.catalog.Catalog):
    name = 'mycat'
    def _load(self):
        print('loading', end='...')
        sleep(2)
        print('loaded')

        self._entries = {}

# Write a nested catalog with a mycat entry
inner = MyCatalog(ttl = 200, name='inner')
with open('tmp.yml', 'w') as f:
    f.write(inner.yaml())

# Load the nested catalog, and dot-access the inner catalog several times
outer = intake.open_catalog('tmp.yml')
print("How many times is it loaded?")
for i in range(10):  
    inner = outer.inner
    inner = outer.inner
```

This is probably also related to #410 . If there are some best-practices around this that have recently changed in light of #490, I'd be interested in hearing them as well.

**Comment by martindurant** [comment]
The solution to this should probably be #506 - @danielballan have you had a chance to get going on that?

**Comment by ian-r-rose** [comment]
Making inner catalogs fetch entries lazily does sound worthwhile -- would it necessarily solve this issue though? In my case, I'm trying to avoid recreating the catalog and re-fetching its entries if it has already been created once.

**Comment by martindurant** [comment]
Oh I see. 

There seems to be a couple of things here.

Firstly, the outer catalog is being reloaded every time, it has the default ttl of 1s, should be
```python
outer = intake.open_catalog('tmp.yml', ttl=200)
```
(ttl does not propagate to child catalogs...)

Second, the caching of the default instance is indeed broken, since we no longer call _get_default_source, just `.get()` with no params. The following could fix
```diff
--- a/intake/catalog/local.py
+++ b/intake/catalog/local.py
@@ -277,12 +277,17 @@ class LocalCatalogEntry(CatalogEntry):

     def get(self, **user_parameters):
         """Instantiate the DataSource for the given parameters"""
+        if not user_parameters and self._default_source is not None:
+            return self._default_source
+
         plugin, open_args = self._create_open_args(user_parameters)
         data_source = plugin(**open_args)
         data_source.catalog_object = self._catalog
         data_source.name = self.name
         data_source.description = self._description
         data_source.cat = self._catalog
+        if not user_parameters:
+            self._default_source = data_source

         return data_source
```
(but what about remote entries?)

**In addition**, those entries should be lazy and not instantiated if not selected.

Note that I have found the interesting fact that bool(entry) is always True, but bool(source) is always False. Weird!

**Comment by martindurant** [comment]
About this line: `outer = intake.open_catalog('tmp.yml', ttl=200)`, it would also be reasonable to check the text of the catalog for changes or ask the filesystem to see if there was an update, to avoid re-instantiating the entries every time. I do think that the default TTL should be bigger than 1s.

**Comment by ian-r-rose** [comment]
> Firstly, the outer catalog is being reloaded every time, it has the default ttl of 1s, should be

👍 Good catch. In my non-toy use-case I have longer ttls at all levels though, so my main focus is in the caching behavior.

> Second, the caching of the default instance is indeed broken, since we no longer call _get_default_source, just `.get()` with no params. The following could fix
> 
> ```diff
> --- a/intake/catalog/local.py
> +++ b/intake/catalog/local.py
> @@ -277,12 +277,17 @@ class LocalCatalogEntry(CatalogEntry):
> 
>      def get(self, **user_parameters):
>          """Instantiate the DataSource for the given parameters"""
> +        if not user_parameters and self._default_source is not None:
> +            return self._default_source
> +
>          plugin, open_args = self._create_open_args(user_parameters)
>          data_source = plugin(**open_args)
>          data_source.catalog_object = self._catalog
>          data_source.name = self.name
>          data_source.description = self._description
>          data_source.cat = self._catalog
> +        if not user_parameters:
> +            self._default_source = data_source
> 
>          return data_source
> ```
Makes sense, would you be interested in a PR to that effect?
I didn't follow all the ins and outs of #490, is anybody using `_get_default_source` anymore? Can it be removed?

> (but what about remote entries?)

I'm not sure I understand.

> **In addition**, those entries should be lazy and not instantiated if not selected.

Agreed.

> Note that I have found the interesting fact that bool(entry) is always True, but bool(source) is always False. Weird!

Weird indeed! Evidently there are some corners of falsiness that I am unaware of.

**Comment by martindurant** [comment]
> would you be interested in a PR to that effect

Yes; if tests pass, this should be good enough, but I haven't looked rigorously to see if there might be unfortunate repercussions.

> is anybody using _get_default_source anymore

It is referenced in a couple of places in CatalogEntry that I suspect are never used now that raw entry instances are not passed around, so should be fixed and tested. Also appears in a couple of tests.

> (but what about remote entries?)

I mean that my diff is in the LocalCatalogEntry class and something similar should maybe implemented for RemoteCatalogEntry and maybe EntrypointEntry. This could happen in the base class, and each calls super before the specific code.

**Comment by ian-r-rose** [comment]
Hmm, the proposed caching is failing some tests having to do with templating environment variables. If the data source picks up those environment variables upon creation, and the relevant environment variables change, then the cached source might not be the same as a newly-created one.

I could also cache the `open_args` in the same way to also check if the environment context is the same as when the cached source was created. That would involve a deep equality check, it seems. Thoughts?

**Comment by martindurant** [comment]
You mean that they are getting the same source, because "default" values are being interpreted differently for a changed env? That takes a dose of thinking about ... This thing should at least work for the majority case where there are no template parameters.

**Comment by ian-r-rose** [comment]
I suppose if a source depends on possibly-changing environment variables, then who is to say which version of the source should be considered "default"?

How about this: we only try to cache a default source if `getenv` is `False`. That would mostly sidestep the issue, but I think it would be fair to say that a source which depends implicitly on its execution environment might not have a proper default.

**Comment by martindurant** [comment]
Perhaps this is the kind of thing that can be discussed at tomorrow's dev meeting
