### ISSUE TITLE
intake_server and http headers with underscore

### ISSUE THREAD

**Issue by dylanmcreynolds** [intake/intake#515]
I'm trying to setup intake server instance behind a load balancing firewall (Kubernetes Ingress). Found a very strange issue.

```
In [1]: from intake import RemoteCatalog                                                                                                                                             

In [2]: c = RemoteCatalog('intake://<hostname....>')                                                                                            

In [3]: list(c)                                                                                                                                                                      
Out[3]: ['root']

In [4]: list(c['root'])                                                                                                                                                               
Out[4]: ['root']

In [5]: list(c['root']['root'])                                                                                                                                                        
Out[5]: ['root']
```

After some sniffing of http headers, I found that a request was missing the 'source_id' header which I assume should have told the server what catalog to interrogate. Without it, the server always replies with the root catalog specified in the intake-server's yml file ('root' in the case above.)

This has to do with underscores in headers, which nginx does not pass by default. I tested and a header with 'source-id' would be passed fine. Sniffing around the web, this seems to be some old cgi related issue. I'm working and on a solution in my installation (I do not have access to the the obvious configuration in nginx that would fix this). It might be nice to consider changing the few custom headers that intake client and server pass around so that underscore is not being used.

**Comment by bjoernenders** [comment]
FYI this is solved with
```
nginx.ingress.kubernetes.io/server-snippet: |
  underscores_in_headers on;
```
But this took a very long time to research. Better would be if intake were not using underscores *at all* in their headers. Why not use dashes instead and make every server happy?

**Comment by martindurant** [comment]
Agreed, this can be a simple fix on our end

On July 14, 2020 8:43:40 PM EDT, Bjoern Enders <notifications@github.com> wrote:
>FYI this is solved with
>```
>nginx.ingress.kubernetes.io/server-snippet: |
>  underscores_in_headers on;
>```
>But this took a very long time to research. Better would be if intake
>were not using underscores *at all* in their headers. Why not use
>dashes instead and make every server happy?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/intake/intake/issues/515#issuecomment-658481861

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by martindurant** [comment]
(you may well want to submit the PR if you have the time, you're likely to get to it before me)

**Comment by dylanmcreynolds** [comment]
I was thinking about that. I'll take a stab at it. I was thinking it would probably take less time than it took to track down the issue. :)

**Comment by martindurant** [comment]
find-replace on the header keys should do it :)
So long as client and server are updated together, all is good. The server could check for both old and new keys.

**Comment by bjoernenders** [comment]
The PR should probably also update the docs with it

**Comment by bjoernenders** [comment]
Also looking at the docs it says that "parameters are message packed" which isn't true, as `the source_id` parameter can be part of the header. Is this communication pattern following a certain design philosophy? Should other parameters be exposed in the header?

**Comment by martindurant** [comment]
"parameter" in this case means additional arguments, which is not too clear (i.e., this is what they are called in DataSource). Certainly feels like clarifying the API in general would be welcome.
