### ISSUE TITLE
Anyone know if there is a way to offer intake goodness to R folks?

### ISSUE THREAD

**Issue by cwerner** [intake/intake#527]
Hi.

We might move to intake as our data access layer in our organization soon. However, we have quite a few R people and it would help the adoption a lot if there is the equivalent to intake as an R package. Is this feasible in any way? Does this exist?

Cheers,
C

**Comment by martindurant** [comment]
There is *not* an implementation for R, although there may well be another package out there which does a similar thing in the R world - I would probably not have heard of that.

The standard way to write intake catalogs is to specify arguments, which get passed to python functions like read_csv, so the definition is tied to the third-party API. However, it is totally possible to write catalogs in a language-agnostic way, so long as the driver knows what to do with the listed arguments. An example of this is [intake-stac](https://intake-stac.readthedocs.io/en/latest/), which uses a scientific standard for dataset specification, and translates each entry into the specific call that needs to be made in python. If this translation layer were made in R, the same catalog could be used from both languages.

Another interesting example is [intake-spark](https://intake-spark.readthedocs.io/en/latest/quickstart.html#usage) which uses an external (non-python) definition of how to create datasets. This would presumably be very similar for spark-R, but I'm not sure if it could be generalised beyond spark.

Finally, the intake server protocol, over HTTP, is really simple. You could talk to this from R with a minimal amount of code. Again, there would need to be work interpret those source definitions and/or decode the raw streaming data (which are msgpack-encoded python containers like numpy, pandas, but could be something more standard, perhaps using arrow).

**Comment by cwerner** [comment]
Great!

Thanks for the insight!

**Comment by martindurant** [comment]
Please ping back here if you have further thoughts or attempt to make any progress towards intake-R. I would be happy to see, for instance, conventions on argument naming that would make use from R easier (e.g., the arguments in read_csv are probably approximately the same in pandas- and R-dataframe)

**Comment by cwerner** [comment]
Will do - I'm thoroughly living in python land myself so that's not something I'd create, but wanted to check the options for our R users.  

My guess is we will move ahead since the majority of people use python anyways and wait/ see if we or someone comes up with an interface. Will talk to our R guys what they think...
