### ISSUE TITLE
urlpath pattern fails for case string ending in pattern

### ISSUE THREAD

**Issue by dwr-psandhu** [intake/intake#529]
E.g. the pattern of 'blah{pattern}' fails as evidenced by 
```
intake.source.utils.path_to_glob('blah{pattern}')
'blah'
```

when it really should be blah*

it works fine if some non-empty string follows the pattern 
```
intake.source.utils.path_to_glob('blah{pattern}.csv')
'blah*.csv'
```

**Comment by dwr-psandhu** [comment]
Offending lines below

https://github.com/intake/intake/blob/d44979c6f43c6a77cbb1cb86cfa4486903cf36dd/intake/source/utils.py#L252-L254

**Comment by martindurant** [comment]
Sounds like you have a good test case and a fix!
Would you like to put these into a PR?

**Comment by dwr-psandhu** [comment]
#530 
@martindurant please review.
