### ISSUE TITLE
Regression in opening Catalog from a URL

### ISSUE THREAD

**Issue by TomAugspurger** [intake/intake#542]
With intake>=0.5.5, this warns and returns an empty catalog:

```python
>>> import intake
>>> cat_url = 'https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/master.yaml'
>>> cat = intake.Catalog(cat_url)
 UserWarning: deprecation: intake.Catalog now references the base class intake.catalog.base.Catalog
 If you want to open a generic URL, you should use intake.open_catalog
  warnings.warn('deprecation: intake.Catalog now references the base class intake.catalog.base.Catalog\n '
>>> list(cat)
[]
```

With 0.5.4 it returns the expected result

```
>>> list(cat)
['ocean', 'atmosphere', 'climate', 'hydro']
```

**Comment by danielballan** [comment]
Thanks, @TomAugspurger. It looks like the would-be "deprecation" of `intake.Catalog` was not handled properly in https://github.com/intake/intake/pull/479. The warning

```
 UserWarning: deprecation: intake.Catalog now references the base class intake.catalog.base.Catalog
 If you want to open a generic URL, you should use intake.open_catalog
```

calls it a deprecation, but in fact its meaning was changed in a bugfix release (0.5.4 -> 0.5.5).

@martindurant I propose a back-port release 0.5.6 to restore the original meaning of `intake.Catalog`. Looking forward in 0.6.0 and beyond, I think we should go through a slow deprecation -> removal process. A _replacement_ seems likely to create confusion. Is there a reason that `intake.Catalog` even _accepts_ a string? Could it raise and say, "You probably meant intake.open_catalog?"

@TomAugspurger The workaround, as you probably gleaned from the warning message, is to use `intake.open_catalog`.

**Comment by martindurant** [comment]
> Is there a reason that intake.Catalog even accepts a string? Could it raise and say, "You probably meant intake.open_catalog?"

This is probably the right way to go

**Comment by martindurant** [comment]
> I propose a back-port release 0.5.6

I am not opposed, happy to push it. We'll need a dangling branch to attach the tag to?

**Comment by danielballan** [comment]
Cool, thanks. Yes, that sounds right.
