### ISSUE TITLE
'auth' attribute and __init__ parameter removed from Catalog

### ISSUE THREAD

**Issue by danielballan** [intake/intake#543]
@martindurant Can you comment on the intent behind removing the `auth` attribute and `__init__` parameter from `Catalog`?

https://github.com/intake/intake/commit/bf5fb33d87914e004b29c792791ce208aee78313#diff-4e371ca3c37982987024b768df161ca8c8da696ff4a3459035c122e6cfb9bd15L52-L104

That backward-compatible change broke databroker in several places where we access it and pass it through to new instances, as in for example:

https://github.com/bluesky/databroker/blob/41700e7f04f5dcbd88eec17d4f21ab2a4e2b3c57/databroker/_drivers/mongo_normalized.py#L345

**Comment by danielballan** [comment]
For reference, the workaround in databroker is https://github.com/bluesky/databroker/pull/619/commits/0990e306f981686c6f6f3dccc4bdb5c220c9521b.

**Comment by martindurant** [comment]
Yeah, a `None` attribute is reasonable for the Catalog base class.

I think the motivation was not to have to import the auth stuff outside of remote catalogues, because it never gets used.

**Comment by danielballan** [comment]
Makes sense. I will open a PR upsteaming that fix on Monday.
