### ISSUE TITLE
Two new drivers for the plugin directory

### ISSUE THREAD

**Issue by AlbertDeFusco** [intake/intake#570]
[intake-sklearn](https://github.com/AlbertDeFusco/intake-sklearn): Load scikit-learn models from Pickle files (`sklearn`)

[intake-metabase](https://github.com/continuumio/intake-metabase): Load Metabase tables as DataFrames (`metabase_table`)

**Comment by martindurant** [comment]
Easiest is to PR to the docs page (plugin-directory.rst)

**Comment by AlbertDeFusco** [comment]
will do!
