### ISSUE TITLE
Mutate rather the overwrite self._entries

### ISSUE THREAD

**Issue by danielballan** [intake/intake#575]
An effect of this change is that anything else holding a reference to `self._entries` (say, in a subclass) will have a reference to a stale copy.

https://github.com/intake/intake/commit/e8759199587a7e2ac0e09aa3efcb88593c26caad#diff-600ceff2b8688f2ca92e05b9d68a79b03c7c4dce84c750497ae2aa99b7a2e2ebL793-R794

Would it be OK to revert back to mutating `self._entries`?

**Comment by martindurant** [comment]
The purpose of the change was to cope with a possible race of the entries being updated multiple times as set of files (for example) changes

cc https://github.com/intake/intake/issues/556

Happy to switch back to mutation, if races can be avoided.

**Comment by danielballan** [comment]
If the keys are built-in types, `dict.update` is threadsafe. If we are worried about non-string keys, we should apply a lock.
