### ISSUE TITLE
Development instructions are out-of-date

### ISSUE THREAD

**Issue by blackary** [intake/intake#589]
The development instructions reference a `conda` directory, which no longer exists in the codebase.

**Comment by martindurant** [comment]
Thanks for bringing this to me attention. I can spend some time soon (I have docs to write anyway), but your help would be good too, if you have corrections you can easily make.

**Comment by blackary** [comment]
I'd be happy to make changes. Would you have any objection to telling people to use one of the yml files in scripts/cli, or should they use the yml from the feedstock, or something else?

**Comment by martindurant** [comment]
Do you mean for environment description, or example catalogue?

On April 2, 2021 11:34:02 AM EDT, Zachary Blackwood ***@***.***> wrote:
>I'd be happy to make changes. Would you have any objection to telling
>people to use one of the yml files in scripts/cli, or should they use
>the yml from the feedstock, or something else?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/intake/intake/issues/589#issuecomment-812580944

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by blackary** [comment]
For building the development environment. I just built the conda environment for testing from `scripts/ci/environment-py38.yml`, but I'm not sure if you want that to be the recommended route for development.

**Comment by martindurant** [comment]
Yes, that's a good one to use, since it matches the CI
