### ISSUE TITLE
Issues opening catalogs from GitHub

### ISSUE THREAD

**Issue by malmans2** [intake/intake#591]
I'm suddenly having issues opening catalogs from GitHub.
It works fine if instead of opening from `https://raw.githubusercontent.com` I clone the catalogs and read locally.
I guess it has to do with encoding/decoding,  but I can't figure out what has changed and an easy fix.

Here is an example using Pangeo catalogs:
```python
from intake import open_catalog
cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/master.yaml")
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/intake/__init__.py", line 167, in open_catalog
    return registry[driver](uri, **kwargs)
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/intake/catalog/local.py", line 568, in __init__
    super(YAMLFileCatalog, self).__init__(**kwargs)
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/intake/catalog/base.py", line 100, in __init__
    self.force_reload()
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/intake/catalog/base.py", line 158, in force_reload
    self._load()
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/intake/catalog/local.py", line 603, in _load
    self.parse(text)
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/intake/catalog/local.py", line 672, in parse
    data = yaml_load(self.text)
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/intake/utils.py", line 78, in yaml_load
    return yaml.safe_load(stream)
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/scanner.py", line 251, in fetch_more_tokens
    return self.fetch_double()
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/scanner.py", line 655, in fetch_double
    self.fetch_flow_scalar(style='"')
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/scanner.py", line 666, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/scanner.py", line 1151, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_spaces(double, start_mark))
  File "/home/mattia/anaconda3/envs/intake_test/lib/python3.8/site-packages/yaml/scanner.py", line 1238, in scan_flow_scalar_spaces
    raise ScannerError("while scanning a quoted scalar", start_mark,
yaml.scanner.ScannerError: while scanning a quoted scalar
  in "<unicode string>", line 13, column 13:
          path: "{{CATALOG_DI
                ^
found unexpected end of stream
  in "<unicode string>", line 13, column 26:
          path: "{{CATALOG_DI
                             ^
```

**Environment**:

<details><summary>Output of <tt>conda env export</tt></summary>

name: intake_test
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - abseil-cpp=20210324.0=h9c3ff4c_0
  - affine=2.3.0=py_0
  - aiobotocore=1.2.2=pyhd8ed1ab_0
  - aiohttp=3.7.4=py38h497a2fe_0
  - aioitertools=0.7.1=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py38h497a2fe_2
  - arrow-cpp=3.0.0=py38hd6878d3_11_cpu
  - asciitree=0.3.3=py_2
  - asn1crypto=1.4.0=pyh9f0ad1d_0
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - aws-c-cal=0.4.5=h76129ab_8
  - aws-c-common=0.5.2=h7f98852_0
  - aws-c-event-stream=0.2.7=h6bac3ce_1
  - aws-c-io=0.9.1=ha5b09cb_1
  - aws-checksums=0.1.11=h99e32c3_3
  - aws-sam-translator=1.34.0=pyh44b312d_0
  - aws-sdk-cpp=1.8.151=hceb1b1e_1
  - aws-xray-sdk=2.7.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - bleach=3.3.0=pyh44b312d_0
  - blosc=1.21.0=h9c3ff4c_0
  - bokeh=2.3.1=py38h578d9bd_0
  - boost-cpp=1.74.0=hc6e9bd1_2
  - boto3=1.16.52=pyhd8ed1ab_0
  - botocore=1.19.52=pyhd8ed1ab_0
  - brotli=1.0.9=h9c3ff4c_4
  - brotlipy=0.7.0=py38h497a2fe_1001
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2020.12.5=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2020.12.5=py38h578d9bd_1
  - cffi=1.14.5=py38ha65f79e_0
  - cfitsio=3.470=hb418390_7
  - cfn-lint=0.48.2=py38h578d9bd_0
  - cftime=1.4.1=py38h5c078b8_0
  - chardet=4.0.0=py38h578d9bd_1
  - charls=2.2.0=h9c3ff4c_0
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.1=pyhd8ed1ab_0
  - cloudpickle=1.6.0=py_0
  - colorcet=2.0.6=pyhd8ed1ab_0
  - coverage=5.5=py38h497a2fe_0
  - coveralls=3.0.1=pyhd8ed1ab_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - curl=7.76.0=h979ede3_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py38h497a2fe_3
  - dask=2021.4.0=pyhd8ed1ab_0
  - dask-core=2021.4.0=pyhd8ed1ab_0
  - decorator=5.0.6=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2021.4.0=py38h578d9bd_0
  - docker-py=5.0.0=py38h578d9bd_0
  - docker-pycreds=0.4.0=py_0
  - docopt=0.6.2=py_1
  - ecdsa=0.16.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.3.0=h9c3ff4c_0
  - fasteners=0.14.1=py_3
  - fastparquet=0.5.0=py38h5c078b8_0
  - flask=1.1.2=pyh9f0ad1d_0
  - flask_cors=3.0.10=pyhd3deb0d_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - freexl=1.0.6=h7f98852_0
  - fsspec=0.9.0=pyhd8ed1ab_0
  - future=0.18.2=py38h578d9bd_3
  - geos=3.9.1=h9c3ff4c_2
  - geotiff=1.6.0=h2b14fbe_4
  - gettext=0.19.8.1=h0b5b191_1005
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h36c2ea0_2
  - glog=0.4.0=h49b9bf7_3
  - grpc-cpp=1.37.0=h36de60a_1
  - h5netcdf=0.10.0=pyhd8ed1ab_0
  - h5py=3.1.0=nompi_py38hafa665b_100
  - hdf4=4.2.13=h10796ff_1004
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - heapdict=1.0.1=py_0
  - holoviews=1.14.3=pyhd8ed1ab_0
  - hvplot=0.7.1=pyh44b312d_0
  - icu=68.1=h58526e2_0
  - idna=2.10=pyh9f0ad1d_0
  - imagecodecs=2021.3.31=py38h1455ab2_0
  - imageio=2.9.0=py_0
  - importlib-metadata=3.10.0=py38h578d9bd_0
  - inflection=0.5.1=pyh9f0ad1d_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - intake=0.6.2=pyhd8ed1ab_0
  - intake-parquet=0.2.3=py_0
  - ipykernel=5.5.3=py38hd0cf306_0
  - ipython=7.22.0=py38hd0cf306_0
  - ipython_genutils=0.2.0=py_1
  - itsdangerous=1.1.0=py_0
  - jedi=0.18.0=py38h578d9bd_2
  - jinja2=2.11.3=pyh44b312d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - jpeg=9d=h36c2ea0_0
  - json-c=0.15=h98cffda_0
  - jsondiff=1.1.2=py_0
  - jsonpatch=1.24=py_0
  - jsonpointer=2.0=py_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - junit-xml=1.9=pyh9f0ad1d_0
  - jupyter_client=6.2.0=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py38h578d9bd_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jxrlib=1.1=h7f98852_2
  - kealib=1.4.14=hcc255d8_2
  - kiwisolver=1.3.1=py38h1fd1430_1
  - krb5=1.17.2=h926e7f8_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libaec=1.0.4=h9c3ff4c_1
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libcurl=7.76.0=hc4aaa36_0
  - libdap4=3.20.6=hd7c4107_2
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgdal=3.2.1=h38ff51b_7
  - libgfortran-ng=9.3.0=hff62375_18
  - libgfortran5=9.3.0=hff62375_18
  - libglib=2.68.1=h3e27bee_0
  - libgomp=9.3.0=h2828fa1_18
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h238a007_1013
  - liblapack=3.9.0=8_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libnetcdf=4.7.4=nompi_h56d31a8_107
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.1=hfd2b0eb_2
  - libprotobuf=3.15.8=h780b84a_0
  - librttopo=1.1.0=h1185371_6
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialite=5.0.1=he52d314_3
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libthrift=0.14.1=he6d91bd_1
  - libtiff=4.2.0=hdc55705_0
  - libutf8proc=2.6.1=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.10=h72842e0_3
  - libxslt=1.1.33=h15afd5d_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - llvmlite=0.36.0=py38h4630a5e_0
  - locket=0.2.0=py_2
  - lxml=4.6.3=py38hf1fe3a4_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=1.1.1=py38h497a2fe_3
  - matplotlib-base=3.4.1=py38hcc49a3a_0
  - mistune=0.8.4=py38h497a2fe_1003
  - mock=4.0.3=py38h578d9bd_1
  - monotonic=1.5=py_0
  - more-itertools=8.7.0=pyhd8ed1ab_0
  - moto=2.0.0=pyhd8ed1ab_0
  - msgpack-numpy=0.4.7.1=pyh9f0ad1d_0
  - msgpack-python=1.0.2=py38h1fd1430_1
  - multidict=5.1.0=py38h497a2fe_1
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py38h578d9bd_3
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - netcdf4=1.5.6=nompi_py38hf887595_101
  - networkx=2.5=py_0
  - notebook=6.3.0=py38h578d9bd_0
  - numba=0.53.1=py38h0e12cce_0
  - numcodecs=0.7.3=py38h709712a_0
  - numpy=1.20.2=py38h9894fe3_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hf7af979_0
  - openssl=1.1.1k=h7f98852_0
  - orc=1.6.7=heec2584_1
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.3=py38h51da96c_0
  - pandoc=2.12=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - panel=0.11.2=pyhd8ed1ab_0
  - param=1.10.1=pyhd3deb0d_0
  - parquet-cpp=1.5.1=2
  - parso=0.8.2=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.2=py38ha0e1e83_1
  - pip=21.0.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pluggy=0.13.1=py38h578d9bd_4
  - pooch=1.3.0=pyhd8ed1ab_0
  - poppler=0.89.0=h2de54a5_5
  - poppler-data=0.4.10=0
  - postgresql=13.1=h6303168_2
  - proj=7.2.0=h277dcde_2
  - prometheus_client=0.10.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - prompt_toolkit=3.0.18=hd8ed1ab_0
  - psutil=5.8.0=py38h497a2fe_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py=1.10.0=pyhd3deb0d_0
  - pyarrow=3.0.0=py38hc9229eb_11_cpu
  - pycparser=2.20=pyh9f0ad1d_2
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pydap=3.2.2=pyh9f0ad1d_1001
  - pygments=2.8.1=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pysocks=1.7.1=py38h578d9bd_3
  - pytest=6.2.3=py38h578d9bd_0
  - pytest-cov=2.11.1=pyh44b312d_0
  - python=3.8.8=hffdb5ce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-jose=3.1.0=pyh9f0ad1d_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pyviz_comms=2.0.1=pyhd3deb0d_0
  - pywavelets=1.1.1=py38h5c078b8_3
  - pyyaml=5.4.1=py38h497a2fe_0
  - pyzmq=22.0.3=py38h2035c66_1
  - rasterio=1.2.2=py38h56add21_0
  - re2=2021.04.01=h9c3ff4c_0
  - readline=8.0=he28a2e2_2
  - requests=2.25.1=pyhd3deb0d_0
  - responses=0.13.2=pyhd8ed1ab_0
  - s2n=1.0.0=h9b69904_0
  - s3fs=0.6.0=pyhd8ed1ab_0
  - s3transfer=0.3.6=pyhd8ed1ab_0
  - scikit-image=0.18.1=py38h51da96c_0
  - scipy=1.6.2=py38h7b17777_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py38h578d9bd_3
  - six=1.15.0=pyh9f0ad1d_0
  - snappy=1.1.8=he1b5a44_3
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.3.0=pyhd8ed1ab_0
  - soupsieve=2.0.1=py_1
  - sqlite=3.35.4=h74cdb3f_0
  - sshpubkeys=3.1.0=py_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - terminado=0.9.4=py38h578d9bd_0
  - testpath=0.4.4=py_0
  - thrift=0.11.0=py38he1b5a44_1001
  - tifffile=2021.4.8=pyhd8ed1ab_0
  - tiledb=2.2.7=h91fcb0e_0
  - tk=8.6.10=h21135ba_1
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py38h497a2fe_1
  - tqdm=4.60.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - tzcode=2021a=h7f98852_1
  - tzdata=2021a=he74cb21_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - webob=1.8.7=pyhd8ed1ab_0
  - websocket-client=0.57.0=py38h578d9bd_4
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.36.2=pyhd3deb0d_0
  - wrapt=1.12.1=py38h497a2fe_3
  - xarray=0.17.0=pyhd8ed1ab_0
  - xerces-c=3.2.3=h9d8b166_2
  - xmltodict=0.12.0=py_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.0=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py38h497a2fe_1
  - zarr=2.7.0=pyhd8ed1ab_0
  - zeromq=4.3.4=h9c3ff4c_0
  - zfp=0.5.5=h9c3ff4c_5
  - zict=2.0.0=py_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - rangehttpserver==1.2.0
prefix: /home/mattia/anaconda3/envs/intake_test

</details>

**Comment by martindurant** [comment]
This is a known issue with fsspec, where the size inferred for the file is the gzip compressed size, resulting in truncation. Please try with fsspec master - which will be released soon.

**Comment by malmans2** [comment]
Yes, that worked! Thanks!
