### ISSUE TITLE
Reading json/jsonl files

### ISSUE THREAD

**Issue by blackary** [intake/intake#604]
We've made some simple drivers to handle json/jsonl files (where `.read()` returns a dictionary/list) that are slightly-modified versions of the textfiles driver. Would it make sense to make a PR to add those to intake itself, or would it be better to release them as separate packages?

**Comment by martindurant** [comment]
If it's small, just include it, I'd be happy to see it. If you plan on adding more drivers or features, you will find it faster to iterate in your own package.

**Comment by martindurant** [comment]
W can close this now?

**Comment by blackary** [comment]
Yes, I'll close it now. We may separate it out at some point and put it in intake or a separate package. Thanks for the info.
