### ISSUE TITLE
How to troubleshoot the intake GUI

### ISSUE THREAD

**Issue by kthyng** [intake/intake#619]
Hi there. I was working with catalogs with intake just fine two days ago (and had a question I posted about (#617)) but I haven't been able to follow up on that work due to some undetermined change in my workflow that leads to the intake GUI not recognizing the entries in my catalog. This looks like the following, in which the catalog will appear in the left hand column, but assets within an item are not recognizes and brought into the middle column as they were recently (once in the middle column, I could open them to look at metadata and create pre-configured plots). It seems there must be an inconsistency in my catalog entry that is preventing the GUI from recognizing it properly. (Though I am able to read in the dataset through intake without the GUI. I was also able to read in an example intake catalog successfully to the GUI and examine it.)

![image](https://user-images.githubusercontent.com/3487237/136285604-72110e55-0be2-4c03-8704-b98402c6f7b0.png)

So my question is: are there GUI logs I can look at to see what the problem is? Or do you suggest a way to troubleshoot? I am happy to give more information, but since this problem seems to have sort of randomly appeared, I'm more interested in how to approach fixing the issue than hoping I can get help with the undetermined issue itself.

**Comment by martindurant** [comment]
Feel free to request or propose changes, or come to the gitter channel for general conversation.
