### ISSUE TITLE
New release of intake

### ISSUE THREAD

**Issue by naatebarber** [intake/intake#631]
We'd like to pull in the updated intake from Pip, featuring the changes merged in with the `persist_mode` propagation branch: https://github.com/intake/intake/pull/629

**Comment by martindurant** [comment]
on my todo list.

By the way, feel free to join us at the [community meeting](https://github.com/intake/intake/issues/596) to tell us about your application.

**Comment by hussainsultan** [comment]
@martindurant any chance we could get a release here? it seems some of our internal downstream pipelines are blocked by it. 

@naatebarber please reach out in the community meeting and share our application with the team.

**Comment by martindurant** [comment]
Sorry I did not get around to this yet.

**Comment by hussainsultan** [comment]
Thanks @martindurant. Is there any way that @tylerpotts or @naatebarber can help support the release? It's just a bug fix that the team already made a PR (#618) for. Our alternate is to build conda packages for intake from master. 

Any other options? Thank you so much!

**Comment by martindurant** [comment]
0.6.5 now on pypi, soon building for conda-forge

**Comment by hussainsultan** [comment]
Thank you so much @martindurant

**Comment by martindurant** [comment]
Welcome @hussainsultan ! Did you want to organise a sync?
