### ISSUE TITLE
How to change `parameter` of `target` in `GenericTransform`

### ISSUE THREAD

**Issue by aaronspring** [intake/intake#638]
Lets assume my `target` has `parameter`s: `station = [1 default, 2]`
`GenericTransform` does not seem to inherit parameters from `target`. https://intake.readthedocs.io/en/latest/transforms.html#intake.source.derived.DerivedSource

https://github.com/intake/intake/blob/7cbd7d1f778566bf33b0242309fbdec0a9d3fc1f/intake/source/derived.py#L118-L147

Therefore only the default parameter `1` is accessible for derived catalog entries. Would it be possible to implement that parameters can be passed also? Like `DerivedEntry(station=2).read()` Or is that what `metadata` or `kwargs` should be used for?

Asking for https://github.com/aaronspring/remote_climate_data/pull/79

EDIT: If `kwargs` handles this, then only one parameter can be choosen for a derived dataset and a derived dataset wouldnt transform all parametrized options possible.

**Comment by martindurant** [comment]
I agree it should be possible to pass arguments down to the transform's original source. There is a problem of possible name conflicts (especially if the transform's source is another transform, and so on).

Checking back at the code now, the `target_kwargs` argument of `DerivedSource` appears to be meant for this situation. The actual instantiation happens in intake.source.derived.get_source(), and the picking of the target from potentially many targets in intake.source.derived..first() (by default). So the transformed source might be something like
```yaml
new_source:
  driver: intake.source.derived.DerivedSource
  description: ""
  arguments:
    target: ["other_source"]
    target_kwarg:
      other_source: <kwargs to pass here>
```
So if you wanted to override the target_kwargs as a user, you'd have to replicate them and change the bits you wanted and pass it back in again. Or else encode user_parameters, but type coercion for an argument is not very flexible, so anything not string might be tricky to do by templating.

This experimental feature does not appear to be tested!

**Comment by aaronspring** [comment]
can confirm this works.

```python
cat.other_source(target_kwargs=dict(other_source=dict(user_parameter_of_other_source='value'))).read().plot()
```
is a bit long for a user to type. I guess the second `other_source` is needed because `target` could contain multiple items.

a shortcut of omitting the second `other_source` if only one `target` wouldnt be possible/useful to implement I guess?
```python
cat.other_source(target_kwargs=dict(user_parameter_of_other_source='value')).read().plot()
```

**Comment by martindurant** [comment]
Yes, I suppose we could do something for the first/only target, but we'd also still have to look for the key named the same as the target, to allow for both.

**Comment by aaronspring** [comment]
and is it possible to access the same `plots` as in the `target`?

**Comment by martindurant** [comment]
Not quite - the metadata of the target (including plots) are contained in the derived source metadata under "target", so won't immediately look like a plot. In the general case, I don't suppose a set of arguments to a plot to the target will make sense to the derived source.

**Comment by aaronspring** [comment]
> In the general case, I don't suppose a set of arguments to a plot to the target will make sense to the derived source.

ok. I understand
