### ISSUE TITLE
WHATSNEW section in docs?

### ISSUE THREAD

**Issue by raybellwaves** [intake/intake#640]
A place to add a summary of

https://github.com/intake/intake/compare/0.6.4...0.6.5

**Comment by martindurant** [comment]
I think that's a good idea. Do you happen to have a tool to hand to auto-generate from PR commit messages (like in the diff) so we can get a PR rolling?

**Comment by raybellwaves** [comment]
```
git clone https://github.com/intake/intake.git
cd intake
git log --pretty=reference ^0.6.4 0.6.5
```

Small enough to do by eye. I haven't added the sections in https://docs.dask.org/en/latest/changelog.html#v2022-04-0 but just the major PRs.

- Added tiled
- Added google-analytics plugin
- Allow paramters pass through catalog
- Add json and jsonl drivers
- Add mlist

**Comment by martindurant** [comment]
Thanks, @raybellwaves
