### ISSUE TITLE
Creating catalog in a script

### ISSUE THREAD

**Issue by kthyng** [intake/intake#642]
Hi! I'm using `intake` some more now and my current use case is to create a catalog in a script. I've seen in the docs that one might do this with
```
import intake
cat = intake.catalog.Catalog
catalog.add(source)
```
where `source`, I think, would be a dataset I have previously read in using `intake`, such as what I am doing with `intake-xarray`:
```
source = intake.open_opendap([filepath])
```
Is this idea correct? And if so, is there a new way to do this? Apparently `add` is not available to the catalog.

Ultimately, the idea I am hoping for is to:
1. Create catalog instance
2. Add data sources that I open in the script using `intake`
3. Save the catalog to a file to use in the future.

Thanks!

**Comment by martindurant** [comment]
`add` is only available to a YAMLFileCatalog, i.e., one loaded from an existing file. That leaves you with a bootstrap problem.

Honesty, I think the easiest way to do it is to deal with this is to handle the dictionary views of the data sources directly. This gives you the idea of how it should look:
```python
intake.open_opendap([filepath])._yaml()
```

So you can easily make your own dict like:
```python
cat_dict = {"sources": {
    name: {
        "description": "",
        "driver": "opendap",
        "args": {"filename": filename},
        "metadata": {}
    }
    for name, filename in zip(names, filenames)
}
yaml.dump(cat_dict, default_flow_style=False)
```

**Comment by kthyng** [comment]
@martindurant Thanks, I really appreciate your response!

However, I am still confused how to go from the code you have there to an intake catalog object. Could you connect the dots for me?

**Comment by martindurant** [comment]
The output of the yaml dump is text, which you can put into a .yaml catalog file. 

Or did you not want to write a file at all? If the latter, then you need `Catalog.from_dict`, which takes a `{name: source}` dict, e.g., 
```python
sources = {"first_source": intake.open_opendap([filepath]), ...}
cat = Catalog.from_dict(sources)
```

**Comment by kthyng** [comment]
Ah, ok I had tried both of those approaches and hit errors so I thought they weren't the right ideas.

I've been able to get the first to work by fixing the type of one piece of metadata that it turned out was causing an error.

In the second, dictionary, approach, when I try to define the catalog with a dictionary, I hit this error once I try to recall the entry in the catalog:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [100], in <module>
----> 1 mycat['sfbofs2']

File ~/miniconda3/envs/goods/lib/python3.10/site-packages/intake/catalog/base.py:436, in Catalog.__getitem__(self, key)
    427 """Return a catalog entry by name.
    428 
    429 Can also use attribute syntax, like ``cat.entry_name``, or
   (...)
    432 cat['name1', 'name2']
    433 """
    434 if not isinstance(key, list) and key in self:
    435     # triggers reload_on_change
--> 436     s = self._get_entry(key)
    437     if s.container == 'catalog':
    438         s.name = key

File ~/miniconda3/envs/goods/lib/python3.10/site-packages/intake/catalog/utils.py:45, in reload_on_change.<locals>.wrapper(self, *args, **kwargs)
     42 @functools.wraps(f)
     43 def wrapper(self, *args, **kwargs):
     44     self.reload()
---> 45     return f(self, *args, **kwargs)

File ~/miniconda3/envs/goods/lib/python3.10/site-packages/intake/catalog/base.py:316, in Catalog._get_entry(self, name)
    313 @reload_on_change
    314 def _get_entry(self, name):
    315     entry = self._entries[name]
--> 316     entry._catalog = self
    317     entry._pmode = self.pmode
    319     up_names = set((up["name"] if isinstance(up, dict) else up.name)
    320                     for up in entry._user_parameters)

AttributeError: 'dict' object has no attribute '_catalog'
```

Anyway I can use the first approach to do what I need. Thank you for your time and help!

**Comment by martindurant** [comment]
Sorry, the dict option should have had LocalCatalogEntry instances as the values, not sources
