### ISSUE TITLE
test_mlist_parameter not passing

### ISSUE THREAD

**Issue by raybellwaves** [intake/intake#645]
https://github.com/intake/intake/blob/master/intake/catalog/tests/test_parameters.py#L167

**Comment by martindurant** [comment]
It seems that the default given value is not an allowed value, but should be.
```
up = UserParameter("", "", "mlist", default=["a"], allowed=["a", "b"])
```
Perhaps in such a situation, the default should be picked from the allowed values, or validation should only happen some time later.
