### ISSUE TITLE
Catalog-level description not carrying through?

### ISSUE THREAD

**Issue by kthyng** [intake/intake#649]
Hi, I am working with a set of nested catalogs and I'm having trouble with losing information when I save — I have two sets of the catalogs so that I can update information, but the catalog-level descriptions do not come through. Below is an example I created to demonstrate.  Any idea why the description is being dropped and how to keep it in there? Thanks!

```
from intake.catalog import Catalog
from intake.catalog.local import LocalCatalogEntry

cat1 = Catalog.from_dict({
            'name': LocalCatalogEntry('name', 
                                      description='description',
                                      driver=intake.catalog.local.YAMLFileCatalog, 
                                        )
},
                name='overall catalog name',
                description='overall catalog description'
    
)

cat1.save('desc_test.yaml')

cat1
```
> overall catalog name:
  args:
    description: overall catalog description
    name: overall catalog name
  description: overall catalog description
  driver: intake.catalog.base.Catalog
  metadata: {}

But once I read in that saved catalog, the overall description is gone:
```
cat2 = intake.open_catalog('desc_test.yaml')
cat2
```
> overall catalog name:
  args:
    path: desc_test.yaml
  description: ''
  driver: intake.catalog.local.YAMLFileCatalog
  metadata: {}

**Comment by martindurant** [comment]
Thanks, that is a very nice and concrete bug, in the form of testable code! If you like, you could make a PR adding exactly this test, which will fail in CI. 
Either `save` doesn't consider the description field, or `YAMLFileCatalog`'s parsing doesn't look for it (or both!). I don't immediately know which, but a quick view of the output file should tell you.

**Comment by kthyng** [comment]
Ok this ended up being straight forward, I have a PR here #650
