### ISSUE TITLE
Understanding DataSourceBase `_load_metadata`

### ISSUE THREAD

**Issue by djhoese** [intake/intake#672]
I'm preparing to make a custom driver/plugin for intake to use the Satpy library. While reading the documentation I got a little confused by the usage of `_load_metadata` and `_get_schema`.

https://intake.readthedocs.io/en/latest/making-plugins.html#subclassing-intake-source-base-datasourcebase

The docs say to define `_get_schema`, but then use `_load_metadata` in the `read` method below that definition. Then later in this section it says:

> Note that all of these methods typically call _get_schema, to make sure that the source has been initialised.

So I looked at the source and found this:

https://github.com/intake/intake/blob/2db1ec3e954666e2bf3d90b82afe45b7af1906da/intake/source/base.py#L282-L289

This makes me think that I (the plugin developer) and the documentation should be changed to use `_load_metadata` in all DataSource methods instead of `_get_schema`. It seems that if I only ever used `_get_schema` there is a chance that some of the above properties (ex. `dtype`, `shape`, etc) would never be initialized on the DataSource subclass.

Is that correct? Any clarification would be appreciated. Thanks.

**Comment by martindurant** [comment]
Sorry I didn't reply earlier, I'll respond shortly.

**Comment by martindurant** [comment]
I think that the difference that you are getting at here, is that not all data sources have extensive information about themselves. Whereas a schema must exist, even if it has minimal information, attributes like dtype only make sense for arrays and dataframes, even if those make up the vast majority of intake targets. As you can see, all the base load_metadata method does is call _get_schema and read its contents. That's probably fine for many uses, and so no need to override it. It is debatable how useful the schema object is at all....

In general, an intake driver is a pretty simple thing, and we have had some discussions around making the required API even smaller/simpler. The only thing that really matters is `read()` in many contexts; but the intent is that there should be three stages:
- a near zero cost to init, which provides little or nothing more than the originating catalog definition did
- a constant-time cost to interrogate the dataset and provide any metadata we can, which depends heavily on the storage
- a linear-time cost to reading (partition-wise or complete) into standard pydata structures
Anything you can provide for feedback here would be helpful, even if it is only making the docs clearer.

**Comment by martindurant** [comment]
Should we close this, or is there more action to be taken?

**Comment by djhoese** [comment]
Let's close it for now. I haven't had time to get back to this and fully understand what you commented. It sounds like the things I was concerned about are "just the way they are" and are something I should just do to stay consistent.
