### ISSUE TITLE
Can a user parameter depend on another?

### ISSUE THREAD

**Issue by kthyng** [intake/intake#676]
I'd like to have a user parameter for an intake catalog, `yesterday`, that depends on another user parameter, `today`. Something like:

```
name: example

sources:
  example_source:
    [other stuff]
    parameters:
      tod:
        description: Pandas like Timestamp for today
        type: datetime  # one of bool, str, int, float, list[str | int | float], datetime,
        default: today
      yesterday:
        description: Pandas like Timestamp for yesterday
        type: datetime  # one of bool, str, int, float, list[str | int | float], datetime,
        default: today - pd.Timedelta('1 day')
```
Or, alternatively, could the jinja templating decipher subtracting 1 day from `today` when using `today` to create some strings?

Are either of these possible? I've tried some reasonable things and couldn't get it to work. Thanks.

**Comment by SultanOrazbayev** [comment]
There is [this answer](https://stackoverflow.com/a/54150216/10693596), but I am not sure if this is a good idea (conditional on it working).

**Comment by SultanOrazbayev** [comment]
Also, while going through old issues saw [this issue](https://github.com/intake/intake/issues/195#issuecomment-438031712), which has a relevant answer by mdurant:

>> should be datetime.today() - datetime.timedelta(days=5*365). Is something like that currently supported

>No, the only functions currently supported for expansion of the defaults are for environment variables and external shell. Others could be possible, but it does not seem right to try to put executable code directly into the catalog spec like this. However, a custom driver is free to have whatever internal defaults it likes, or interpret strings to mean specific things, like any python code. Suggestions on a comprehensive grammar of parameters that would be able to express your requirements welcome here.

So perhaps a custom driver is one way to go about this.

**Comment by martindurant** [comment]
Agreed, the templating system is pretty simplistic. jinja can do a lot, so you can try various magic functions from there, but I don't think there's a reasonable way to tie together different parameters, since it would make the set of parameters into a graph with possible circular dependencies. It is true, however, that drivers are cheap to create, so you could have something custom to deal with your specific case.

**Comment by raybellwaves** [comment]
If you've got a known pattern e.g. 20220101-20220102 (e.g. second number is a day ahead of the other) you can use 
https://github.com/DTN-Public/intake-pattern-catalog for one date and derive the other date in a f-string

e.g.
  entry:
    description: description
    driver: pattern_cat
    args:
      urlpath: s3://BUCKET/{datetime:%Y%m%d}-{datetime - pd.Timedelta('1D'):%Y%m%d}.csv

**Comment by kthyng** [comment]
Thank you all for your answers — I meant to respond long ago but was sidetracked. I ended up not being able to get this to work in the way I hoped,  but was able to make a workaround. 

@raybellwaves I looked at your pattern catalog and it looked good. I may be coming back to that one in the future.
