### ISSUE TITLE
Usage/design question: why does `.urlpath` return a string?

### ISSUE THREAD

**Issue by SultanOrazbayev** [intake/intake#677]
This might be a trivial question, but is there a reason why the value returned by `.urlpath` is a string rather than `fsspec` or `Pathlib` object?

Would this be a useful feature to have? If so, I could give it a shot.

**Comment by martindurant** [comment]
fsspec uses strings to denote paths everywhere, there is no "fsspec path object". Pathlib is annoying and surprisingly expensive to operate on (but there is universal_pathlib if you wanted it).

**Comment by martindurant** [comment]
Furthermore, most data driver backends expect strings in most cases, for example pandas.read_csv or xarray.open_dataset.

**Comment by SultanOrazbayev** [comment]
Interesting, I had one use case in mind around being able to get the path/stem info and glob folder contents. However, I see that this is not generally necessary to be done within intake.
