### ISSUE TITLE
AttributeError: open_esm_datastore

### ISSUE THREAD

**Issue by savannahferretti** [intake/intake#700]
Hi, I'm trying to load CMIP6 data from the Pangeo Cloud using the following code:
```python
import intake
url = 'https://storage.googleapis.com/cmip6/pangeo-cmip6.json'
col = intake.open_esm_datastore(url)
```
And I get the following error: ```AttributeError: open_esm_datastore```
![image](https://user-images.githubusercontent.com/103456955/213210874-352e3dfa-07f4-4d4d-8e02-fd1c8a768d12.png)

I have used this syntax successfully before (the other day). Here is what I have in my environment:
```
# Name                    Version                   Build  Channel
intake                    0.6.6           py310hecd8cb5_0  
intake-esm                2022.9.18          pyhd8ed1ab_0    conda-forge
```

**Comment by martindurant** [comment]
Can you `import intake_esm`? I suppose something has gone wrong with your environment.

**Comment by savannahferretti** [comment]
I cannot, even though both intake and intake_esm were install with conda.

From: Martin Durant ***@***.***>
Date: Wednesday, January 18, 2023 at 1:05 PM
To: intake/intake ***@***.***>
Cc: Savannah Ferretti ***@***.***>, Author ***@***.***>
Subject: Re: [intake/intake] AttributeError: open_esm_datastore (Issue #700)

Can you import intake_esm? I suppose something has gone wrong with your environment.

**Comment by martindurant** [comment]
Perhaps you get some informative traceback?
If not, I recommend installing again in a fresh environment.

**Comment by savannahferretti** [comment]
I created a new environment and installed fresh: Here is what I installed (env is Python 3.9):

  *   conda install -c anaconda ipykernel
  *   conda install -c anaconda numpy
  *   conda install -c anaconda sympy
  *   conda install -c conda-forge pandas
  *   conda install -c conda-forge scipy
  *   conda install -c conda-forge matplotlib
  *   conda install -c conda-forge proplot
  *   conda install -c conda-forge xarray dask netdcf4 bottleneck
  *   conda install -c conda-forge opencv
  *   conda install -c conda-forge intake-esm
When running this code:

import intake
url = https://raw.githubusercontent.com/NCAR/intake-esm-datastore/master/catalogs/pangeo-cmip6.json
dataframe = intake.open_esm_datastore(url)

I get a new error now (on the dataframe=... line):

ImportError: HTTPFileSystem requires "requests" and "aiohttp" to be installed


From: Martin Durant ***@***.***>
Date: Wednesday, January 18, 2023 at 2:21 PM
To: intake/intake ***@***.***>
Cc: Savannah Ferretti ***@***.***>, Author ***@***.***>
Subject: Re: [intake/intake] AttributeError: open_esm_datastore (Issue #700)

Perhaps you get some informative traceback?
If not, I recommend installing again in a fresh environment.

**Comment by martindurant** [comment]
Can you install aiohttp and requests? Perhaps intake-esm is happy to work with local/networked storage, but to read from HTTP you need these. At least the import worked!

By the way, I would generally recommend putting all our requirements in a YAML file and creating the environment from that, since it will help get a consistent set of recent versions, especially since you are mixing channels (do you need to?).

**Comment by savannahferretti** [comment]
Ok, so I created another environment just with these to see what things need to be downloaded before intake_esm:
conda install -c anaconda ipykernel
conda install -c anaconda requests
conda install -c anaconda aiohttp
conda install -c conda-forge intake-esm

But then when trying to run something simple:
import intake
cat_url = https://storage.googleapis.com/cmip6/pangeo-cmip6.json
col = intake.open_esm_datastore(cat_url)
col

I get this error:

AttributeError: open_esm_datastore

What are the dependencies of intake-esm that I need to have downloaded so that I can load in CMIP6 data from Pangeo (example here<https://gallery.pangeo.io/repos/pangeo-gallery/cmip6/intake_ESM_example.html>)?

Thanks for helping!

From: Martin Durant ***@***.***>
Date: Wednesday, January 18, 2023 at 8:05 PM
To: intake/intake ***@***.***>
Cc: Savannah Ferretti ***@***.***>, Author ***@***.***>
Subject: Re: [intake/intake] AttributeError: open_esm_datastore (Issue #700)

Can you install aiohttp and requests? Perhaps intake-esm is happy to work with local/networked storage, but to read from HTTP you need these. At least the import worked!

By the way, I would generally recommend putting all our requirements in a YAML file and creating the environment from that, since it will help get a consistent set of recent versions, especially since you are mixing channels (do you need to?).

**Comment by martindurant** [comment]
I did this:

file esm_env.yaml
```yaml
name: esm_env

channels:
  - conda-forge
  - defaults

dependencies:
  - ipython
  - intake-esm
  - fsspec
  - aiohttp
  - requests
```

Then:
```bash
$ conda env create -f esm_env.yaml
$ conda activate esm_env
$ ipython
In [1]: import intake
   ...: cat_url = https://storage.googleapis.com/cmip6/pangeo-cmip6.json
   ...: cat = intake.open_esm_datastore(cat_url)
```
worked fine.

**Comment by savannahferretti** [comment]
So you created esm_env.yml with just what is typed below? Then made it into an environment?


channels:

  - conda-forge

  - defaults



dependencies:

  - ipython

  - intake-esm

  - fsspec

  - aiohttp

  - requests



From: Martin Durant ***@***.***>
Date: Thursday, January 19, 2023 at 1:12 PM
To: intake/intake ***@***.***>
Cc: Savannah Ferretti ***@***.***>, Author ***@***.***>
Subject: Re: [intake/intake] AttributeError: open_esm_datastore (Issue #700)

I did this:

file esm_env.yaml

name: esm_env



channels:

  - conda-forge

  - defaults



dependencies:

  - ipython

  - intake-esm

  - fsspec

  - aiohttp

  - requests

Then:

$ conda env create -f esm_env.yaml

$ conda activate esm_env

$ ipython

In [1]: import intake

   ...: cat_url = https://storage.googleapis.com/cmip6/pangeo-cmip6.json<https://urldefense.com/v3/__https:/storage.googleapis.com/cmip6/pangeo-cmip6.json__;!!CzAuKJ42GuquVTTmVmPViYEvSg!Jb_xL7HlOIsYTgu_FmrgnYRX-3Z3EJnz4Y1FFulproSlZ0ZKqvZ0rR70IT8eMuym_zgpAlpb6pxuEV-zVege48365JKMPto$>

   ...: cat = intake.open_esm_datastore(cat_url)

worked fine.

**Comment by martindurant** [comment]
Yes, you create the YAML file with the contents I have, and then give that to conda. https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file

**Comment by martindurant** [comment]
Was this resolved, @savannahferretti ?

**Comment by savannahferretti** [comment]
Yes, thank you!

From: Martin Durant ***@***.***>
Date: Thursday, February 2, 2023 at 3:21 PM
To: intake/intake ***@***.***>
Cc: Savannah Ferretti ***@***.***>, Mention ***@***.***>
Subject: Re: [intake/intake] AttributeError: open_esm_datastore (Issue #700)

Was this resolved, @savannahferretti<https://urldefense.com/v3/__https:/github.com/savannahferretti__;!!CzAuKJ42GuquVTTmVmPViYEvSg!M433miaFqAW0HK2Vt_QEtI13c7M-CyPlqVbfUHpsagMVULmMIZdvAAMREPhjZCqHPAXPOiFjI6aMPSECFElib2TY4sF8TL0$> ?
