### ISSUE TITLE
Docs have the version in <title>

### ISSUE THREAD

**Issue by intentionally-left-nil** [intake/intake#713]
E.g. `<title>Catalogs — intake 0.6.7+24.g9d9eebd.dirty documentation</title>`

This hurts SEO (duckduckgo displays it prominently for example)

**Comment by martindurant** [comment]
@blakerosenthal is working on this, following #709

**Comment by blakerosenthal** [comment]
Thanks for pointing this out @intentionally-left-nil -- I hadn't noticed this. After clicking through a couple other projects I'm realizing this is a quirk of the 'sphinx_rtd_theme` (intake-parquet and intake-xarray have the same issue, e.g.). There's probably a simple way to tweak the template.
