### ISSUE TITLE
Enable hotplugging into Intake registry?

### ISSUE THREAD

**Issue by blakerosenthal** [intake/intake#717]
I noticed that `intake.register_driver` adds a new entry to the registry but [make_open_functions](https://github.com/intake/intake/blob/1e26dc1bb9e6beedb683761cbc5ec49a4b6a2b30/intake/__init__.py#L75) is only called on import so my new drivers don't get their `intake.open_*` functions until I reinstall or call `make_open_functions` manually. Would it make sense to build the open function whenever a new driver is registered?

**Comment by martindurant** [comment]
Yes, that makes sense.
