### ISSUE TITLE
 intake.open_thredds_cat shows error

### ISSUE THREAD

**Issue by tarankalra1** [intake/intake#730]
i have installed intake via pip (version 0.6.5). I am getting an error while opening a sample xml file. 

<img width="1163" alt="Screen Shot 2023-04-24 at 3 51 47 PM" src="https://user-images.githubusercontent.com/10886837/234101596-1160ada2-d661-4648-abdd-e83ccd9240df.png">

**Comment by martindurant** [comment]
Do you have intake-thredds installed?

**Comment by tarankalra1** [comment]
that was quick. thank you and that helped.

**Comment by martindurant** [comment]
@blakerosenthal : perhaps an attribute lookup of the form `intake_*` should, if unsuccessful, direct users to the intake plugin registry?

**Comment by blakerosenthal** [comment]
Whoops, sorry I missed this notification. I think this is a great idea. Intake could do better about displaying missing libraries in general.
