### ISSUE TITLE
Update GUI to work with latest Panel release

### ISSUE THREAD

**Issue by blakerosenthal** [intake/intake#746]
Firing up the GUI gives me the following warning
```
WARNING:param.panel_extension: A HoloViz extension was loaded previously. This means the extension is already initialized and custom raw_css resources could not be loaded. If you are loading custom extensions with pn.extension(...) ensure that this is calledbefore any other HoloViz extension such as hvPlot or HoloViews.
```

**Comment by martindurant** [comment]
Was this with output_notebook, pn.extension or neither?

Hm. Not too worried about a warning, but we should probably track it down. The code that executes upon `intake.gui`, constructing the default GIU instance, does apply some CSS which may be unnecessary with the new panel 1.0 setup.

https://github.com/intake/intake/blob/master/intake/interface/__init__.py#L31

**Comment by blakerosenthal** [comment]
This was with `source.gui` in https://github.com/intake/intake-examples/blob/master/GUI.ipynb
