### ISSUE TITLE
Enhancement?: make _pattern_to_glob() honor ?s in format strings

### ISSUE THREAD

**Issue by JessicaS11** [intake/intake#776]
Hello! I modified the [`intake.utils._pattern_to_glob()` function](https://github.com/intake/intake/blob/d5d668a0a488de01746a80253531ba011fe12822/intake/source/utils.py#L221) for my own use case to honor character-length formatting in strings. Based on the way my data was stored, allowing the generalization to all `*` picked up a lot of unwanted files. I'm wondering if that "feature" (since some may not consider it a feature) would be useful to contribute here or not. I noticed that `_pattern_to_glob` doesn't seem to exist in the latest 2.0.0a2 tag, though it's still present in the master branch, so perhaps it's a moot point.

Examples for my modified function:
```
Examples
--------
>>> _pattern_to_glob('{year}/{month}/{day}.csv')
'*/*/*.csv'
>>> _pattern_to_glob('{year:4}/{month:2}/{day:2}.csv')
'????/??/??.csv'
>>> _pattern_to_glob('data/{year:4}{month:02}{day:02}.csv')
'data/????????.csv'
>>> _pattern_to_glob('data/*.csv')
'data/*.csv'
```

Please let me know and, pending the answer, I'll open a PR.

**Comment by martindurant** [comment]
I had thought this very little used and it is removed in upcoming Intake Take2 (v2.0.0), which is still in unmerged PR. It would be more involved, you you might be interested in implementing your pattern for the new framework.

**Comment by JessicaS11** [comment]
We've actually recently deprecated its use in our own implementation and it was the process of removing the code that prompted me to open this issue. Happy to consider it if it's a feature others would/are using, but it sounds like there's little enough demand that we should focus our dev energy elsewhere for now!

**Comment by martindurant** [comment]
Could you please share your improved `_pattern_to_glob` - it may be useful?

**Comment by JessicaS11** [comment]
```
def _pattern_to_glob(pattern):
    """
    Adapted from intake.source.utils.path_to_glob to convert a path as pattern into a glob style path
    that uses the pattern's indicated number of '?' instead of '*' where an int was specified.

    Returns pattern if pattern is not a string.

    Parameters
    ----------
    pattern : str
        Path as pattern optionally containing format_strings

    Returns
    -------
    glob_path : str
        Path with int format strings replaced with the proper number of '?' and '*' otherwise.

    Examples
    --------
    >>> _pattern_to_glob('{year}/{month}/{day}.csv')
    '*/*/*.csv'
    >>> _pattern_to_glob('{year:4}/{month:2}/{day:2}.csv')
    '????/??/??.csv'
    >>> _pattern_to_glob('data/{year:4}{month:02}{day:02}.csv')
    'data/????????.csv'
    >>> _pattern_to_glob('data/*.csv')
    'data/*.csv'
    """
    from string import Formatter

    if not isinstance(pattern, str):
        return pattern

    fmt = Formatter()
    glob_path = ""
    # prev_field_name = None
    for literal_text, field_name, format_specs, _ in fmt.parse(format_string=pattern):
        glob_path += literal_text
        if field_name and (glob_path != "*"):
            try:
                glob_path += "?" * int(format_specs)
            except ValueError:
                glob_path += "*"
                # alternatively, you could use bits=utils._get_parts_of_format_string(resolved_string, literal_texts, format_specs)
                # and then use len(bits[i]) to get the length of each format_spec
    # print(glob_path)
    return glob_path
```

**Comment by martindurant** [comment]
Thank you!

**Comment by martindurant** [comment]
This is now merged for Intake Take2, as datatype CSVPattern and reader DaskCSVPattern. It could be argued that there was no need for a separate reader for this, it could have been folded into DaskCSV, but I don't want anyone looking at that more common class to get confused.

**Comment by dpro-shc** [comment]
Hey Martin, actually the way I found Intake was though its pattern features: we get data from a source where none of their files contain date columns, except for in the filenames...

Intake was the only option I could find that offered a reasonable way to ingest this data, including dates. This feature might be more widely used than you think!

**Comment by martindurant** [comment]
@dpro-shc , @ALAB-SHC : would love to see your workflow, and how we might phrase them with Intake Take2. All the fundamentals are the same, but essentially all the functionality has been split into opt-in classes rather than monolithic classes with loads of keyword arguments. Do intake.readers.CSVPattern/intake.readers.[Dask]CSVPatternReader do everything you need?

**Comment by martindurant** [comment]
Thanks @dpro-shc . It would take me a while to go through that and describe how to implement it in V2. Of course, if you have a satisfactory workflow with <2, that's fine too.

**Comment by dpro-shc** [comment]
you got it, I took a look at some of the readers and I believe the relevant ones are the Condition and FileExistsReader. As long as the conditional's condition can access the resulting dict of reverse_format, then the implementation should be feasible.
