### ISSUE TITLE
Add missing intake/_version.py

### ISSUE THREAD

**Issue by kadykov** [intake/intake#781]
As it is required in 
https://github.com/intake/intake/blob/6426267e4f01ed55b79c15ad3e514b2176442720/intake/__init__.py#L10

**Comment by martindurant** [comment]
Isn't this always made by `pip`? Or are you saying there should be a fallback file for the case that the package is being imported directly from the repo?

**Comment by kadykov** [comment]
Yes, `pip` + `setuptools_scm` create the file, but the idea is to be able to use the package directly from the repository without installation.
Solved by #782, so we can close it.
