### ISSUE TITLE
How to read NetCDF4 file correctly in Take2?

### ISSUE THREAD

**Issue by forestbat** [intake/intake#792]
I want to read netcdf file, and my code is this:
```
import intake as itk
# obj is path of file, such as '/home/someuser/'
nc_source = itk.datatypes.HDF5(obj, storage_options=storage_option)
nc_src_reader = itk.readers.HDF5(nc_source).to_reader()
data_obj = nc_src_reader.read()
```
It crashed with this: https://pastebin.com/N7NDgq6e
`TypeError: argument of type 'HDF5' is not iterable`
And I haven't found any document which solve this, so can you tell me what's the correct method?
Thank you for a lot.

**Comment by forestbat** [comment]
```
nc_source = itk.datatypes.HDF5(obj, storage_options=storage_option)
nc_src_reader = itk.readers.DaskHDF(nc_source).to_reader()
data_obj = nc_src_reader.read()
```
is effective.

**Comment by martindurant** [comment]
Note, I don't recommend using the abbreviation "itk" because of itkpythonpackage.readthedocs.io
