### ISSUE TITLE
Hierarchical Catalogue in Intake 2

### ISSUE THREAD

**Issue by nshankar** [intake/intake#805]
Hello, new to intake here. 

Is there any documentation/examples on creating a hierarchical catalogue using the intake 2 API? It seems this was possible in intake 1 via either nested yaml files (https://github.com/intake/intake/issues/425)  or the [zillow plugin](https://github.com/intake/intake/blob/9d33c86e1353ddcbea1d434d98e99af5ef61f36d/docs/plugins.yaml#L92-L95) but I'm not sure if there is a way to do this with the new interface.

For context I would like to create a catalogue of this public s3 dataset: https://registry.opendata.aws/noaa-wod/ where I can add one dataset `wod` to my catalogue which has 1 reader (xarray opening a netcdf file contained in the [bucket](https://noaa-wod-pds.s3.amazonaws.com/index.html)) but allows me to flexibly select which file I want at runtime. Would you suggest user parameters as the right way to do this?

If you can share a code example with intake 2 I'm happy to raise a PR to update the documentation.

**Comment by martindurant** [comment]
I'll add examples of how to make nested catalogs (i.e., catalogs which point to other catalogs) here, and maybe show how to replicate the zillow plugin for intake 2. However, I think that a user_paratemer is probably what you are after.

Here is what your workflow might have looked like, with comments inline.

```python
import intake

# one example data URL
url = "https://noaa-wod-pds.s3.amazonaws.com/2023/wod_pfl_2023.nc"

# the recommended data types includes HDF, which is the right one. With head=True, 
# it is the only one, but this takes longer
intake.recommend(url, head=False)
data = intake.readers.datatypes.HDF5(url)
reader = data.to_reader("xarray")
cat = intake.Catalog()
cat["wod"] = reader

# for me, the hex value is the identity of the data entry (see from cat.pprint() )
# name= is what we want to call the new parameter, and value= is what
# pattern in the data entry we want to replace
# We store to "Catalog" so it shows up in the repr, but this is optional
cat.extract_parameter("8e372d5df1e7708f", name="year", value="2023", store_to="Catalog")
# set the description of the parameter
cat.get_entity["year"].description
# set the reader or data metadata
cat.get_entity("wod").metadata
cat.pprint()
# maybe save to file
cat.to_yaml_file()

# example usage
cat(year=2024).wod.read()
```

**Comment by nshankar** [comment]
Thank you Martin, these kind of code samples are very helpful when working in intake 2! I was able to replicate the behavior here and also learned some new intake 2 tricks.

This approach does the trick for the `wod` but it will be cumbersome for working with more complex directory structures. To expand: `wod` is just one dataset I want to catalog and each dataset has its own unique directory structure. The user parameter namespace will get noisy quickly and it will be painful remember which parameters go with which dataset in a catalog. To me it makes more sense to pass these parameters either
1. As chained catalogs e.g. `cat.wod.2020.wod_pfl_2020.read()` (seems close to the zillow plugin behavior)
2. As part of the read() operation like `cat.wod.read(year=2024, reading_type="pfl")`

Are either of these approaches possible today?

**Comment by martindurant** [comment]
Firstly, in my previous example, I put the user-parameter at the catalog root (`store_to="Catalog"`) just so it would show up more clearly, but this is a choice. With good design, you would want to provide appropriate description and examples to users.

Here is a simple way to produce hierarchical catalogues using multiple files.
```python
# as before
import intake
url = "https://noaa-wod-pds.s3.amazonaws.com/2023/wod_pfl_2023.nc"
data = intake.readers.datatypes.HDF5(url)
reader = data.to_reader("xarray")

# one sub-catalog
cat2023 = intake.Catalog()
cat2023["wod"] = reader
cat2023.to_yaml_file("2023.yaml")  # persist

# main catalog
cat = intake.Catalog()
cat_reader = intake.readers.YAMLCatalogReader("2023.yaml")
cat["2023"] = cat_reader
cat.to_yaml_file("cat_main.yaml")  # persist

# usage
cat = intake.open_catalog("cat_main.yaml")
cat["2023"].read() # to interrogate the sub-cat
cat["2023"].wod.read()  # to go straight to access in one line
```
(sorry, I seem to have inverted the levels you suggested)

Of course, you can combine the multi-file and user-parameters ideas. 

The zillow "multiple catalogs in one file" (giving the nice dot-access syntax) isn't implemented yet, but I can make this if what is above is not enough.

**Comment by nshankar** [comment]
Thanks Martin, I think this is sufficient for my needs! Closing the issue

**Comment by khalsz** [comment]
Hi [martindurant](https://github.com/martindurant). 
I tried the approach you mentioned above in creating hierarchical catalogues using multiple files. however, because the last catalogue file which is loaded from the root catalog file requires parameters, but considering that it is of type `YAMLCatalogReader reader producing intake.readers.entry:Catalog`, it does not let me include the parameters. is there a way around this?
