### ISSUE TITLE
What sort of methods can I apply to transform data?

### ISSUE THREAD

**Issue by kthyng** [intake/intake#813]
Hi! I am working with text files that require some basic processing that I would like to do in an intake catalog itself. I am stuck on one type of problem though. I need to:
1. read in the file without parsing time, 
2. fix a single time value, 
3. then parse the times. 

I can do this with pandas fine. I have figured out steps 1 and 2 with in the intake v2 set up, but I can't get step 3 to work via various attempts. I either hit an error from trying to add columns together using integers (can't do that) or from using `.add` (weird error), or when I try my best to avoid all possible problems I still hit the following:
```
TypeError: object of type 'Pipeline' has no len()
```

<details>

```
TypeError                                 Traceback (most recent call last)
Input In [233], in <cell line: 31>()
     28 def parse_date2(reader):
     29     return pd.to_datetime(reader.year.astype(str).str.cat(reader.day_of_year.astype(str)).astype(str).str.cat(reader.time_utc.astype(str)), format='%Y%j%H%M')
---> 31 cat_prep["parse_dates"] = reader.apply(parse_date2(reader))

Input In [233], in parse_date2(reader)
     28 def parse_date2(reader):
---> 29     return pd.to_datetime(reader.year.astype(str).str.cat(reader.day_of_year.astype(str)).astype(str).str.cat(reader.time_utc.astype(str)), format='%Y%j%H%M')

File /opt/conda/envs/py39/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1063, in to_datetime(arg, errors, dayfirst, yearfirst, utc, format, exact, unit, infer_datetime_format, origin, cache)
   1061 elif is_list_like(arg):
   1062     try:
-> 1063         cache_array = _maybe_cache(arg, format, cache, convert_listlike)
   1064     except OutOfBoundsDatetime:
   1065         # caching attempts to create a DatetimeIndex, which may raise
   1066         # an OOB. If that's the desired behavior, then just reraise...
   1067         if errors == "raise":

File /opt/conda/envs/py39/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:192, in _maybe_cache(arg, format, cache, convert_listlike)
    188 cache_array = Series(dtype=object)
    190 if cache:
    191     # Perform a quicker unique check
--> 192     if not should_cache(arg):
    193         return cache_array
    195     unique_dates = unique(arg)

File /opt/conda/envs/py39/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:136, in should_cache(arg, unique_share, check_count)
    133 # default realization
    134 if check_count is None:
    135     # in this case, the gain from caching is negligible
--> 136     if len(arg) <= start_caching_at:
    137         return False
    139     if len(arg) <= 5000:

TypeError: object of type 'Pipeline' has no len()

```

</details>

This happens when I run the catalog step, not try to read it, which makes me think it is trying to run it at that point instead of later and that is the problem — it can't "save" the operation for later.

Do you have advice for if there is a type of date parsing I am allowed to use with readers and catalogs to use here? Let me know if this is too vague and I'll come up with a specific example to show.

**Comment by martindurant** [comment]
It would be better to see the catalog or your steps to create it, but 
```
reader.apply(parse_date2(reader))
```
looks wrong.
The argument should be a function that takes the output of the previous step, in this case DataFrame.

I'm not certain that I caught the intent of the code shown in the traceback, but it might look something like
```
def parse_date2(df: pd.DataFrame) -> pd.DataFrame:
    return pd.to_datetime(df.year.astype(str).str.cat(df.day_of_year.astype(str)).astype(str).str.cat(df.time_utc.astype(str)), format='%Y%j%H%M')

cat_prep["parse_dates"] = reader.apply(parse_date2)
```

(this works similar to dask's map_partitions as a way to chain operations, if you ever use that)

**Comment by kthyng** [comment]
Ah, ok.... Yes. I have been following examples such as in https://intake.readthedocs.io/en/latest/walkthrough2.html#slightly-less-simple and https://github.com/intake/intake/blob/master/examples/Take2.ipynb to see how to daisy chain together these pipelines of modifying the datasets but I did not understand that I should reference the dataset itself at some level (as "df" instead of as a "reader"). Kind of mind-bending. This did work directly as you wrote it actually, thank you very much. It's convoluted as I have it because I've been trying to narrow what the problem was but I was way off! This helped a lot. Thanks.

**Comment by martindurant** [comment]
It's also work pointing out a couple of things:
- reader.method(..) essentially does `reader.apply(method, ...)`
- the list of "known" transforms can be seen with the object `reader.transform`
- there are also "namespaces" of functions (not methods) that might apply, such as pd.* for DataFrames
- some of these names can clash! For example, reader.apply calls the Intake apply function, so if you want to do df.apply, you need to do `reader.apply(DataFrame.apply, ...)`

**Comment by kthyng** [comment]
Thank you!
