### ISSUE TITLE
How to modify metadata for entries in catalog that already exists

### ISSUE THREAD

**Issue by kthyng** [intake/intake#830]
Is there a way to modify the metadata for catalog entries that already exist? Modifications I make are ignored and the workaround I tried didn't worked so far (making a new reader from the existing catalog entry, modifying that, deleting the existing entry, adding the modified entry). 

Here is a generic piece of code to demo the issue:

```
import intake
import pandas as pd

# make test catalog, copying from intake test
df = pd.DataFrame(
{
    "col1": ["a", "b"],
    "col2": [1.0, 3.0],
},
    columns=["col1", "col2"],
)

fname = "testfile.csv"
df.to_csv(fname)
reader = intake.reader_from_call("df = pd.read_csv(fname)")

cat = intake.entry.Catalog()
cat["test"] = reader

# now modify metadata in catalog
cat["test"].metadata.update({"blah": "blahblah"})
```

and you get:

```
cat["test"].metadata
```
is `{}`. Interestingly, if you do `cat.metadata` instead, which was not my intended test, it does actually work.

I struggled with this in intake v1 too but I found a workaround by modifying the metadata within `cat[source_name].describe().metadata` did keep the changes, however, I don't see that as an option in v2. Thanks for your help.

**Comment by martindurant** [comment]
> cat["test"].metadata.update({"blah": "blahblah"})

This materializes the reader from the reader description in the catalog, substituting in any other data, reader and user_parameter values. You *could* take this reader, edit it as you have, and assign it back into the cat. But better would be to edit in place like
```python
cat.get_entity("test").metadata.update(..)
```

**Comment by martindurant** [comment]
(this is the same as 
```
cat.entries["test"].metadata.update(..)
```
but `get_entity` will follow any aliases and give you back any named thing, data, reader or user_parameter

**Comment by kthyng** [comment]
Ok! I was able to get this to work in the example code:

```
import intake
import pandas as pd

fname = "testfile.csv"
reader = intake.reader_from_call("df = pd.read_csv(fname)")

cat = intake.entry.Catalog()
cat["test"] = reader

# now modify metadata in catalog
cat.get_entity("test").metadata.update({"blah": "blahblah"})
```

However, it is still not working in my more complex real code, so apparently my simple code was not complex enough to capture the real issue.

I now specifically update `.aliases` in my code so I do have those, but `cat.entries` is `{}` (this is the catalog I have just been updating to v2).

**Comment by martindurant** [comment]
> but cat.entries is {}

I think you are creating entities in .data , but get_entity should find them anyway

**Comment by kthyng** [comment]
You're right — I've been modifying the metadata successfully in other v2 catalogs I've been working with but haven't been able to in the v2 catalog I updated recently and didn't realize it was specific to that. Any chance you'd be willing to try out [my branch](https://github.com/kthyng/intake-erddap/tree/update_intake) of `intake-erddap` where I have my changes to update to v2 of intake? This code snippet then demos how I can't seem to modify the metadata

```
import intake_erddap

cat = intake_erddap.ERDDAPCatalogReader(server="https://erddap.aoos.org/erddap", search_for=["aoos_204"]).read()
source_name = list(cat)[0]
cat.get_entity(source_name).metadata.update({"blah": "blahblah"})
```

```
cat[source_name].metadata
```
Returns:
```
{'datasetID': 'aoos_204',
 'institution': 'Alaska Ocean Observing System (AOOS)',
 'title': 'Lower Cook Inlet, AK, CDIP Wave and Current Buoy 204 (46108)',
 'summary': "Timeseries data from 'Lower Cook Inlet, AK, CDIP Wave and Current Buoy 204 (46108)' (aoos_204)",
 'minLongitude': -151.8291,
 'maxLongitude': -151.8291,
 'minLatitude': 59.5973,
 'maxLatitude': 59.5973,
 'minTime': '2013-07-21T19:22:27Z',
 'maxTime': '2024-06-24T16:45:00Z',
 'griddap': '',
 'tabledap': 'https://erddap.aoos.org/erddap/tabledap/aoos_204',
 'info_url': 'https://erddap.aoos.org/erddap/info/aoos_204/index.csv'}
```
which does not include any "blahs".

**Comment by martindurant** [comment]
Ping me tomorrow and I can have a look

**Comment by martindurant** [comment]
I think the following line is needed
```diff
--- a/intake/readers/entry.py
+++ b/intake/readers/entry.py
@@ -65,7 +65,7 @@ class DataDescription(Tokenizable):
         ups = self.user_parameters.copy()
         ups.update(user_parameters or {})
         kw = self.get_kwargs(user_parameters=ups, **kwargs)
-        return cls(**kw)
+        return cls(**kw, metadata=self.metadata)

     def __call__(self, **kwargs):
```

**Comment by kthyng** [comment]
`metadata` is already in `kw`, though just the original set of metadata, not the updated metadata.

**Comment by martindurant** [comment]
I don't think it is, else you would get a duplicate keyword error on my line

**Comment by kthyng** [comment]
I did — I tried adding it in and got:

```
In [1]: import intake_erddap
   ...: 
   ...: cat = intake_erddap.ERDDAPCatalogReader(server="https://erddap.aoos.org/erddap", search_for=["aoos_204"]).read()
   ...: source_name = list(cat)[0]
   ...: cat.get_entity(source_name).metadata.update({"blah": "blahblah"})

In [2]: cat[source_name].metadata
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 cat[source_name].metadata

File ~/packages/intake/intake/readers/entry.py:519, in Catalog.__getitem__(self, item)
    517     item = self.data[item]
    518     item = self._rehydrate(item)
--> 519     return item.to_data(user_parameters=ups, **(kw or {}))
    520 else:
    521     raise KeyError(item)

File ~/packages/intake/intake/readers/entry.py:68, in DataDescription.to_data(self, user_parameters, **kwargs)
     66 ups.update(user_parameters or {})
     67 kw = self.get_kwargs(user_parameters=ups, **kwargs)
---> 68 return cls(**kw, metadata=self.metadata)

TypeError: intake_erddap.erddap.TableDAPSource() got multiple values for keyword argument 'metadata'
```

**Comment by martindurant** [comment]
OK, so maybe in my little trial, there was no initial metadata. I'll get back to you tomorrow.

**Comment by kthyng** [comment]
@martindurant Ping to take a look at this if you can.

**Comment by kthyng** [comment]
I just pulled all the latest updates from github and ran this same snippet:

```
import intake_erddap

cat = intake_erddap.ERDDAPCatalogReader(server="https://erddap.aoos.org/erddap", search_for=["aoos_204"]).read()
source_name = list(cat)[0]
cat.get_entity(source_name).metadata.update({"blah": "blahblah"})
```

then
```
cat[source_name].metadata
```

and am getting that same error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 cat[source_name].metadata

File ~/packages/intake/intake/readers/entry.py:519, in Catalog.__getitem__(self, item)
    517     item = self.data[item]
    518     item = self._rehydrate(item)
--> 519     return item.to_data(user_parameters=ups, **(kw or {}))
    520 else:
    521     raise KeyError(item)

File ~/packages/intake/intake/readers/entry.py:68, in DataDescription.to_data(self, user_parameters, **kwargs)
     66 ups.update(user_parameters or {})
     67 kw = self.get_kwargs(user_parameters=ups, **kwargs)
---> 68 return cls(**kw, metadata=self.metadata)

TypeError: intake_erddap.erddap.TableDAPSource() got multiple values for keyword argument 'metadata'
```

Any idea where to go from here for being able to add metadata?

**Comment by martindurant** [comment]
Did you implement my suggestions in https://github.com/martindurant/intake-erddap/tree/update_intake ?

**Comment by kthyng** [comment]
Ok so I see your change and I've been working with it. Now my entry metadata isn't included since you moved it from a kwarg to a separate input. 

https://github.com/kthyng/intake-erddap/blob/0b4e66b02bd2c625ec7900a0a2f5b0510f89d925/intake_erddap/erddap_cat.py#L462-L464
```
            metadata["info_url"] = e.get_info_url(
                response="csv", dataset_id=dataset_id
            )
```
is no longer carried forward into the catalog entries with the change.

**Comment by martindurant** [comment]
At the current state of that branch (commit inline below), I do see the info_url make it into the reader:
```
In [48]: import intake_erddap

In [49]: cat = intake_erddap.ERDDAPCatalogReader(server="https://erddap.aoos.org/erddap", search_for=["aoos_204"]).read()

In [50]: list(cat)
Out[50]: ['aoos_204']

In [51]: cat.aoos_204.metadata
Out[51]:
{'datasetID': 'aoos_204',
 'institution': 'Alaska Ocean Observing System (AOOS)',
 'title': 'Lower Cook Inlet, AK, CDIP Wave and Current Buoy 204 (46108)',
 'summary': "Timeseries data from 'Lower Cook Inlet, AK, CDIP Wave and Current Buoy 204 (46108)' (aoos_204)",
 'minLongitude': -151.8291,
 'maxLongitude': -151.8291,
 'minLatitude': 59.5973,
 'maxLatitude': 59.5973,
 'minTime': '2013-07-21T19:22:27Z',
 'maxTime': '2024-07-03T14:15:00Z',
 'griddap': '',
 'tabledap': 'https://erddap.aoos.org/erddap/tabledap/aoos_204',
 'info_url': 'https://erddap.aoos.org/erddap/info/aoos_204/index.csv'}

In [52]: intake_erddap.__version__
Out[52]: '0.1.dev156+g0b4e66b'
```

**Comment by kthyng** [comment]
Do you mean with your change to the branch and newest changes in intake, you still see the metadata?

I'm having the metadata come and go when I add and remove that change in intake-erddap.

So, with your newest changes in intake, when intake-erddap is like this:
```
            entries[dataset_id] = DataDescription(
                datatype,
                kwargs={"dataset_id": dataset_id, **args},#, "metadata": metadata,},
                metadata=metadata,
            )
```
the metadata is gone
and when intake-erddap is like this:
```
            entries[dataset_id] = DataDescription(
                datatype,
                kwargs={"dataset_id": dataset_id, **args, "metadata": metadata,},
                # metadata=metadata,
            )
```
the metadata is back. I think I need to have that metadata hooked up correctly in erddap.py but I am not sure how to do that.

**Comment by martindurant** [comment]
Actually, it has
```
            entries[dataset_id] = DataDescription(
                datatype,
                kwargs={"dataset_id": dataset_id, **args},
                metadata=metadata,
            )
```
https://github.com/martindurant/intake-erddap/blob/update_intake/intake_erddap/erddap_cat.py#L465

and this is with intake at efbf5c8 , which is the same as master right now.

**Comment by kthyng** [comment]
Ok yes, I am sorry. I see that I reinstalled `intake-erddap` locally and in doing so it reinstalled `intake` from PyPI and that was the problem. Now it is sorted so I am getting the same results as you regarding the metadata. This is great!

I do have another question — do you see why I am seeing this?
`cat[dataset_id].ToHvPlot(**plot_kwargs1).read()` gives me `AttributeError: 'TableDAPSource' object has no attribute 'ToHvPlot'`. I had thought that since I switched `TableDAPSource` to inherit from `BaseData` that I would be able to do this transform. I can create a full example if that will help.

**Comment by martindurant** [comment]
`TableDAPSource` is a data type, not a reader, and it has no associated readers. Looking at the code, I thing it feels more like a reader.

**Comment by kthyng** [comment]
`ERDDAPCatalogReader` is a reader, subclassing `BaseReader`. I just now tried switching `TableDAPSource` to subclass `BaseReader` too but it created a RecursionError at the `ToHvPlot` line. Are Catalogs meant to subclass something else?

**Comment by martindurant** [comment]
I pushed a commit to my branch showing the start of how I would rewrite the table source to be a reader. You'll notice that a lot of the code is simply gone: we don't keep hold of metadata or schema objects anymore, and the control flow is much more functional. That means that the arguments eventually fed to _read() are stored in `kwargs` rather that _ attributes, and show up properly. V2 readers are essentially stateless: they hold the arguments we want to pass on.

> it created a RecursionError at the ToHvPlot

This is probably because your reader has no output_instance, so intake didn't know that ToHvPlot could be a valid next step. You could have called it explicitly (like instantiating a reader rather than using to_reader()), but otherwise, intake assumes you mean to call a method called ToHvPlot on the output of the reader. Why that caused recursion, I am not sure. There are a few locations in the code guarding against recursion specifically for this "we are calling an unknown thing and assuming it makes a pipeline" case, so it would be good to find why this case is escaping.

**Comment by kthyng** [comment]
Interesting! Thanks for this work, I appreciate it. I had been wondering if I could remove a lot of that but was worried about going too far off course; plus, someone else had written a lot of it in the first place. I will take a look at it next week.

**Comment by martindurant** [comment]
Is the hang happening [here](https://github.com/axiom-data-science/intake-erddap/compare/main...martindurant:intake-erddap:update_intake?expand=1#diff-2c7d32319cafd9260f6ef948bc2d8f2c6416c03dc90e745038626c3e11c68d3cR153) ? If yes, the block above wasn't modified by me, you'll probably need a breakpoint there to figure out what's with the response variable and download-url. There may be more arguments you're supposed to pass to pandas.

**Comment by kthyng** [comment]
Ok I think I have it working! You were right, I dug in more and figured out a bunch of details which were unrelated to your changes. I hope to have it pushed tomorrow. Thanks again!

**Comment by kthyng** [comment]
I have the package working with intake v2 now. Thanks for your help through this process. https://github.com/axiom-data-science/intake-erddap
