### ISSUE TITLE
Removing entries from catalog?

### ISSUE THREAD

**Issue by kthyng** [intake/intake#844]
Can I remove or delete an entry or a set of entries from an existing catalog? Or alternatively can I keep a subset of entries in an existing catalog and make a new catalog object from it? Thanks!

**Comment by martindurant** [comment]
The dictionaries can be updated in place as you see fit, using for example `del` or `pop` will work fine. The catalog also has a `.delete()` method you can use, which will also look up and remove aliases. There is no current way to automatically remove readers or data entities that lose their referents.

**Comment by martindurant** [comment]
(and `del cat[thing]` is an alias for `cat.delete(thing)`.

**Comment by kthyng** [comment]
Thanks @martindurant. I had tried to discover some of these before and hadn't been able to have them work, but maybe I used the wrong syntax. 

Today I had trouble with `cat.delete(thing)` getting this:

```
In [5]: cat.delete('LCDeployment03Y2020')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 cat.delete('LCDeployment03Y2020')

File ~/packages/intake/intake/readers/entry.py:293, in Catalog.delete(self, name, recursive)
    281 """Remove named entity (data/entry) from catalog
    282 
    283 We do not check whether any other entity in the catalog refers *to*
   (...)
    290     they refer to in turn.
    291 """
    292 item = self.get_entity(name)
--> 293 del self[item]
    294 if recursive:
    295     raise NotImplementedError

File ~/packages/intake/intake/readers/entry.py:546, in Catalog.__delitem__(self, key)
    544 def __delitem__(self, key):
    545     # remove alias, data or entry with no further actions
--> 546     if key in self.aliases:
    547         self.data.pop(self.aliases[key], None)
    548         self.entries.pop(self.aliases[key], None)

File ~/packages/intake/intake/readers/utils.py:287, in Tokenizable.__hash__(self)
    285 def __hash__(self):
    286     """Hash depends on class name and all non-_* attributes"""
--> 287     return int(self.token, 16)

ValueError: invalid literal for int() with base 16: 'LCDeployment03Y2020'
```

but the variation

```
del cat['LCDeployment03Y2020']
```

worked fine so I just used that. Thanks again!!

**Comment by martindurant** [comment]
Fixed in https://github.com/intake/intake/pull/849
