### ISSUE TITLE
Slim down requirements

### ISSUE THREAD

**Issue by mrocklin** [intake/intake#97]
Currently the requirements file looks like the following:

```
jinja2
msgpack-numpy
msgpack-python
numpy
pandas
pytest
python-snappy
ruamel.yaml >= 0.15.0
requests
appdirs
six
tornado >= 4.5.1
dask[complete]
holoviews
```

This makes it difficult for downstream deployments to easily depend on it.  I wonder if perhaps some of these requirements could be made optional for minimal deployments.

**Comment by seibert** [comment]
Hmm, good question.  Let me run down the list:
* jinja2: needed for catalog files
* msgpack-numpy: needed for streaming data from remote catalog servers
* msgpack-python: needed for communication with remote catalog servers
* numpy: needed for array containers
* pandas: needed for dataframe containers
* pytest: only needed for running unit tests
* python-snappy: optionally needed for streaming data from remote catalogs
* ruamel.yaml: needed for catalog files
* requests: needed for communication with remote catalog servers
* appdirs: needed to find locally installed catalogs
* six: needed for python2/3 support
* tornado: needed for running catalog server
* dask: needed for to_dask
* holoviews: needed for plotting

So I think we could sort these out into groups:
* Core functionality (catalog YAML files with no server support): ruamel.yaml, jinja2, numpy, pandas, appdirs, six, dask (maybe not dask[complete])
* Plotting: holoviews
* Connection to catalog servers: msgpack-python, msgpack-numpy, requests, python-snappy
* Running catalog server: tornado + previous category
...and drop pytest from requirements entirely.

**Comment by mrocklin** [comment]
In dask we provide targets like `dask[array]` and `dask[distributed]` for this sort of breakdown

**Comment by mrocklin** [comment]
Something similar might be useful here.

**Comment by martindurant** [comment]
I would expect the server stuff to be much less used by the wider community, perhaps something only important to enterprise types; it could even potentially be a separate package at some point.
I have taken pains to have pandas and dask-array only imported at use, so they should not be required if there is no plugin that doesn't depend on them.

**Comment by bryevdv** [comment]
> In dask we provide targets like dask[array] and dask[distributed] for this sort of breakdown
 
How does that work on the conda side of things? Just separate packages?

@martindurant Is there a specific reason to use  `ruamel[\._]yaml` instead of `pyyaml`?

**Comment by mrocklin** [comment]
> How does that work on the conda side of things? Just separate packages?

We have a dask-core package that is minimal and then a dask package that includes many optional dependencies (like bokeh).

**Comment by bryevdv** [comment]
> We used more advanced features of YAML at some point, worth investigating whether that's still the case.

It appears ruamel will throw an error on duplicate keys (which intake relies on), but that pyyaml does not. There are workarounds here: https://gist.github.com/pypt/94d747fe5180851196eb but a python loader is presumably going to be slower.

**Comment by martindurant** [comment]
@bryevdv , speed of parsing YAML is unlikely to be an issue for us. I would agree with a move to pyyaml if it provided additional useful features, but I'm not convinced that moving just to remove the ruaml dependency is worth moving if we have to implement hacks. Having said all that, I think we [already do](https://github.com/ContinuumIO/intake/blob/master/intake/catalog/local.py#L268) ! I actually suspect the code may no longer be using anything from ruamel other that the exception class.

**Comment by danielballan** [comment]
What is the current thinking on moving intake's setup.py to a dask-like model with a slimmer core? #99 looks like a good draft to me.

**Comment by martindurant** [comment]
I am, in principle, ok with the idea.

The trouble really is on the conda side; there could be an intake-core package with minimum requirements and intake package which depends on it.

The reason this hasn't happened yet, is that the code has been changing a lot still, and I am wanting things to stabilise somewhat before making such a change. I imagine that most users are going from a pretty full pydata stack (e.g., anaconda main), so it's not really an issue.

**Comment by bryevdv** [comment]
> What is the current thinking on moving intake's setup.py to a dask-like model with a slimmer core?

I think this makes sense for intake, personally. The only reason we have not split Bokeh into "core" and "server" packages is because Bokeh only has like six dependencies to begin with. But Intake has more than double that, and will likely feel pressure to add even more given the essential nature of the project is to aid with integrating lots of different things. I think the split in #99 is a fairly natural one though it might be worth thinking about what keeping the "client" portion together with the "base" would look like. Essentially what I'd optimize for is the smallest split that partitions the dependencies the most. 

And the reason for that last statement is simply that, besides the benefits, there are also costs to splitting things up, in the form of coordination of maintenance, testing. intra-dependencies, and interfaces. I'd also mention that splitting packages may not imply splitting the repo. I'm definitely generally swayed by the "monorepo" viewpoint, so it's worth thinking about the question of 1 vs N repos explicitly.

**Comment by danielballan** [comment]
>  I'd also mention that splitting packages may not imply splitting the repo. 

Agreed. I did not think that splitting the repo was under consideration. I don't think it's necessary. I'm just hoping to land in a place where a user can pull down some remote data without installing Tornado or HoloViews.

**Comment by jsignell** [comment]
I thought a dependency graph  might help with the discussion:

<img src="https://gist.githubusercontent.com/jsignell/f4c342e3bcc2f5f2b10cfa803c7524b3/raw/69089e45a8ba4f07a78b8da52c9c80ca83670694/intake-conda.svg?sanitize=true">

**Comment by martindurant** [comment]
Now just colour-code those boxes by the conda package size :)  Except MKL, which would dominate everything, although it's optional. Note that you would see a different graph with conda-forge packages, which tend to have wider requirements, I think you would get qt5 in there.

**Comment by mrocklin** [comment]
If you're looking at conda packages then I would use `dask-core` rather than `dask`, which is a more all-features-included metapackage.

**Comment by jsignell** [comment]
> you would see a different graph with conda-forge 

Sorry should have specified - this graph is with deps from conda-forge.

> use dask-core

Right intake-core would ideally depend only on dask-core there is a lot of slimming down that can be done.

**Comment by mrocklin** [comment]
I just tried installing intake (@rabernat used it in a minimal example) and found that I had to install Jupyter and the whole PyViz stack.  In the future it would be great if either ...

1.  Intake didn't require these things
2.  People didn't use it in minimal examples

**Comment by martindurant** [comment]
I agree, and it is in the plan, but a number of things are still in flux. Perhaps following the craziness of anacondacon next week, I can start making progress on splitting into core and complete packages. Complete could also include a selection of driver packages, we'll see.

**Comment by mlshapiro** [comment]
@mrocklin thank you for bringing up this issue. We are developing a downstream package and I am going through the process of integrating intake.

For what its worth, the only real issue I ran into was with `python-snappy` while installing using `pip`. In the short term, making `snappy` an optional dependency should provide an error free install (for both conda and pip) on most anaconda and non-anaconda installs.

**Comment by martindurant** [comment]
snappy is certainly an optional dependency only.
Also, tornado and msgpack are only required by the server. There is certainly scope here.
